wireapp/wire-ios-sync-engine

.travis.yml, README.md
This PR adds travis support to this project.
=> Add .travis.yml and update readme

Source/AddressBookTracker.swift, Source/Registration/ZMAddressBook.h, Source/Registration/ZMAddressBook.m, Source/Registration/ZMAddressBookEncoder.h, Source/Registration/ZMAddressBookEncoder.m, Source/Synchronization/ZMAddressBookSync.m, Tests/Source/Registration/ZMAddressBookEncoderTests.m, Tests/Source/Synchronization/Transcoders/ZMAddressBookSyncTests.m, Tests/Source/Utility/AnalyticsTests.swift, zmessaging-cocoa.xcodeproj/project.pbxproj
**What's in this PR?**
* Adds address book upload tracking ([6980](https://wearezeta.atlassian.net/browse/ZIOS-6980))
=> Add address book upload analytics

Source/Synchronization/ZMAddressBookSync.m, Tests/Source/Synchronization/Transcoders/ZMAddressBookSyncTests.m
**What's in this PR?**
* If the address book has been marked to uploaded but did not have any changes it was rechecked on every operation loop.
=> Fix bug checking address book changes to often

Source/APNSPerformanceTracker.swift, Tests/Source/Utility/AnalyticsTests.swift
**What's in this PR?**
* Fixes the flaky test `testVOIPTimeDifferenceTracking` in `AnalyticsTests`
=> Inject the current date to avoid timing sensitive tests

.travis.yml
**What's in this PR?**
* Removes the build / test commands from the `.travis.yml` as they were timing out (> 50min)
* Travis is only used for checking the PR using Danger, the build and testing is being done on Jenkins.
=> Use travis only to run Danger

Source/Synchronization/Strategies/AddressBookUploadRequestStrategy.swift, Tests/Source/Synchronization/Strategies/AddressBookUploadRequestStrategyTest.swift
This restores the behaviour that was present at version: https://github.com/wireapp/wire-ios-sync-engine/blob/a84e152d82fde41e5a961eb2cf505c067150680c/Source/Synchronization/ZMAddressBookSync.m#L153 and then removed. Not that this is not the final implementation of the feature: that behaviour was not as designed, and will eventually be fixed (soonish).
- Parsing response of address book search request
With this pull request we have a similar issue that will be addressed later. The issue is that, since we search in batches, and take the response of a batch as the new list of suggestions, at any given time the suggestions will be the ones coming from the last batch upload. If the user has more contacts than the batch size (will upload more than one batch), the suggestions will change …
=> Parse suggestions from address book search result

Tests/Source/Utility/AnalyticsTests.swift
* The tests did not compile anymore
=> Fix test compilation

Resources/es.lproj/Push.strings, Resources/es.lproj/Push.stringsdict, Resources/ru.lproj/Push.strings, Resources/ru.lproj/Push.stringsdict, Resources/uk.lproj/Push.strings, Resources/uk.lproj/Push.stringsdict, zmessaging-cocoa.xcodeproj/project.pbxproj
- Adding support for Ukrainian, Spanish and Russian localization
- Adding localized strings from Crowdin for new languages
=> Adding Ukrainian, Spanish and Russian localization

Source/Synchronization/Transcoders/ZMClientMessageTranscoder.m, Source/UserSession/BackgroundAPNSConfirmationStatus.swift, Tests/Source/E2EE/MissingClientsRequestStrategyTests.swift, Tests/Source/Integration/APNSTests.m, Tests/Source/Integration/ConversationTests+Confirmation.swift, Tests/Source/MessagingTest.h, Tests/Source/Synchronization/Transcoders/ZMClientMessageTranscoderTests.m
**In this PR**
We will not send confirmation messages for now.
Note: Since I couldn't run tests, I am not 100% sure I removed all related tests.
=> Do not send confirmation messages

Resources/de.lproj/Push.strings, Resources/de.lproj/Push.stringsdict, Resources/pt-BR.lproj/Push.strings
What's in this PR
- Added DE and pt-BR localization for reactions
=> Added localization for reactions

Tests/Source/Integration/ConversationsTests.m
This PR adds a couple of negative integration tests on the like feature.
=> Negative Integrations tests for like

Tests/Source/Synchronization/EventDecoderTests.swift
* Adds a test to verify each event is only processed once in `EventDecoder`
* This test is currently **failing intentionally** and was added to track the progress on this issue.
____
The `EventDecoder` API was converted to be asynchronous to fix the multithreading violations and avoid too many -performGroupedBlockAndWait: calls in #53, this current implementation however has the limitation that if called successively, the same events can be processed multiple times.
_Consider the following example:_
While processing the notification stream the event decoder creates lots of `StoreUpdateEvents` and stores them in the event database (accessed through the `eventMOC`), as clients need to be added on the `syncMOC` and the actual forwarding to the transcoders is done on the `syncMOC` a couple of …
=> Add test to verify each event is only processed once in `EventDecoder`

Tests/Source/UserSession/ZMStoredLocalNotificationTests.m
The test `testThatItCreatesAStoredLocalNotificationFromALocalNotification` was failing
- removed unused code
- create a local notification from a message, not from an event
=> Fix failing testThatItCreatesAStoredLocalNotificationFromALocalNotification test

Tests/Source/E2EE/ConversationTests+OTR.m
* There was no assertion in `testThatItNotifiesWhenInsertingCannotDecryptMessage ` that checked if the observer was actually called at all, only if it was called with the correct data when it was called, which made this test wrongfully pass.
=> Add assertion to make sure the observer block has been called

Source/UserSession/BackgroundAPNSConfirmationStatus.swift, Tests/Source/UserSession/BackgroundAPNSConfirmationStatusTests.swift
We changed the name for the background activity in the project, but not in the tests.
=> Use correct name background activity name

Source/Synchronization/Strategies/UserClientRequestFactory.swift
* `NSJSONSerialization` crashed when trying to write a `Swift.UInt16`, we now box it in a `NSNumber`.
* There also were a couple of optionals in the payload which have been removed.
* Removed unnecessary casts to optional `ZMTransportData` or optional `AnyObject`.
=> Wrap Swift.UInt16 in NSNumber for JSON serialization

Resources/de.lproj/Push.stringsdict, Resources/es.lproj/Push.strings, Resources/it.lproj/Push.strings, Resources/it.lproj/Push.stringsdict, Resources/ja.lproj/Push.strings, Resources/ja.lproj/Push.stringsdict, Resources/nl.lproj/Push.strings, Resources/nl.lproj/Push.stringsdict, Resources/tr.lproj/Push.strings, Resources/tr.lproj/Push.stringsdict, zmessaging-cocoa.xcodeproj/project.pbxproj
What in this PR:
- Adding support for new languages: Japanese, Italian, Dutch, Turkish
- Fixing one Spanish string's translation
=> Adding support for new languages: Japanese, Italian, Dutch, Turkish

Source/Analytics/RequestLoopAnalyticsTracker.swift, Source/Public/ZMUserSession.h, Source/UserSession/ZMUserSession.m, zmessaging-cocoa.xcodeproj/project.pbxproj
In this PR, we now react to request loop and track the occurrences, with the path.
It also notifies the UI about it.
=> Implement tracking for request loop

Resources/da.lproj/Push.strings, Resources/da.lproj/Push.stringsdict, Resources/de.lproj/Push.stringsdict, Resources/es.lproj/Push.strings, Resources/fr.lproj/Push.strings, Resources/fr.lproj/Push.stringsdict, Resources/it.lproj/Push.strings, Resources/ja.lproj/Push.strings, Resources/nl.lproj/Push.strings, Resources/pt-BR.lproj/Push.strings, Resources/ru.lproj/Push.strings, Resources/tr.lproj/Push.strings, Resources/uk.lproj/Push.strings, zmessaging-cocoa.xcodeproj/project.pbxproj
- Added new languages: Danish, French
- Added translation (or English placeholders) for push notifications for ephemeral messages
- Fixed unnecessary whitespaces added by Crowdin to German push notifications
=> Added localisation for release 2.20

Resources/de.lproj/Push.strings, Resources/es.lproj/Push.strings, Resources/ja.lproj/Push.strings, Resources/ja.lproj/Push.stringsdict
- Added some missing translations and updated some existing strings
=> Updated localisations for release 2.21

Resources/zh-Hans.lproj/Push.strings, Resources/zh-Hans.lproj/Push.stringsdict, zmessaging-cocoa.xcodeproj/project.pbxproj
- Added support for Simplified Chinese language
- Imported already localised strings from Crowdin
=> Added Simplified Chinese localization

Source/Calling/ZMCallKitDelegate.m
Calls grouping breaks AVS unfortunately.
=> Disable calls grouping

Resources/sl.lproj/Push.strings, Resources/sl.lproj/Push.stringsdict, zmessaging-cocoa.xcodeproj/project.pbxproj
- Added support for Slovenian language
- Imported already localised strings from Crowdin
=> Added Slovenian localization

Source/Calling/ZMCallKitDelegate.m
Sometimes CallKit got stuck in the inconsistent call state, this seems to happen due to incorrect handling of call "Answer" button.
In `requestStartCallInConversation:videoCall:` we always indicated the new call starting, whereas when we answer the call we are supposed to indicate not the new call but answer on existing one.
Also included the CallKit logs into call log that users are able to forward to Wire, this should help with debugging in the future.
=> Updated CallKit call join logic; added CallKit log to call log

Source/Calling/ZMCallKitDelegate.m
Sometimes app fails to start recording; this is to try to configure audio session on AVS side.
=> Do not try to extra configure audio session

Source/Calling/ZMCallKitDelegate.m
Reverts wireapp/wire-ios-sync-engine#131
=> Revert "Do not try to extra configure audio session"

Source/UserSession/Search/TopConversationsDirectory.swift, Tests/Source/UserSession/TopConversationsDirectoryTests.swift
* Add the possibility the subscribe to changes to the top conversations using a `TopConversationsDirectoryObserver`.
=> Add observer to top conversations

Source/UserSession/Search/Internal/ZMSearch.m, Source/UserSession/Search/Internal/ZMSearchRequestCodec.h, Source/UserSession/Search/Internal/ZMSearchRequestCodec.m, Source/UserSession/Search/ZMSearchDirectory.m, Tests/Source/UserSession/Search/ZMSearchDirectoryTests.m, Tests/Source/UserSession/Search/ZMSearchRequestCodecTests.m
Filter user and group conversations from search result, when the query is a query for a username (`@query`)
=> Filter search results when searching by handle

Source/Registration/RandomHandleGenerator.swift, Tests/Source/Registration/RandomHandleGeneratorTests.swift
Characters handles were truncated at 22 characters instead of 21 characters
=> Characters handles were truncated at 22 instead of 21 characters

Resources/et.lproj/Push.strings, Resources/et.lproj/Push.stringsdict, zmessaging-cocoa.xcodeproj/project.pbxproj
- Added support for Estonian localisation
- Imported existing translations from Crowdin
Aitäh, @margusholland
=> Adding Estonian localisation

Source/Calling/ZMGSMCallHandler.m, Source/UserSession/ZMAuthenticationStatus.h, Source/UserSession/ZMAuthenticationStatus.m, Source/UserSession/ZMClientRegistrationStatus.m, Source/UserSession/ZMUserSession+Registration.m, Source/UserSession/ZMUserSession.m, Tests/Source/Integration/CallingTests.m, Tests/Source/Notifications/PushNotifications/ZMLocalNotificationSetTests.swift, Tests/Source/UserSession/ZMUserSessionTests.m
Concurrency issues on login and GSM call
=> Fix concurrency issues

Source/UserSession/ZMUserSession+Background.m
* Process pending changes after merging changes from remote contexts
=> Process pending changes after merging changes from remote contexts

Source/UserSession/CallStateObserver.swift, Tests/Source/Calling/CallStateObserverTests.swift
Fixes:
https://wearezeta.atlassian.net/browse/ZIOS-7957
https://wearezeta.atlassian.net/browse/ZIOS-7956
=> Fix incoming calls displayed as calls by you

Source/Calling/WireCallCenterV2.swift
Only line 254 is a fix: FlowManagerVideoReceiveStateNotification are probably not guaranteed to arrive on the correct thread.
The other changes are just improvements: The VoiceGainNotification can set the conversationID as object so you don't need to filter notifications when receiving them. Note that this only works if you cast the object to NSUUID otherwise it will fail comparing Any to UUID ¯\_(ツ)_/¯
=> perform changes from flowManagerDidChange notification on correct queue

Resources/Base.lproj/Push.strings
* Copy change as requested by design.
=> Use monochrome heart copy in push action to like a message

Source/Calling/ZMCallKitDelegate+WireCallCenter.swift, Source/Calling/ZMCallKitDelegate.m, Tests/Source/Calling/ZMCallKitDelegateTests.swift
Also the change that allows to end the call even if CallKit is refusing to end.
=> Do not ring with CallKit for muted conversations

Source/UserSession/Search/TopConversationsDirectory.swift, Tests/Source/UserSession/TopConversationsDirectoryTests.swift
* The last change  https://github.com/wireapp/wire-ios-sync-engine/pull/286 had a significant impact on the top people computation performance.
* We now try a different approach and enumerate all the messages of the last month in a conversation.
* The added performance test showed an improvement of over 1000% percent over the previous solution (but then again the test uses an in memory store...).
=> Reverse enumerate the messages relation instead of executing multiple fetches

Source/Calling/WireCallCenter.swift
* We need to check the user in order to know if the reason for the end of the call is `self` or `other`.
=> Track the call ended reason correctly when hanging up on calling device

Source/Synchronization/Strategies/UserImageAssetUploadStrategy.swift, Source/UserSession/UserProfileImageUpdateStatus.swift, Tests/Source/Synchronization/Strategies/UserImageAssetUploadStrategyTests.swift, Tests/Source/UserSession/UserProfileImageUpdateStatusTests.swift, zmessaging-cocoa.xcodeproj/project.pbxproj
This continues on work done in #292 by adding logic for uploading resized images to asset store.
=> Profile picture v3: Request strategy for uploading

Cartfile, Cartfile.resolved, Source/Calling/WireCallCenterV3.swift
- Allow setting CBR flag
- Listen to the CBR active callback
=> CBR support

Source/Data Model/ZMUser+UserSession.m, Source/Synchronization/Strategies/UserImageAssetUpdateStrategy.swift, Source/Synchronization/Strategies/UserImageAssetUploadStrategy.swift, Source/Synchronization/ZMSyncStrategy.m, Source/UserSession/UserProfileImageUpdateStatus.swift, Tests/Source/Synchronization/Strategies/UserImageAssetUpdateStrategyTests.swift, Tests/Source/UserSession/UserProfileImageUpdateStatusTests.swift, zmessaging-cocoa.xcodeproj/project.pbxproj
Updated request strategy to handle downloading v3 profile pictures
=> Profile picture v3: downloading v3 images when available

Source/UserSession/UserProfileImageUpdateStatus.swift, Tests/Source/UserSession/UserProfileImageUpdateStatusTests.swift, WireSyncEngine.xcodeproj/project.pbxproj
* Updated the implementation to be able to try uploading profile picture again after a failure.
* Updated tests and implementation to use correct MOCs which should hopefully make tests more reliable
* Removed Data Model added as a subproject
=> Profile picture v3: handle failures

Source/Calling/WireCallCenterV3.swift, Tests/Source/Integration/CallingV3Tests.swift
This fixes an issue where the outgoing video was missing when accepting a call.
https://wearezeta.atlassian.net/browse/ZIOS-8400
=> We need to dispatch onto the main queue before we do anything in the AVS handlers

Source/Calling/WireCallCenterV3.swift
```
<Error>: /Users/silvandaehn/Developer/Wire-App/wire-ios-sync-engine/Source/Synchronization/Strategies/CallingRequestStrategy.swift:133 calling Not sending calling messsage since it's not UTF-8
```
* When starting a call we send a special generic message containing a `String`. The memory containing the strings bytes is passed to us from `AVS`. Since changing the threading model and dispatching to the UI MOC we sometimes failed to create a UTF-8 `String`, as the memory has already been freed in some cases. We now immediately get the data from the pointer and pass the data to the `send` method.
=> Get data from pointer before dispatching

Source/UserSession/ZMEnvironmentsSetup.m
- Removed the edge environment since it's not supported any more.
=> Retire edge environment

Cartfile, Cartfile.resolved, Source/Calling/SystemMessageCallObserver.swift, Source/Calling/WireCallCenterV3.swift, Source/UserSession/CallStateObserver.swift, Tests/Source/Calling/WireCallCenterV3Tests.swift, Tests/Source/Integration/CallingV3Tests.swift
=> Update AVS, use timeStamp for missed call message

Source/Calling/SystemMessageCallObserver.swift, Source/UserSession/CallStateObserver.swift, Tests/Source/Calling/CallSystemMessageGeneratorTests.swift
If we miss a call we want to display a missed Call APNS even if we are using CallKit.
=> Post APNS about missed call when CallKit is enabled

Source/Synchronization/Strategies/UserImageStrategy.swift
Logging all the variables that the sync objects depend on
=> Added more logging to debug profile picture request loops

Source/Calling/VoiceChannel.swift, Source/Calling/VoiceChannelRouter.swift, Source/Calling/ZMCallKitDelegate.m
- prefix caller name with `(V2)` in callkit if we make/receive V2 calls.
https://wearezeta.atlassian.net/browse/ZIOS-8556
=> Expose callingProtocol on the VoiceChannel

Source/UserSession/CallStateObserver.swift
If we miss a call other people joined, we receive a call-ended-reason normal. In this case we still need to create an APNS.
=> create APNS for calls that other people joined, but we didn’t

Source/Synchronization/Strategies/UserImageAssetUpdateStrategy.swift, Source/Synchronization/Strategies/UserImageStrategy.swift, Source/Synchronization/Transcoders/ZMConversationTranscoder.m, Source/Synchronization/ZMCallStateRequestStrategy.m
* Update for new request strategy API.
=> Update for new request strategy API

Source/Synchronization/Transcoders/ZMConnectionTranscoder.m
This was causing a crash
https://rink.hockeyapp.net/manage/apps/65633/app_versions/1060/crash_reasons/171199425
=> Protocol method signature changed the compiler didn't complain :O

Source/Synchronization/ZMSyncStrategy.m
* Add `PermissionsDownloadRequestStrategy` to list of strategies.
=> Add PermissionsDownloadRequestStrategy to list of strategies

circle.yml
There is no customisation on SE for now, added the same config we use in other projects
=> CircleCI: using the same configuration

Tests/Source/Integration/ConversationTestsBase.h, Tests/Source/Integration/ConversationTestsBase.m, Tests/Source/Integration/IntegrationTest.swift, Tests/Source/Integration/LinkPreviewTests.m
=> Fix link preview tests

Tests/Source/Integration/ConversationTests+Confirmation.swift, Tests/Source/Integration/ConversationTests+Ephemeral.swift
* Fix `ConversationTests_Confirmation` and `ConversationTests_Ephemeral`.
=> Fix ConversationTests_Confirmation and ConversationTests_Ephemeral

Source/SessionManager/LocalStoreProvider.swift, Source/SessionManager/SessionManager.swift, Tests/Source/DiskDatabaseTest.swift, Tests/Source/E2EE/UserClientRequestFactoryTests.swift, Tests/Source/E2EE/UserClientRequestStrategyTests.swift, Tests/Source/MessagingTest.h, Tests/Source/MessagingTest.m, Tests/Source/Utility/AnalyticsTests.swift
* Update for https://github.com/wireapp/wire-ios-data-model/pull/337.
=> Update for usage with new data-model

Source/SessionManager/Account+Cookie.swift, Source/SessionManager/SessionFactories.swift, Source/SessionManager/SessionManager.swift, WireSyncEngine.xcodeproj/project.pbxproj
* Extract factory classes in separate files.
* Add comments to SessionManager.
=> Extract factories and add comments to SessionManager

Source/Notifications/Push notifications/Helpers/SessionTracker.swift, Source/Notifications/Push notifications/LocalNotificationDispatcher.swift, Source/Public/ZMUserSession+Authentication.h, Source/SessionManager/SessionManager.swift, Source/UserSession/ZMUserSession+Authentication.m, Tests/Source/Integration/IntegrationTest.swift, Tests/Source/SessionManager/SessionManagerTests.swift
* Fix crashes during teardown when logging out.
* Add a method to `SessionManager` to logout.
=> Fix teardown during logout

Source/Calling/FlowManager.swift, Source/Public/ZMUserSession.h, Source/UserSession/ZMUserSession.m
We rely on this notification in the UI.
=> Put back the flow manager did become available notification

Source/SessionManager/SessionManager.swift, Source/Synchronization/NSManagedObjectContext+EventDecoder.swift, Source/Synchronization/ZMOperationLoop.m, Tests/Source/SessionManager/SessionManagerTests.swift
- Plus some fixes for threading during logout.
=> Added account deletion

Source/Synchronization/Transcoders/ZMRegistrationTranscoder.m, Tests/Source/Integration/PhoneRegistrationTests.m
During the last refactoring we changed the behaviour and the notification is not called anymore when registering with phone number.
=> Triggering authenticationDidSucceed also when registering with phone

Source/Public/NSError+ZMUserSession.h, Source/SessionManager/SessionManager.swift, Tests/Source/Integration/IntegrationTest.swift, Tests/Source/SessionManager/SessionManagerTests.swift
- add addAcount method for informing the UI that we intend to logout & add account
- inform the session manager delegate of which account will attempt to open
=> Update SessionManager API for adding / switching account

Source/SessionManager/SessionManager.swift
- Not sure how the issue could happen, but for me the team account after some time got the image set, this should forbid it.
=> Remove user image for account with team

Source/Data Model/ConversationListChangeInfo+UserSession.swift, Source/Data Model/MessageChangeInfo+UserSession.swift, Source/Data Model/UserChangeInfo+ObserverHelper.swift, Source/UserSession/NotificationInContext+UserSession.swift, Source/UserSession/PostLoginAuthenticationNotification.swift, Source/UserSession/PreLoginAuthenticationNotification.swift, Source/UserSession/UserProfileImageOwner.swift, WireSyncEngine.xcodeproj/project.pbxproj
- Observers that do not require NSManagedObjectContext reference for use in UI code.
- Fixed warnings.
=> User Session observers

Source/E2EE/ZMUserSession+OTR.m, Source/SessionManager/SessionManager.swift, Source/UserSession/ClientUpdateNotification.swift, Source/UserSession/ClientUpdateStatus.swift, Source/UserSession/NotificationInContext+UserSession.swift, Source/UserSession/PostLoginAuthenticationNotification.swift
=> UI Integration fixes

Source/Calling/VoiceChannelV3.swift, Source/Calling/ZMCallKitDelegate.m, Source/Public/ZMUserSession.h, Source/SessionManager/SessionManager.swift, Source/UserSession/CallStateObserver.swift, Source/UserSession/ZMUserSession.m, Tests/Source/Calling/ZMCallKitDelegateTests.swift
- Allow switching CallKit on and off realtime
=> CallKit toggle

Source/Notifications/Push notifications/LocalNotificationDispatcher.swift, Source/Synchronization/Strategies/TypingStrategy.swift, Source/UserSession/UserProfile.swift, Source/UserSession/UserProfileUpdateNotifications.swift, Source/UserSession/UserProfileUpdateStatus.swift, Tests/Source/E2EE/UserClientRequestStrategyTests.swift, Tests/Source/Integration/UserHandleTests.swift, Tests/Source/Integration/UserProfileTests.m, Tests/Source/UserSession/UserProfileUpdateStatusTests.swift
also remove some unnecessary `NotificationCenter.default.removeObserver(self)`
=> Update UserProfileUpdateNotification to new notification system

Source/Calling/VoiceChannelV3.swift, Source/Calling/WireCallCenter.swift, Source/Calling/WireCallCenterV3+Notifications.swift, Source/Calling/WireCallCenterV3.swift, Source/Calling/WireCallCenterV3Factory.swift, Source/Data Model/NSManagedObjectContext+CTCallCenter.swift, Source/Public/ZMUserSession.h, Source/UserSession/ZMUserSession.m, Tests/Source/Calling/CallStateObserverTests.swift, Tests/Source/Calling/VoiceChannelParticipantV3SnapshotTests.swift, Tests/Source/Calling/VoiceChannelV3Tests.swift, Tests/Source/Calling/ZMCallKitDelegateTests.swift, Tests/Source/Integration/CallingV3Tests.swift, Tests/Source/UserSession/ZMUserSessionTestsBase+Calling.swift
- Required for calling in multiple accounts
=> Allow multiple WireCallCenterV3 objects

Source/Notifications/Push notifications/Notification Types/EventNotifications/ZMLocalNotificationForConnectionEvent.swift, Source/Notifications/Push notifications/Notification Types/EventNotifications/ZMLocalNotificationForEvent.swift, Source/Notifications/Push notifications/Notification Types/EventNotifications/ZMLocalNotificationForReactions.swift, Source/Notifications/Push notifications/Notification Types/MessageNotifications/ZMLocalNotificationForMessage.swift, Source/Notifications/Push notifications/Notification Types/MessageNotifications/ZMLocalNotificationForSystemMessage.swift, Source/Notifications/Push notifications/Notification Types/ZMLocalNotificationForCallState.swift, Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForMessageTests.swift
Also renamed `configureAlertBody` to `textToDisplay`
=> Add name of team to UI notifications

Source/UserSession/NotificationInContext+UserSession.swift, Source/UserSession/SyncStatus.swift
=> Fixes for threading

Source/SessionManager/SessionManager.swift, Source/Synchronization/ZMOperationLoop+Background.m, Source/Synchronization/ZMSyncStrategy+Internal.h, Source/Synchronization/ZMSyncStrategy.m, Tests/Source/Synchronization/ZMOperationLoopTests.m, Tests/Source/Synchronization/ZMSyncStrategyTests.m
A dot will be shown on the badge of the user, if a new message is sent to any of the authenticated accounts.
=> Unread messages dot

Source/SessionManager/SessionManager.swift
=> Added more session manager logs

Source/SessionManager/SessionManager.swift
If the unread count changes when the app is in background (new messages, or messages read on another client), then we want to sync the UI to these changes when the app returns to foreground.
=> update unread count when app enters foreground

Source/SessionManager/SessionManager.swift
- Issue happens that the app is started from the push notification.
- Added the precondition check to make sure the issue is not happening any more.
=> Make sure it is not possible to load the multiple sessions

Source/Calling/FlowManager.swift, Tests/Source/Calling/FlowManagerTests.swift, WireSyncEngine.xcodeproj/project.pbxproj
- Necessary to know when we can configure the flow manager for uploading the call stats
=> Notify when the AVS flow manager is created

Source/Synchronization/Transcoders/ZMConversationTranscoder.m, Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
If a client hasn't been active for long time we will not be able to sync the entire notifications stream when it comes back online. In this case we will perform "slow sync" which fetches the state of all the conversations and users among other things, in order to have an up-to-date state to apply new notification stream events on.
It can happen that while the client was offline that the self user was removed from conversations. We didn't check for this during the slow sync.
During the slow sync we fetch a list of all conversations the self user is currently active in. We can then remove the self user from all the conversations not in that list.
If we for some reason are removed from a conversation on the BE but we didn't do a slow sync and we try to fetch a conversation we will receive a …
=> Update self user group participation status on slow sync

Source/Utility/ZMSound.swift
Rename the None sound filename to `silence.m4a`
=> Rename None sound filename

Source/Calling/CallKitDelegate.swift, Tests/Source/Calling/CallKitDelegateTests.swift
When we receive calls quickly one after another in a conversation CallKit will stop working
Previously we would assign the remote identifier of the conversation where the call is happening
as the UUID of the call. This leads to problems when we report calls starting and ending quickly because Callkit needs several seconds to completely shutdown a call. If we re-use a UUID before the previous call as been deleted CallKit will stop working.
Assign a unique UUID for each call.
=> Assign a unique uuid for each CallKit call

Resources/lt.lproj/Push.strings, Resources/lt.lproj/Push.stringsdict, Resources/lt.lproj/ZMLocalizable.strings, Resources/zh-Hant.lproj/Push.strings, Resources/zh-Hant.lproj/Push.stringsdict, Resources/zh-Hant.lproj/ZMLocalizable.strings, WireSyncEngine.xcodeproj/project.pbxproj
We want the app to speak in more languages. We have translations for Traditional Chinese (50 million people) and Lithuanian (3 million people).
=> Add zh-Hant and lt translations

Resources/es.lproj/Push.strings, Resources/et.lproj/Push.stringsdict, Resources/et.lproj/ZMLocalizable.strings, Resources/zh-Hant.lproj/Push.strings, Resources/zh-Hant.lproj/Push.stringsdict
Update localization from crowdin
=> Update localization from crowdin

Source/Public/WireSyncEngine.h, Source/Synchronization/Transcoders/ZMConversationTranscoder.m, Source/Synchronization/Transcoders/ZMConversationTranscoder.swift, Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.swift, WireSyncEngine.xcodeproj/project.pbxproj
When conversation access mode is update we get an update event and need to handle it.
Unpacking the payload and setting new access mode and role for the conversation
=> Handling access update event

Source/SessionManager/SessionManager+Restore.swift, WireSyncEngine.xcodeproj/project.pbxproj
The new API expects to receive the URL to the archived backup to be restored. On successful restore the callback would be called. The callback would receive the instance of Account that would represent the newly restored account or an error.
=> Proposed API for backup restoring

Source/SessionManager/SessionManager+Backup.swift, Tests/Source/SessionManager/SessionManagerTests+Backup.swift
* Update history backup filename.
=> Update history backup filename

Source/SessionManager/SessionManager+Backup.swift, Tests/Source/SessionManager/SessionManagerTests+Backup.swift
=> Adjust backup naming

Source/SessionManager/SessionManager.swift, Tests/Source/SessionManager/SessionManagerTests+Backup.swift
* Delete old ephemeral messages after restoring from backup.
=> Delete old ephemeral messages after restoring from backup

Source/Data Model/ServiceUser.swift, Source/SessionManager/SessionManager+Backup.swift, Source/SessionManager/SessionManager.swift, Source/SessionManager/SessionManagerURLHandler.swift, Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift, WireSyncEngine.xcodeproj/project.pbxproj
The new API was added in order to allow handling the specially crafted URLs for Wire. First handled URL is the one to add the bot with the given ID to the conversation.
=> Added URL Handler, adding bots

Source/Calling/WireCallCenterV3.swift, Tests/Source/Integration/CallingV3Tests.swift
Drop an active call if the security level of the conversation degrades.
Writing a unit test which involves the `securityLevel` is not very easy today due to private initializers, so I added integration test instead.
=> Drop call if the conversation security degrades

Source/Calling/CallKitDelegate.swift
* Ensure .end call kit actions have completed when requesting a .start or .answer action.
=> Ensure .end call kit actions have completed when requesting a .start or .answer action

Source/UserSession/CallStateObserver.swift, Tests/Source/Calling/CallStateObserverTests.swift
* Unarchive cleared conversations when a call is incoming.
=> Unarchive cleared conversations when a call is incoming

Resources/Base.lproj/Push.strings, Source/Notifications/Push notifications/Notification Types/LocalNotificationContentType.swift, Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Localization.swift, Source/Notifications/Push notifications/Notification Types/ZMLocalNotification+Messages.swift, Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Event.swift
* Show pushes for message timer updates.
=> Show pushes for message timer updates

Source/Synchronization/ZMHotFixDirectory+Swift.swift, Tests/Source/Synchronization/ZMHotFixDirectoryTests.swift, Tests/Source/Synchronization/ZMHotFixTests.swift
Original migration test was not taking in account the new migration.
=> Fixed the hotfix tests

Resources/de.lproj/Push.strings
=> Add german translations

Resources/es.lproj/Push.stringsdict, Resources/et.lproj/Push.strings, Resources/fr.lproj/Push.strings, Resources/pt-BR.lproj/Push.strings, Resources/uk.lproj/Push.strings, Resources/zh-Hant.lproj/Push.strings
Localized strings updates for v3.17.
=> Updated "de|it|ja|pt-BR|es-ES|ru|uk|tr|nl|da|fr|zh-CN|sl|ar|et|fi|pl|zh-TW|lt" localized resources

Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForTests_CallState.swift
update testIncomingVideoCall after localized string is updated.
=> fix: testIncomingVideoCall

Source/Registration/Company/CompanyLoginRequester.swift, Tests/Source/Registration/CompanyLoginRequesterTests.swift
* Forward status code when validating company login token.
=> Forward status code when validating company login token

Source/Registration/Company/CompanyLoginRequester.swift
* Remove success and error callbacks from HEAD validation request.
=> Remove success and error callbacks from HEAD validation request

Source/Registration/Company/CompanyLoginRequester.swift, Tests/Source/Registration/CompanyLoginRequesterTests.swift
* Actually perform a HEAD request when validating a SSO token.
=> Actually perform a HEAD request when validating a SSO token

Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Messages.swift, Source/Notifications/Push notifications/Notification Types/LocalNotificationContentType.swift, Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
Disable mention notifications for now.
=> Temporarily disable mention notifications

Resources/Base.lproj/Push.strings
See also https://github.com/wireapp/wire-ios/pull/2742.
=> Align drafts placeholder with input bar copy

Resources/Base.lproj/Push.strings, Source/Notifications/Push notifications/Notification Types/NotificationAction.swift, Source/Notifications/Push notifications/Notification Types/PushNotificationCategory.swift, Source/UserSession/ZMUserSession+Actions.swift, Source/UserSession/ZMUserSession+Push.swift, Tests/Source/Calling/CallStateObserverTests.swift, Tests/Source/UserSession/ZMUserSessionTests+PushNotifications.swift
There will be more than one type of mute configuration and this action does not make sense anymore.
=> Remove mute button from notifications quick actions

Resources/ar.lproj/Push.strings, Resources/da.lproj/Push.strings, Resources/de.lproj/Push.strings, Resources/es.lproj/Push.strings, Resources/et.lproj/Push.strings, Resources/fi.lproj/Push.strings, Resources/fr.lproj/Push.strings, Resources/it.lproj/Push.strings, Resources/ja.lproj/Push.strings, Resources/lt.lproj/Push.strings, Resources/nl.lproj/Push.strings, Resources/pl.lproj/Push.strings, Resources/pt-BR.lproj/Push.strings, Resources/ru.lproj/Push.strings, Resources/sl.lproj/Push.strings, Resources/tr.lproj/Push.strings, Resources/uk.lproj/Push.strings, Resources/zh-Hans.lproj/Push.strings, Resources/zh-Hant.lproj/Push.strings
=> Updated strings for 3.22

Source/Calling/CallKitDelegate.swift, Source/Registration/ContactAddressBook.swift, Source/SessionManager/SessionManager.swift, Source/Synchronization/Strategies/AddressBookUploadRequestStrategy.swift, Source/UserSession/ZMUserSession+Calling.swift, Tests/Source/Calling/CallKitDelegateTests.swift, Tests/Source/Notifications/PushNotifications/ZMLocalNotificationLocalizationTests.swift
Since we removed the iOS 9 support we are fine to remove those.
=> Removed unnecessary old iOS versions compatibility

Resources/Base.lproj/Push.strings, Resources/ar.lproj/Push.strings, Resources/da.lproj/Push.strings, Resources/de.lproj/Push.strings, Resources/es.lproj/Push.strings, Resources/et.lproj/Push.strings, Resources/fi.lproj/Push.strings, Resources/fr.lproj/Push.strings, Resources/it.lproj/Push.strings, Resources/ja.lproj/Push.strings, Resources/lt.lproj/Push.strings, Resources/nl.lproj/Push.strings, Resources/pl.lproj/Push.strings, Resources/pt-BR.lproj/Push.strings, Resources/ru.lproj/Push.strings, Resources/sl.lproj/Push.strings, Resources/tr.lproj/Push.strings, Resources/uk.lproj/Push.strings, Resources/zh-Hans.lproj/Push.strings, Resources/zh-Hant.lproj/Push.strings, Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
Change copy of the message body  for an ephemeral reply to "Replied to you"
=> Update copy for ephemeral reply

Resources/Base.lproj/Push.strings, Resources/ar.lproj/Push.strings, Resources/da.lproj/Push.strings, Resources/de.lproj/Push.strings, Resources/es.lproj/Push.strings, Resources/et.lproj/Push.strings, Resources/fi.lproj/Push.strings, Resources/fr.lproj/Push.strings, Resources/it.lproj/Push.strings, Resources/ja.lproj/Push.strings, Resources/lt.lproj/Push.strings, Resources/nl.lproj/Push.strings, Resources/pl.lproj/Push.strings, Resources/pt-BR.lproj/Push.strings, Resources/ru.lproj/Push.strings, Resources/sl.lproj/Push.strings, Resources/tr.lproj/Push.strings, Resources/uk.lproj/Push.strings, Resources/zh-Hans.lproj/Push.strings, Resources/zh-Hant.lproj/Push.strings, Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
Update display string for reply notification for the design update.
=> Fix: update notification string to "replied to you"

Resources/ar.lproj/Push.strings, Resources/da.lproj/Push.strings, Resources/de.lproj/Push.strings, Resources/es.lproj/Push.strings, Resources/et.lproj/Push.strings, Resources/fi.lproj/Push.strings, Resources/fr.lproj/Push.strings, Resources/it.lproj/Push.strings, Resources/ja.lproj/Push.strings, Resources/lt.lproj/Push.strings, Resources/nl.lproj/Push.strings, Resources/pl.lproj/Push.strings, Resources/pt-BR.lproj/Push.strings, Resources/ru.lproj/Push.strings, Resources/sl.lproj/Push.strings, Resources/tr.lproj/Push.strings, Resources/uk.lproj/Push.strings, Resources/zh-Hans.lproj/Push.strings, Resources/zh-Hant.lproj/Push.strings
_This field was intentionally left blank._
=> Localization for 3.24

Source/UserSession/ZMUserSession+Background.m
Please refer to https://github.com/wireapp/wire-ios/pull/2933
=> Save when merging the background changes

Source/Calling/CallKitDelegate.swift
Add more logging when requesting CallKit actions
=> Improve CallKit logging

Source/Synchronization/ZMOperationLoop.m
When app is running in the background it should have an active background task or it can be suspended by iOS at any point. This sometimes happen when firing `ZMRequestAvailableNotification ` - the previous one has already been completed and new one has not been started yet. This leads to app running in the background for longer than needed.
The main problem is that when request completes we fire `ZMRequestAvailableNotification`. However this is done on a private queue when all other completion handlers have been called already. This means that all background tasks of running requests have been finished by now and there could potentially be a gap before we start a new one.
Start another background activity just after the request was generated and finish it after we fire the last …
=> Try to overlap background activities

Resources/Base.lproj/Push.strings, Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Alerts.swift
Copy has been shortened to better fit on smaller displays.
=> Update copy for availability local notification

Source/Synchronization/ZMHotFixDirectory.m
We need to re-fetch users after the e-mail field was introduced on the backend.
=> Include hot fix for re-fetching of users

Source/Notifications/Push notifications/LocalNotificationDispatcher+Messages.swift, Source/Notifications/Push notifications/LocalNotificationDispatcher.swift, Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Messages.swift, Source/SessionManager/SessionManager+Push.swift, Source/Synchronization/Strategies/PushTokenStrategy.swift, Source/UserSession/ZMUserSession+Actions.swift, Source/UserSession/ZMUserSession+Push.swift, Source/Utility/Logging.swift
Add more logging around scheduling local notifications.
=> Add more logging around scheduling local notifications

Source/UserSession/ZMUserSession+LegalHold.swift, WireSyncEngine.xcodeproj/project.pbxproj
We want to tell the backend that the user accepted the legal hold request.
Perform a one-time request when the user taps the legal hold approval button.
=> ZIOS-11412: Approve legal hold request

Tests/Source/Integration/ConversationsTests.m
`testThatItNotifiesTheObserverWhenTheHistoryIsClearedAndSyncsWithTheBackend` is unstable.
The test makes assumptions about the order in which requests are being made.
Remove the test since the code that it was originally testing no longer exists.
The test was introduced by: https://github.com/zinfra/rip/commit/4ee5345b408ac60f4d624a1c3d0ed29390c474b4
It was testing that the we were receiving a `ZMConversationWindowChangeNotification` when a conversation was cleared. The `ZMConversationWindow` used to be responsible for informing the UI about inserted/deleted messages. It has however since then been deleted and replaced by a `NSFetchResultsController`.
=> Delete outdated unstable integration test

Source/SessionManager/JailbreakDetector.swift
Added support for jailbreak detection on Sileo URL schemes (https://twitter.com/getsileo/status/1121199374107725825)
=> Feature: added support for detection of Sileo URL schemes

Source/Calling/VoiceChannel.swift
Expose mute state observer method on the `VoiceChannel`
=> Expose mute state observer method

Resources/ar.lproj/Push.strings, Resources/da.lproj/Push.strings, Resources/de.lproj/Push.strings, Resources/es.lproj/Push.strings, Resources/et.lproj/Push.strings, Resources/fi.lproj/Push.strings, Resources/fr.lproj/Push.strings, Resources/it.lproj/Push.strings, Resources/it.lproj/Push.stringsdict, Resources/ja.lproj/Push.strings, Resources/lt.lproj/Push.strings, Resources/nl.lproj/Push.strings, Resources/pl.lproj/Push.strings, Resources/pt-BR.lproj/Push.strings, Resources/ru.lproj/Push.strings, Resources/ru.lproj/Push.stringsdict, Resources/sl.lproj/Push.strings, Resources/tr.lproj/Push.strings, Resources/uk.lproj/Push.strings, Resources/zh-Hans.lproj/Push.strings, Resources/zh-Hant.lproj/Push.strings
Pulled latest localization from crowdin.
=> Updated localization

Cartfile
clean up version format in Cartfile
=> Clean up Cartfile

Source/Analytics/Analytics+Push.swift, Source/Data Model/ServiceUser.swift, Source/Data Model/UserChangeInfo+UserSession.swift, Source/Notifications/Push notifications/Helpers/ZMLocalNotificationSet.swift, Source/Notifications/Push notifications/LocalNotificationDispatcher+Calling.swift, Source/SessionManager/SessionManager+Backup.swift, Source/Synchronization/Strategies/ProxiedRequestStrategy.swift, Source/Synchronization/Strategies/TeamInvitationRequestStrategy.swift, Source/UnauthenticatedSession/UnauthenticatedSession+Login.swift, Source/UserSession/NotificationInContext+UserSession.swift, Source/UserSession/PreLoginAuthenticationNotification.swift, Source/UserSession/ZMUserSession+Actions.swift, Source/UserSession/ZMUserSession+Push.swift, Tests/Source/Integration/ConversationTests+Guests.swift, Tests/Source/Integration/IntegrationTest.swift, Tests/Source/Integration/SlowSyncTests+Swift.swift, Tests/Source/Integration/SlowSyncTests+Teams.swift, Tests/Source/Synchronization/Strategies/SearchUserImageStrategyTests.swift
=> Fix: reduce build time warning

Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.swift
Add a test to check the conversation.member-join event which contains the new defined roles in the field `conversation_role`.
=> Feature: Add a test to check the conversation.member-join event

Source/Synchronization/Transcoders/ZMConversationTranscoder.swift, Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m, Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.swift
=> Fix parsing member update event

Source/SessionManager/SessionManager.swift
Added logging for boot time updates
=> Log boot time updates

Source/UnauthenticatedSession/UnauthenticatedSession+DomainLookup.swift, Tests/Source/UserSession/UnauthenticatedSessionTests+DomainLookup.swift
- Update `config_json` to `config_json_url` after the spec changed.
- Make `configurationURL` public
=> [Fix] Fix domain lookup

Source/UnauthenticatedSession/UnauthenticatedSession+SSO.swift, Tests/Source/UserSession/UnauthenticatedSessionTests+SSO.swift, WireSyncEngine.xcodeproj/project.pbxproj
Add method on the unauthenticated session to fetch SSO settings
=> [Feature] Add method on the unauthenticated session to fetch SSO settings

Source/Calling/WireCallCenterV3+Events.swift, Source/Calling/WireCallCenterV3.swift, Source/Synchronization/Strategies/CallingRequestStrategy.swift
Add more detailed logging around sending calling messages
=> [Fix] Add more detailed logging around sending calling messages

Tests/Source/Data Model/ServiceUserTests.swift
Remove redundant code due to API change in https://github.com/wireapp/wire-ios-data-model/pull/942
=> [Chore] Remove redundant code

Source/Synchronization/Strategies/SignatureRequestStrategy.swift, Tests/Source/Synchronization/Strategies/SignatureRequestStrategyTests.swift, WireSyncEngine.xcodeproj/project.pbxproj
This PR provides tests that cover the SignatureRequestStrategy.
=> [Feature]Tests for the SignatureRequestStrategy

Cartfile, Cartfile.resolved, Source/Calling/AVSCallMember.swift, Source/Calling/AVSWrapper+Handlers.swift, Source/Calling/AVSWrapper.swift, Source/Calling/CallParticipantSnapshot.swift, Source/Calling/CallState.swift, Source/Calling/NetworkQuality.swift, Source/Calling/WireCallCenterV3+Events.swift, Source/Calling/WireCallCenterV3+Notifications.swift, Source/Calling/WireCallCenterV3.swift, Tests/Source/Calling/CallParticipantsSnapshotTests.swift, Tests/Source/Calling/VoiceChannelV3Tests.swift, Tests/Source/Calling/WireCallCenterV3Tests.swift
AVS 5.5.6 was reverted for the last release. It's re-integration will be included as part of the AVS 6 integration. This PR simply reverts the revert.
=> [Chore] Re-integrate AVS 5.5.6

Source/SessionManager/SessionManager+UserActivity.swift
remove unused parameter to prevent unnecessary casting in UI project
=> removed unused parameter in SessionManager.continueUserActivity

Source/Calling/WireCallCenterConfiguration.swift, Source/Calling/WireCallCenterV3.swift, Source/Calling/WireCallCenterV3Factory.swift, Source/SessionManager/SessionFactories.swift, Source/SessionManager/SessionManager.swift, Source/SessionManager/SessionManagerConfiguration.swift, Source/Synchronization/Strategies/CallingRequestStrategy.swift, Source/Synchronization/ZMSyncStrategy.h, Source/Synchronization/ZMSyncStrategy.m, Source/UserSession/ZMUserSession.swift, Tests/Source/Calling/AVSBridgingTests.swift, Tests/Source/Calling/WireCallCenterV3Mock.swift, Tests/Source/Calling/WireCallCenterV3Tests.swift, Tests/Source/Integration/IntegrationTest.swift, Tests/Source/SessionManager/SessionManagerTests.swift, Tests/Source/Synchronization/Strategies/CallingRequestStrategyTests.swift, Tests/Source/Synchronization/ZMSyncStrategyTests.m, Tests/Source/UserSession/ZMUserSessionTests.m, Tests/Source/UserSession/ZMUserSessionTestsBase+Calling.swift, Tests/Source/UserSession/ZMUserSessionTestsBase.h, Tests/Source/UserSession/ZMUserSessionTestsBase.m, WireSyncEngine.xcodeproj/project.pbxproj
This PR introduces `WireCallCenterConfiguration`, an object to contain information regarding customizable behavior. This configuration object is created as part of the `SessionManagerConfiguration` and therefore can be configured in `session_manager.json`.
=> [Feature] Call center configuration

Source/Calling/AVSCallMember.swift, Source/Calling/CallParticipantSnapshot.swift, Source/Calling/CallState.swift, Source/Calling/WireCallCenterV3+Events.swift, Tests/Source/Calling/CallParticipantsSnapshotTests.swift, Tests/Source/Calling/WireCallCenterV3Tests.swift
Added `microphoneState` property to `AVSCallMember`
=> [Feature] add support for microphone states

Source/Synchronization/Strategies/CallingRequestStrategy.swift
Similar to https://github.com/wireapp/wire-ios-sync-engine/pull/1292, call events aren't processed in the background.
The `CallingRequestStrategy` does not implement the `processEventsWhileInBackground(events:)` method.
Implement the method and remove the foreground processing method.
=> [Fix] Call events are not processed when the app is in the background

Source/UserSession/ZMUserSession+EncryptionAtRest.swift
Expose a user session protocol for the EAR feature, this will make it easier to write tests in the UI which interacts with the EAR functionality.
=> [Chore] Expose user session protocol for the EAR interface

Source/Calling/WireCallCenterV3Factory.swift
set the `useConferenceCalling` flag when creating call center
=> [Chore] set conference calling flag when creating call center

Source/Calling/WireCallCenterV3.swift, Source/Calling/WireCallCenterV3Factory.swift, Source/Data Model/NSManagedObjectContext+CTCallCenter.swift, Source/SessionManager/SessionManager.swift, Source/UserSession/ZMUserSession+Calling.swift, Tests/Source/Calling/WireCallCenterV3Tests.swift
- Remove the conference calling flag and update calling logic accordingly
=> [Chore] remove conference calling flag

Source/Calling/WireCallCenterV3.swift, Tests/Source/Calling/WireCallCenterV3Tests.swift
- mute user when answering call in group conversation
=> [Feature] mute when answering call in group conversation

Source/Calling/WireCallCenterV3.swift
- PR to trigger a minor release
=> [Chore] Trigger minor release

Source/Synchronization/ZMHotFixDirectory.m
Trigger a re-fetch of all users in order tor retrieve the qualified userID for all users.
=> [Chore] Re-fetch users after the introduction of qualified user IDs

crowdin.yml
This PR adds a crowdin config file which allows us to manage translations using the crowdin cli tool. It would also allow us to use the crowdin GitHub action.
=> [Chore] Add crowdin config

Tests/Source/SessionManager/SessionManagerTests.swift, Tests/Source/UserSession/ZMUserSessionTests+EncryptionAtRest.swift
BSI needs a documentation that contains security-relevant test cases which are mapped to security functions (SF) and interfaces (TSFI). Additionally we need to deliver a document for them which contains all test cases containing purpose, procedure, expected result and actual result.
This PR annotates unit/integration test cases with a comment in front of each test case function. This helps to automatically gather these test cases and create a document out of it.
There are additional pull requests in wire-ios and wire-ios-data-models like this.
See https://github.com/wireapp/bsi-mapping/ for the scripts that do the parsing and creation of the documents.
=> [Chore] Annotate tests for BSI

Source/SessionManager/SessionManager.swift
This is an empty PR to trigger a release.
=> [Chore] Trigger

Source/UserSession/ZMUserSession+SecurityClassification.swift, WireSyncEngine.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-96" title="FS-96" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-96</a>  [iOS] Fetch classified domains
</td></table>
<br />
----
----
Provides the classification between the self user and other users.
=> feat: provide classification FS-96

Tests/Source/UserSession/ZMUserSessionTests+Classification.swift, Tests/Source/UserSession/ZMUserSessionTests+SecurityClassification.swift, WireSyncEngine.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-96" title="FS-96" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-96</a>  [iOS] Fetch classified domains
</td></table>
<br />
----
----
Add unit tests for the security classification providing logic in user session
=> test: security classification tests FS-96

Source/SessionManager/SessionManager.swift, Source/UserSession/BlacklistReason.swift, Tests/Source/Integration/IntegrationTest.swift, Tests/Source/SessionManager/SessionManagerTests.swift, WireSyncEngine.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-482" title="FS-482" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-482</a>  [iOS] Block the app if no common api version is found
</td></table>
<br />
----
----
Create a `BlacklistReason` enum and added it as a parameter of `sessionManagerDidBlacklistCurrentVersion()` in order to report to the UI that the app has been blacklisted due to obsolete API version.
----
----
----
=> feat: support several blacklisting reasons FS-482
