- Source/Synchronization/Transcoders/ZMUserImageTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMUserImageTranscoderTests.m
- Issue happens in code that is needed to solve problem with some old issue when user has no image data, but his locally modified flags are indicating that the upload must be initiated
- Uploading images is supported only for self user for logical reasons
- I changed the code to check only self user if it needs to be fixed
- Originally doing this made the tests crashing, but it looks like there was a race condition while `init` is also loading self user in same context, so I decided to load in once and pass it in
- There is no way to verify if code change really fixes the issue, but we'll see from tracking. I think that root of the issue was loading self user in `init` and in grouped block on sync MOC (which was happening indirectly if predicate was really matching it).
> Fix for crash in user image transcoder

- Resources/de.lproj/Push.strings
- Resources/de.lproj/Push.stringsdict
- Resources/pt-BR.lproj/Push.strings
In this PR:
- Added Brazilian Portuguese translation for push notifcation quick action for call back
- Changed German translation for the push notification for missed call in a conversation without a name
> Added missing localization for 2.12

- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
It is possible for the decryption of an event to fail, returning a nil decrypted event.
We were not guarding for that eventuality, leading to a crash.
This PR fixes that.
> Fix of a crash on failed decryption

- Source/Synchronization/Transcoders/Helper/ZMSimpleListRequestPaginator.h
- Source/Synchronization/Transcoders/Helper/ZMSimpleListRequestPaginator.m
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.h
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Source/Synchronization/Transcoders/ZMSelfTranscoder.m
- Source/Synchronization/ZMSingleRequestSync.h
- Source/Synchronization/ZMSingleRequestSync.m
- Source/Synchronization/ZMSyncStrategy.m
- Source/UserSession/BackgroundAPNSPingBackStatus.swift
- Tests/Source/Integration/APNSTests.m
- Tests/Source/Integration/CallingTests+PushNotifications.m
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
- Tests/Source/Synchronization/ZMSingleRequestSyncTests.m
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
- Tests/Source/UserSession/BackgroundAPNSPingBackStatusTests.swift
It seems like the new notification stream strategy is causing crashes on the application that are not easily debuggable. The crash are random and sometime causing the phone to reboot.
This commit reverts the notification stream processing to the previous state.
We will continue the work on the new notification stream strategy on a separate branch and merge it back to develop only when stable enough.
> Revert notification stream changes

- Source/Synchronization/Transcoders/ZMUserImageTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMUserImageTranscoderTests.m
- Another approach to fixing the crashes happening in current release
- Originally self user was created from syncMOC on main thread
- Idea is that the data gets corrupted because of loading happening on the incorrect thread
> Load selfUser for syncMOC on syncMOC queue in UserImageTranscoder

- Source/Calling/ZMVoiceChannel+CallFlow.m
- Source/Notifications/ZMNotifications+UserSession.m
- Source/Notifications/ZMNotifications+UserSessionInternal.h
- Source/Synchronization/Strategies/ProxiedRequestStrategy.swift
- Source/Synchronization/Sync States/ZMEventProcessingState.m
- Source/Synchronization/Transcoders/ZMConnectionTranscoder.m
- Source/Synchronization/ZMCallStateTranscoder.m
- Source/UserSession/ZMBlacklistDownloader.m
- Source/UserSession/ZMUserSession+Background.m
Remove `dispatch_async` in favour or `performGroupedBlock` where possble
Where not possible, make sure to enter/leave groups.
Only using groups gives us the guarantee that tests will wait for the queue to be empty before moving to the next test. If we can't guarantee this, we will have a lot of flaky tests.
> Remove `dispatch_async` in favour or `performGroupedBlock` where possible

- Source/Notifications/Push notifications/ZMLocalNotificationForCallEvent.swift
- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
This PR fixes an issue where the user would not see notification when he/she missed a call.
This was due to the fact that we would update the last read timestamp of the conversation for event like `VoiceChannelActivate`, or any other event that does not generate a message or system message. This would lead to the clearing of notification, leaving us unable to update the call notification to a missed call. 
With this changed, the only kind of event that would update the conversation timestamp are successful call termination.
Additionally, we would wrongfully consider equivalent 2 call state events with the same ID and type, even though they might have a different sequence number. The sequence number is what identify in which order call state event happens, so 2 …
> Fix missed call notification

- Source/AddressBookTracker.swift
- Source/Synchronization/Strategies/AddressBookUploadRequestStrategy.swift
- Tests/Source/Synchronization/Strategies/AddressBookUploadRequestStrategyTest.swift
- Tests/Source/Utility/AnalyticsTests.swift
Address book search is missing analytics
Add two separate events:
- begin of address book processing / search request
- end of address book search, when the backend returns a 200
We have two events because it's possible that we start the search, but if we are in the background we fail to process the address book / submit the request before we get suspended or killed. We can look at the difference between the # of start events and the # of end events to know how many times we tried a search but we failed to complete it.
> Add tracking to address book search

- Source/Registration/AddressBook+Encoding.swift
- Source/Synchronization/Strategies/AddressBookUploadRequestStrategy.swift
- Source/Synchronization/ZMSyncStrategy.m
- Tests/Source/Synchronization/Strategies/AddressBookUploadRequestStrategyTest.swift
Address book search was not working
This bug was caused by a number of factors, all fixed in this PR:
- AddressBookUploadRequestStrategy not being added to list of strategies
- Backend returning 400 in case "self" key was missing in payload, even if it's ignored
- Async completion handler not being executed because the AddressBook instance was released in the meanwhile
Given the kind of issues that were found, it seems like this feature is missing proper component testing.  We will address that in future PR.
> Fix address book search not working

- Source/AddressBookTracker.swift
- Source/Synchronization/Strategies/AddressBookUploadRequestStrategy.swift
- Tests/Source/Utility/AnalyticsTests.swift
Missing "interval" parameter in AB search tracking
- Fixed not storing time of previous upload
- Also moved the "last uploaded" time from NSUserDefaults to the NSManagedObjectContext, so that in future deleting the context will reset the value
Previous tests were not catching this error as they were injecting the time of the previous upload artificially. Added a test that just uploads twice without artificially injecting the value.
> Fix missing interval in AB search tracking

- Source/Notifications/Push notifications/Notification Types/ZMLocalNotificationForEvent.swift
- Source/Notifications/Push notifications/ZMLocalNotificationDispatcher.m
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationDispatcherTest.m
(1) Moved notification creation for notifications with hidden content into `ZMLocalNotificationForEvent`. Previously we were creating a new `UILocalNotification` which we were not able to cancel (e.g. when opening the conversation) because we did  not keep a reference to it.
(2) Added notification sound
> move notification creation and add sound

- Source/Registration/AddressBook+Encoding.swift
- Tests/Source/Registration/AddressBookTests.swift
Address book search was stopping when it reaches the end of the AB. It should have restarted from the beginning.
Return empty chunk when we tried to generate a chunk past the 0 starting position and there were no more contacts. This will be interpreted as "I reached the end" and trigger the restart.
> Fix restart address book search from first batch

- Source/Synchronization/Decoding/EventDecoder.swift
- Source/Synchronization/Decoding/StoreUpdateEvent.swift
- Source/Synchronization/ZMSyncStrategy.m
- Source/UserSession/BackgroundAPNSConfirmationStatus.swift
- Tests/Source/Synchronization/EventDecoderTests.swift
- Tests/Source/Synchronization/StoreUpdateEventTests.swift
There was a Core Data multithreading violation introduced in https://github.com/wireapp/wire-ios-sync-engine/pull/28 in which we fetched `StoredEvents` while still on the `syncMOC`'s queue in `consumeStoredEvents:someEvents:lastIndexToFetch:consumeBlock:`.
* This PR changes the event processing to be asynchronous and dispatches all processing onto the `eventMOC`'s queue. The `consumeBlock` is called on the `syncMOC` with the decrypted update events.
* `processBatch:storedEvents:block:` now takes an additional optional completion closure which is used in the `consumeStoredEvents` method to ensure the previously processed events have been deleted when the next batch is fetched.
> Fix multithreading violation in EventDecoder

- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForEventTests+Reactions.swift
Failing tests on develop
- Use the proper emoji, as we now validate against a list of allowed emoji
Still two tests failing about canceling notifications, I want to look at them after merging https://github.com/wireapp/wire-ios-sync-engine/pull/54
> Fix like notification tests

- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationDispatcherTest.m
- Tests/Source/Synchronization/Transcoders/ZMClientMessageTranscoderTests.m
`ZMLocalNotificationDispatcherTest` failed because of a typo 
`ZMClientMessageTranscoderTests` did not return a request since it couldn't encrypt the payload because the self client wasn't created.
> Fix failing ZMClientMessageTranscoder ZMLocalNotificationDispatcher tests

- Tests/Source/Synchronization/Transcoders/ZMAssetTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMClientMessageTranscoderTests.m
Some tests where failing since they where crashing.
- the `ZMClientMessageTranscoderTests` were failing since they didn't create requests since the self client was missing.
- the `ZMAssetTranscoderTests` were crashing since we were mocking the `ZMImageMessage` class and  creating  an instance of it. This led to a crash when the instances where being deallocated. To avoid the crash we create our instance before we start mocking the class.
> Fix crashing/failing tests

- Tests/Source/Calling/ZMFlowSyncTests.m
This test was not failing consistently. I actually could only make it fail one time out of ten. But I think the reason why it is sometimes failing, is that the `AVSFlowManager ` mock is accessed from two threads at the same time. This can happen since `[AVSFlowManager appendLogForConversation:message]:` gets called from the `avsLogQueue`.
If I look at the other `ZMFlowSync` tests many of them have the same issue, so I think we can try to enable this test for now.
> Enable disabled test

- Source/Synchronization/Strategies/ImageUploadRequestStrategy.swift
Image messages were being sent even in case of missing session with remote client
Make sure that message dependencies are considered by the transcoder
Tests were already in place and failing (see `testThatItSendsFailedSessionOTRAssetMessageAfterMissingClientsAreFetchedButSessionIsNotCreated`)
> Fix image messages not depending on missing clients

- Tests/Source/UserSession/BackgroundAPNSConfirmationStatusTests.swift
The test were failing since they expected the application to be in the background state.
Change the mock UIApplication into background state during `setUp`
> Fix failing tests due to wrong test setup

- Source/Notifications/Push notifications/Helpers/ZMLocalNotificationSet.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationSetTests.swift
We were using a mock that was incompatible with the expected class in the function.
> Fix failing test

- Source/E2EE/ZMUserSession+OTR.m
Seems like we were not sending the request immediately because the save on the UIMOC might happen before the changes on the syncMOC
Fix for `[ConversationTestsOTR  testThatItDoesNotSetAllConversationsToSecureWhenDeletingATrustedSelfUserClients]`
> Notify Operationloop after preparing a client for delete

- Source/E2EE/CBCryptoBox+UpdateEvents.m
- Source/Synchronization/Decoding/EventDecoder.swift
- Source/Synchronization/ZMSyncStrategy.m
- Tests/Source/E2EE/ConversationTests+OTR.m
Fixes multiple failing tests in `ConversationTests+OTR`, which all where related to inserting a failed to decrypt system message.
There were multiple issues with the tests, the first one being that a 💣 has been inserted as (plain) text, which is normally done when the sender can not establish a session with the receiver but still needs to send the message. On the receiving side messages with this string are discarded and no system message is inserted (which is another issue that can be discussed). 
Another issue was a missing save after the system message has been inserted. If only one update event is processed and that one can not be decrypted, the system message is appended from a call made inside the `EventDecoder`, the event decoder then does not have any events to propagate to the …
> Fix failing tests in ConversationTests+OTR

- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
Users started to see the message "you haven't used this device in a while" in the random circumstances.
The above mentioned message is inserted only when `/notifications` call return 404. This means that either from backend we had an issue, or on our side we create the incorrect request.
The request has several parameters. One of them is last known to client notification ID. Thanks to help from @basine and @tiago-loureiro we figured out that the request also returns 404 if the last notification ID passed by client is not known to the backend.
We are having a concept of transient events, those are used for realtime call setup (I think). The client can receive events in two ways: with push channel or using sync via `/notifications`. Transient events are delivered via push channel, but they …
> Ignore transient events for lastEventId

- Source/UserSession/ZMUserSession.m
After the swift 3 migration this call to `isEqualToData:` crashes if we pass in nil.
We can replace the call with `isEqual:` where nil is a valid input.
> Fix crash when deviceToken is nil

- Source/Public/ZMUserSession.h
- Source/Synchronization/Strategies/ProxiedRequestStrategy.swift
- Source/UserSession/ProxiedRequestsStatus.swift
- Source/UserSession/ZMUserSession+Proxy.m
- Source/UserSession/ZMUserSession.m
- Tests/Source/Synchronization/Strategies/ProxiedRequestStrategyTests.swift
- Tests/Source/UserSession/ProxiedRequestStatusTests.swift
- Tests/Source/UserSession/UserSessionGiphyRequestStateTests.swift
For the updated giphy feature we allow searching for gifs as you type. For this this work correctly we need to be able to cancel previous searches.
- `ZMUserSession.proxiedRequestWithPath:` now returns a `ProxyRequest` object.
- added `ZMUserSession.cancelProxiedRequest:`
> Add support for canceling proxy requests

- Source/Synchronization/Decoding/EventDecoder.swift
- Source/Synchronization/NSManagedObjectContext+EventDecoder.swift
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.h
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Source/Synchronization/ZMSyncStrategy.m
- Tests/Source/Synchronization/EventDecoderTests.swift
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
- zmessaging-cocoa.xcodeproj/project.pbxproj
- zmessaging-cocoa.xcodeproj/xcshareddata/xcschemes/zmessaging-ios.xcscheme
When in background, APNS enabled, and receiving more than ~10 messages from the same user without opening the app, upon opening the app later some error messages ("failed to decrypt") will be inserted in the conversation, even if no message was missing.
This was causing by trying to decrypt the message twice (once, successfully, from APNS and once later, when coming back to foreground and fetching the notification stream). It is not expected to be able to decrypt the same message twice, but normally cryptobox will return a "duplicated message" error, which we expect and ignore. 
However, if the session with the sender had advanced the key enough times (and it does, because APNS cause a confirmation message to be sent back to the sender, which advance the session), the original key used …
> Fix failed to decrypt when receiving messages in background

- Tests/Source/MessagingTest.h
- Tests/Source/MessagingTest.m
- Tests/Source/Synchronization/Transcoders/ZMLastUpdateEventIDTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
- Tests/Source/UserSession/ZMAccountStatusTests.swift
- Tests/Source/UserSession/ZMClientRegistrationStatusTests.m
This PR fixes tests that were broke changing the way contexts are initialized.
> Fix non passing tests due to change in DataModel

- Source/Notifications/Push notifications/Notification Types/MessageNotifications/ZMLocalNotificationForSystemMessage.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForSystemMessageTests.swift
**In this PR**
In case a user leaves a conversation, we don't want to send out a notification.
> don’t create a notification for user leaving conversation

- Source/Notifications/Push notifications/Notification Types/MessageNotifications/ZMLocalNotificationForSystemMessage.swift
- Tests/Source/Data Model/ZMConversation+Testing.m
- Tests/Source/Integration/ConversationsTests.m
- Tests/Source/Integration/SendAndReceiveMessagesTests.m
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
We are removing `inactiveParticipants` from data model.
Remove all reference to inactive participants and delete related tests
> Remove references to inactive participants

- Source/Notifications/Push notifications/Notification Types/MessageNotifications/ZMLocalNotificationForSystemMessage.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForSystemMessageTests.swift
We were using the wrong property (removedUsers / addedUsers instead of users) on ZMSystemMessage to create the push notification.
> Use correct user collection for member join / leave notifications

- Resources/da.lproj/Push.strings
- Resources/de.lproj/Push.strings
- Resources/es.lproj/Push.strings
- Resources/fr.lproj/Push.strings
- Resources/it.lproj/Push.strings
- Resources/ja.lproj/Push.strings
- Resources/nl.lproj/Push.strings
- Resources/pt-BR.lproj/Push.strings
- Resources/ru.lproj/Push.strings
- Resources/tr.lproj/Push.strings
- Resources/uk.lproj/Push.strings
- Resources/zh-Hans.lproj/Push.strings
- Added translation (or English placeholders) for CallKit strings
> Adding translations for CallKit strings

- Source/Calling/ZMCallKitDelegate.h
The `callKitHandle` was marked non-optional in header file, whereas implementation actually generated nil.
> Fixed nullability warning in CallKit

- Source/Calling/ZMCallKitDelegate.m
When we used to leave the call, CallKit code additionally called `-[voiceChannel ignoreIncomingCall]` that made the next call ignored. Now we can check if ignoring call is necessary.
> Do not ignore call when leaving

- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
Managed object context observer in CallKit used to observe also the conversations that are just created locally, those don't have the remoteIdentifier yet.
> Do not crash when creating the group conversation

- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
Calls in silenced conversations should not be displayed as a CallKit calls.
> Ignore calls in silenced conversations (CallKit)

- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
1. Call used to continue to ring indefinitely
2. If the call is picked up on the other device, CallKit used to continue ringing
Correctly observe the call state transient properties and respect additional call states.
> Respect call timeout; Hide the call that is picked up remotely

- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
We used to offer the calling with Wire from address book using any phone or email.
Exclude phone and email handle types from supported list.
The plan is to add back the handles and offer SiriKit handling, so iOS can check with Wire which number it can dial. Alternatively, we can offer sending invites to users not on wire who current user would like to call.
> Do not offer phone and email calling with CallKit

- Source/Calling/ZMCallKitDelegate.m
In the CallKit mode, the video call incoming must not send video until the app is in the foreground. When app comes to the foreground, `ZMCallKitDelegate` gets the notification in `-[ZMCallKitDelegate applicationDidBecomeActive]` and looks for current active call to check if it is video call.
The bug happened to be with `-[ZMCallKitDelegate nonIdleCallConversations]` method that was looking into `conversationsInUserSession` list for current active call, however this array explicitly excludes the current call.
Use another array that contains all conversations: `conversationsIncludingArchivedInUserSession`.
> Fix for video call not sending video

- Source/Calling/ZMCallKitDelegate.h
- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
Sometimes on CallKit version of the app, the call in one conversation is not possible to establish any more. Moreover, it is not possible to do so even after the app is restarted.
I found that in that case CallKit thinks that there is a not ended call going on in this conversation, and CallKit is rejecting to start another call there because "maximum amount of call groups is reached" (right now set to 1 in the app since we don't support the call grouping).
It comes out that we where not using the API to report broken calls `-reportCallWithUUID:endedAtDate:reason:`. 
Also to be sure I added the code to end all ongoing CallKit calls on the startup, to make sure that the app is not blocked from calling after the restart.
> Correctly report end of the call; end all calls on startup

- Source/Synchronization/ZMSyncStrategy.m
- Tests/Source/Integration/FileTransferTests.m
* This adds the required strategies added in https://github.com/wireapp/wire-ios-message-strategy/pull/19 to the strategies array.
* Add integration tests for asset sending using the `/assets/v3` endpoint.
> Add support to send assets using /assets/v3

- Source/Calling/ZMCallKitDelegate.m
Sometimes AVS cannot start recording because of the mismatch in audio session configuration. Potentially issue can happen because AVS works asynchronously, and the audio session is configured after `-join` call.
> Configure AudioSession before call join

- Source/Calling/ZMCallKitDelegate.m
Sometimes calls gets stuck in connecting when answering via Callkit on the lock screen. According to this thread on the apple forums it could be a race condition and they propose this change as a workaround.
https://forums.developer.apple.com/thread/60336
ticket: https://wearezeta.atlassian.net/browse/ZIOS-7624
> Move configureAudioSession to reportNewIncomingCallWithUUID when receiving a call

- Source/UserSession/UserProfileUpdateNotifications.swift
The `UserProfileUpdateObserver` protocol contains a couple of methods relevant for updating emails, phone numbers and @names, however most of the conforming types do not handle all of these cases which leads to a lot of empty implementations just to conform to this protocol. This is why the methods of the protocol are now marked as `optional` (and `@objc` unfortunately as there are no optional conformances in Swift yet).
> Mark the user profile update observer methods as optional.

- Cartfile.private
- Cartfile.resolved
- Source/Synchronization/Strategies/UserProfileUpdateRequestStrategy.swift
- Tests/Source/Synchronization/Transcoders/UserProfileUpdateRequestStrategyTests.swift
- Tests/Source/UserSession/Search/ZMSearchUserTests.m
* The `Location` header will not be set in the response we receive when checking handle availability. We thus need to determine the handle we checked the availability of using the url of the response's underlying `HTTPURLResponse`.
* Another way would have been to add a completion handler to the request and capture the handle, but this would clutter the `UserProfileUpdateRequestStrategy` and how the response parsing is done for the other update requests.
> Determine handle from the original request's url instead of the header

- Source/Registration/RandomHandleGenerator.swift
- Tests/Source/Registration/RandomHandleGeneratorTests.swift
Autogenerated handles could go above the 21 characters limit when appending digits at the end. They should stay within the 21 characters limit.
> Fix truncate handle length before adding number

- Source/Synchronization/Strategies/UserProfileUpdateRequestStrategy.swift
- Tests/Source/Synchronization/Transcoders/UserProfileUpdateRequestStrategyTests.swift
When bulk checking handle availabilities we were only acknowledging a 200 response as potentially available (parsing the response to check for which handles we did not receive a payload).
As the used endpoint is not a specific search endpoint but the usual endpoint to get user profiles we also need handle a 404 where all handles are available.
If none of the handles belongs to an existing user the endpoint returns a 404 NOT FOUND and we now use the first suggested handle.
> Return first suggested handle when receiving 404 checking available handles

- Source/UserSession/ZMUserSession.m
- Tests/Source/MessagingTest.m
It was a sunny beautiful day, the chilly second one of Berlin winter. @mikeger was rushing to the office: he was thinking about by the fresh and soft croissant that was waiting for him.
As he walked up the stairs, he noticed that something is not quite right that day. Everyone seemed to be worried; no one was enjoying the croissants and looked onto the screens of their mobile phones; it was perfectly clear that something happened.
-- Look! I also got that message! Did someone replaced your key information. I see the message "Identity changed" in your conversation!
Could that really be that someone was trying to break Wire's encryption for everyone in the office? No, there is no time for croissants now, we need to solve that mystery immediately!
It comes out that we merged the changes that …
> The Missing OTR Folder Mystery

- Source/Calling/ZMCallKitDelegate.m
We used to include user email and phone in Calling/CallKit log.
> Removed phone/email from callkit log

- Source/UserSession/Search/Internal/ZMSearchRequestCodec.m
- Tests/Source/UserSession/Search/ZMSearchRequestCodecTests.m
This will allow us to search by username on the backend, where usernames have no @
> Strip initial @-symbol from the search query

- Source/UserSession/Search/TopConversationsDirectory.swift
* We tried to set a `URL` instance as value in the persistent store metadata which not a valid plist type.
> Set absolute string instead of non plist url in persistent store metadata

- Source/Synchronization/Strategies/AddressBookUploadRequestStrategy.swift
- Tests/Source/Synchronization/Strategies/AddressBookUploadRequestStrategyTest.swift
It an address book entry matches a result from the backend, we store the match only if we have a local user, otherwise we lose the information that this was a match.
We create a local user every time there is a match, if such user did not exists
> Create a user when receiving an AB match

- Source/Registration/AddressBook.swift
- Source/Registration/AddressBookIOS8.swift
- Source/Registration/AddressBookIOS9.swift
When searching with an empty query in the AB, we would get an empty result. We should have gotten the entire AB.
Returns a part of the AB (max 2000 contacts)
We don't yet have a system in place to test address book searches
> Fetch *some* contacts when searching the AB for an empty query

- Source/Registration/AddressBook.swift
The AB iteration was aborting in case of invalid entry (no valid email or password). It should continue to the next contact instead.
> Do not abort AB processing on invalid entry

- Source/UserSession/Search/Internal/ZMSearch.m
- Tests/Source/UserSession/Search/ZMSearchDirectoryTests.m
When filtering out conversation from a search result when the query was a username search (with starting with `@`), conversations that have `@` in the name should still be included
> Do not filtering out conversation with @ in name

- Source/Registration/RandomHandleGenerator.swift
- Tests/Source/Registration/RandomHandleGeneratorTests.swift
Handle was limited at 3 characters, but 2 characters are valid handles
> Change minimum amount of characters in handle to 2

- Tests/Source/Integration/FileTransferTests.m
- Tests/Source/MessagingTest.m
* The location of the caches was changed to be in the shared container, in our unit tests they are still located in the caches directory and only this one is cleared in `tearDown`. As the test host has the shared container entitlement the caches in integration tests are created in the shared container, but were never deleted in the `tearDown`.
> Fix failing file transfer tests after changes in cache location

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
- Tests/Source/Synchronization/ZMHotFixTests.m
* Users updating from a non-username version might have missed the updates from users that previously set a username, which is why we now refetch all connected users in a hotfix.
* A refetch of unconnected users should already be initiated by the UI with a call to `refreshData`.
> Add hotfix marking all connected users to be updated from the backend

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
- Tests/Source/Synchronization/ZMHotFixTests.m
* The previous hot fix missed the case in which the secondary client receives and discards the update event when setting the username on the primary one. As we are not refetching the self user by default we need to mark it to be fetched.
> Mark self user as needing update from the backend in username hotfix

- Source/Synchronization/ZMHotFix+PendingChanges.swift
- Tests/Source/Synchronization/ZMHotFix+PendingChangesTests.swift
- Tests/Source/Synchronization/ZMHotFixTests.m
* As mentioned in https://github.com/wireapp/wire-ios/pull/482 this hides the underlying conditions that might cause a hot fix to be pending from the UI.
> Abstract pending hot fix changes into variable on user session

- Source/Calling/ZMCallKitDelegate.m
As of AVS 2.9.18 we have added a new function `setupAudioDevice` to `AVSMediaManager` that allows us to enter call state early, that appears to fix ZIOS-7624. I have tested 50 calls on an iPhone 6 and not seen the issue, but due to the nature of the bug more extensive testing by QA and affected users would be nice. This PR is a simple change to use the function.
> Fix for occasional failure to connect audio with CallKit (ZIOS-7624)

- Source/Data Model/ZMUser+UserSession.m
Replace immediate save with a delayed save when requesting a
profile image, because it can result in a nested save if the
requesting is done as a result of a save.
https://wearezeta.atlassian.net/browse/ZIOS-7846
> Fix double save on requesting profile image

- Source/Calling/ZMCallKitDelegate.m
As requested by AVS we need to call `resetAudioDevice` when a Callkit call is over in order to restore the audio session. This should fix a bug where a ringtone would not play for the second call.
https://wearezeta.atlassian.net/browse/ZIOS-7823
> Reset audio device when ending a callkit call

- Source/Calling/VoiceChanneRouter+CallFlow.swift
- Source/Calling/WireCallCenter.swift
- Source/Calling/WireCallCenterV2.swift
- Source/Calling/WireCallCenterV3.swift
Both V2 & V3 call centers now implement the `ReceivedVideoObserver` protocol. This simplifies the UI code since will now only need to hook up one observer.
> Unify V2 & V3 receiving video observering

- Source/UserSession/ZMUserSession+Background.m
While executing on the SE context, `managedObjectContext.zm_userInterfaceContext` is called.
This is threading violation since we are accessing the `userInfo` property of the UI context
from the SE context.
If we want run on UI context we can just do a `performGroupedBlock` directly on `mangedObjectContext`
> Fix threading violation

- Source/UserSession/ZMUserSession+Background.m
There were some more cases similar to https://github.com/wireapp/wire-ios-sync-engine/pull/210
In the user session it can never be correct to call `self.managedObjectContext.zm_userInterfaceContext`
<b>When running on SE context:</b>
threading violation
<b>When running UI context:</b>
doesn't fail but is also equivalent to `self.managedObjectContext`
> Fix thread violation

- Source/Analytics/AnalyticsType.swift
* Remove `upload` method requirement from the `AnalyticsType` protocol (see https://github.com/wireapp/wire-ios/pull/614).
> Remove upload method from AnalyticsType protocol

- Source/Calling/VoiceChannelRouter.swift
- Source/Calling/WireCallCenter.swift
- Source/Calling/WireCallCenterV3.swift
- Source/Notifications/Push notifications/Notification Types/EventNotifications/ZMLocalNotificationForEvent.swift
- Source/Public/CallingProtocol.h
- Source/Public/ZMUserSession.h
- Source/Public/zmessaging.h
- Source/UserSession/CallStateObserver.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/VoiceChannelRouterTests.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
- zmessaging-cocoa.xcodeproj/project.pbxproj
The `callingV3Enabled` flag on user session has been replaced with `callingProtocol`
which can be set to `negotiate`, `version2` and `version3`. If it's set to `negotiate`,
which is the default, the calling protocol to use is decided by checking a flag
on the BE.
> Add support for BE calling protocol flag

- Source/Data Model/NSManagedObjectContext+ServerTimeDelta.swift
- Source/Synchronization/Strategies/CallingRequestStrategy.swift
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
- zmessaging-cocoa.xcodeproj/project.pbxproj
To handle the case when client's clock has the wrong time a `time` field has been added to the notifications stream response. This time is used to calculate a delta between the client and server time, which is used to correct the current time when passing calling messages to AVS.
> Read server time delta from notification stream response

- Source/Calling/VoiceChannelRouter.swift
- Source/Calling/WireCallCenter.swift
- Source/Calling/WireCallCenterV3.swift
- Source/Public/CallingProtocolStrategy.h
- Source/Public/ZMUserSession.h
- Source/Public/zmessaging.h
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/VoiceChannelRouterTests.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- zmessaging-cocoa.xcodeproj/project.pbxproj
We need distinguish between calling version 2/3 in our tracking.
this PR adds a `callingProtocol` to some of the call observers methods. The name of calling protocol enums where not good so I've renamed them.
`CallingProtocol` > `CallingProtocolStrategy`
`CallingProtocolVersion` >  `CallingProtocol`
> Expose calling protocol in observers for tracking purposes

- Source/Synchronization/Strategies/UserProfileUpdateRequestStrategy.swift
- Source/UserSession/UserProfile.swift
- Source/UserSession/UserProfileUpdateStatus.swift
- Tests/Source/Synchronization/Transcoders/UserProfileUpdateRequestStrategyTests.swift
- Tests/Source/UserSession/UserProfileUpdateStatusTests.swift
We had possibility to set the email, but not to change it afterwards, so added a new method for this. 
Also fixed a threading issue which means `requestSettingEmailAndPassword` method returns an `emailAlreadySet` error in the delegate instead of throwing.
> Add possibility to change email

- Source/Calling/ZMCallTimer.swift
- Source/Calling/ZMVoiceChannel+CallTimer.swift
* Add missing `performGroupedBlock` in `ZMCallTimer`.
* We were checking `isZombieObject` in `ZMVoiceChannel+CallTimer` before dispatching to the correct queue.
> Fix multithreading violation in ZMCallTimer

- Source/Synchronization/Sync States/ZMSyncStateMachine.m
* The authentication notification is fired on the main queue and we did not dispatch to the sync queue.
> Fix multithreading violation in ZMSyncStateMachine

- Source/Calling/ZMCallKitDelegate+Internal.h
- Source/Calling/ZMCallKitDelegate+WireCallCenter.swift
- Source/Calling/ZMCallKitDelegate.h
- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
Outgoing Callkit calls where displayed with the e-mail of the self user. Also fixed and added callkit tests for v3.
> Fix outgoing callkit calls displaying the wrong callie

- Source/UserSession/ZMUserSession.m
As discussed before, it was decided to increase the image cache to allow collections content to be stored on the device without re-downloading.
> Increase imageAssetCache size to 500 MB

- Source/Calling/VoiceChannelV2+CallFlow.m
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallStateObserverTests.swift
For calling 2 we keep the websocket open during a call. This PR adds the
same logic for calling 3.
> Keep websocket open during a call

- Source/Calling/ZMCallKitDelegate.m
We should not leave the voice channel immediately when we request to leave
> Fix group calls not hanging up properly

- Source/Synchronization/Strategies/UserProfileUpdateRequestStrategy.swift
- Source/UserSession/UserProfileUpdateStatus.swift
- Tests/Source/Synchronization/Transcoders/UserProfileUpdateRequestStrategyTests.swift
Initially it was used only for adding phone initially, not for changing it afterwards
> Enable changing phone number after it was added to the profile

- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
We detected the crash issue happening in `pingbackStatus`'es `didReceiveEncryptedEvents:originalEvents:...` when referencing `originalEvents`. Current hypothesis is that for the parameter `originalEvents` the nil value is passed from Obj-C caller in `ZMMissingUpdateEventsTranscoder`. This situation is theoretically possible (there is no concrete steps to reproduce).
There is no reason to call `didReceiveEncryptedEvents:originalEvents:...` if `originalEvents` is nil, therefore the call is guarded by if on the caller side.
> Do not notify pingback status if notificationEventsToCancel is nil

- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
- Tests/Source/E2EE/UserClientRequestStrategyTests.swift
On some devices we observed a list of "ghost users" that were previously deleted, but that are still in the list of clients for the self user.
We now make sure to remove any client (other than self) that we don't see in the list of clients received from the BE
> Remove "ghost clients" when fetching the clients list

- Source/Calling/WireCallCenter.swift
- Source/Calling/WireCallCenterV3.swift
- Source/Calling/ZMCallKitDelegate+WireCallCenter.swift
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
Previously AVS was only reporting state changes for actions you
didn't initiate, that's no longer the case so we need to remove
our own state change reporting to avoid duplicate state changes.
> Update state handling due to API change

- Source/Calling/WireCallCenterV2.swift
We didn't start the video due to a missing save call.
> Fix missing video when answering a call from the lock screen

- Source/Notifications/Push notifications/ZMLocalNotificationDispatcher+Calling.swift
When:
- disabling callKit
- enabling calling v3
- receiving a call shortly after placing a call in the same convo
the notification would show the wrong caller, because we would reuse the old (outbound) notification because it was for the same conversation, even if the caller was not the same.
This makes sure we don't reuse it if it's not the same caller.
> Wrong caller in notification

- Source/Calling/ZMFlowSync.m
- Tests/Source/Calling/ZMFlowSyncTests.m
Calling 3 which is initialized with `wcall_init` requires the flow manager to already be started. Since `wcall_init` is currently not called on demand it also makes no sense to have the flow manager started to on demand.
> Always initialize the flow manager for now

- Source/Notifications/Push notifications/Notification Types/ZMLocalNotificationForCallState.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForCallEventTests.swift
When a call is over it transitions to the `.terminating(reason: CallClosedReason)` state. We only want to show a notification about missed calls if the user didn't answer the call. An answered call closes with the `.normal` reason which we should ignore.
https://wearezeta.atlassian.net/browse/ZIOS-7999
> Fix missed call notifications appearing after answering a call

- Resources/Base.lproj/Push.strings
- Source/Notifications/Push notifications/Notification Types/MessageNotifications/ZMLocalNotificationContentType.swift
- Source/Notifications/Push notifications/Notification Types/MessageNotifications/ZMLocalNotificationForMessage.swift
- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification.h
- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification.m
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForMessageTests.swift
If in the future we add new message types we want users with old clients to be informed that they are receiving message that they can't read. This PR will notify the user of such messages with a local notification.
> Show push notification when receiving an unknown message

- Cartfile
- Cartfile.resolved
- Source/Calling/VoiceChannelV3.swift
- Source/Calling/WireCallCenterV3.swift
AVS 3.2 has some minor API changes:
- `answeredh` handler has been added. (no need to register for separate state handler) 
- `wcall_reject` has been added which should called when you ignore calls
- `WCALL_STATE_TERMINATING ` has been split into `WCALL_STATE_TERM_LOCAL` and `WCALL_STATE_TERM_REMOTE ` but we don't care atm since we check the `userId`
> Update for API changes in AVS 3.2

- Source/Calling/WireCallCenterV2.swift
If we receive two set change updates at the same time enqueing
them on the context will defer them and make them out of date.
> Fix incorrect SetChangeInfo for voice participants

- Source/Calling/WireCallCenterV2.swift
- Source/Synchronization/ZMSyncStrategy.m
- Tests/Source/Calling/WireCallCenterV2Tests.swift
We need to do observing when in the background for calls which the new observer system doesn't support. Since v2 calling will be removed eventually it's easier to revert to direct observing of core data than to add support for background observing.
> Revert to use direct core data observing for call center

- Source/Calling/VoiceChannelV2.h
- Source/Calling/WireCallCenter.swift
- Source/Calling/WireCallCenterV3.swift
We want to track how often user run into the io errors during
call setup so AVS added an additional close reason for this.
> Add mapping for IO error from AVS

- Source/Calling/WireCallCenterV3.swift
AVS updated their API in 3.2.X with a new `answerh`callback which only fires when the remote participant answers the call. So when we accept an incoming call we must notify manually.
> Need manually notify about answered calls again

- Source/Calling/ZMCallKitDelegate.m
We were reset:ing the audio session on performing the end call action. This is
a problem when you are already in a call and receives a 2nd call. Declining that
second call would interrupt audio session and leave you muted for the rest of call.
A better for for reset:ing the audio session is in the `didDeactivateAudioSession`
which is called after a call is over
> Fix interrupting audio session when receiving a 2nd call

- Source/Synchronization/ZMCallStateTranscoder.m
We were previously ignoring calls in newly created groups because they would
show up during sync. But now the CallState transcoder is only listening to live
events so this should not be necessary anymore.
see line: https://github.com/wireapp/wire-ios-sync-engine/blob/226997e1f3db0d2d04f0d01e2946d2bb1d9dc357/Source/Synchronization/ZMCallStateTranscoder.m#L247
https://wearezeta.atlassian.net/browse/ZIOS-5969
> Don't ignore calls in newly created groups

- Source/UserSession/Search/TopConversationsDirectory.swift
- Tests/Source/UserSession/TopConversationsDirectoryTests.swift
What's in this PR?
* We do not want to show conversations without any messages in the top conversations directory.
> Don't include conversations without messages in the last month in the top people directory

- Source/UserSession/Search/TopConversationsDirectory.swift
- Tests/Source/UserSession/TopConversationsDirectoryTests.swift
* System messages were taking into account in the top people calculation.
* Fetch `ZMAssetClientMessage` and `ZMClientMessage` count instead of `ZMMessage`.
* This will add an extra request per conversation, we will have to see if this performs well and otherwise might want to reverse iterate over the messages in a conversation until the `serverTimestamp` is older than a month.
* Add missing test assertion.
> Only consider client and asset messages in top people calculation

- Source/Calling/ZMCallKitDelegate.m
- Crash happens when we are trying to initialize `CXStartCallAction` with nil handle.
- Handle is nil when conversation is nil, or conversation is of an unknown type, or it does not have a remote identifier yet. In all those cases there seems to be no reason to start the call.
> CallKit crash fixed when there is no handle

- Source/Calling/VoiceChannelV2+CallFlow.m
- Calling does not make sense if there is no remote identifier.
- Issue can happen for just created locally conversations.
- This case is already handled in calling V3 (YAY)
> Check if conversation has remoteIdentifier before calling

- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
We need to revert the answer call handling until we have more time investigate why the "correct" api usage breaks incoming calls.
> Revert answer call handling

- Source/Calling/VoiceChannelV2+CallFlow.m
- Source/Calling/VoiceChannelV2.h
- Source/Calling/VoiceChannelV3.swift
- Source/Synchronization/Transcoders/ZMCallStateLogger.m
- Tests/Source/Calling/VoiceChannelV2Tests.m
- Tests/Source/Calling/VoiceChannelV3Tests.swift
- Tests/Source/Calling/ZMCallStateTests+VideoCalling.swift
- Tests/Source/Calling/ZMGSMCallHandlerTest.m
- Tests/Source/Synchronization/Transcoders/ZMCallStateTranscoderTests.m
We need degraded variant for the connecting state. This is handles the case when you find out the call is degraded after you've accepted the call.
> Add degraded variant for connecting state

- Source/Calling/WireCallCenterV2.swift
- Tests/Source/Integration/CallingTests.m
* This is needed in order to properly update the conversation list indicator on the UI.
> Manually fire a notification for the list indicator when the call state changes

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
- Tests/Source/Synchronization/ZMHotFixTests.m
* We need to refetch all connected users as they might alreday have uploaded profile pictures using the `/assets/v3` endpoint which we do not yet have locally and couldn't download before we updated to the latest version (The update event has already been processed so the client won't know about the new picture). The `selfUser` might have uploaded a picture using the new endpoint form a different client as well in the meantime and we need to re-download it. This might lead to a race condition, e.g. we want to migrate the profile picture from the old endpoint to the new one if the user does not yet have a v3 asset, but we need to ensure that we re-download the `selfUser` first, otherwise we might redundantly re-upload a picture that was already uploaded from a different client, or, worse …
> Mark connected users to be re-downloaded in HotFix

- Source/Synchronization/Transcoders/ZMSelfTranscoder.m
- Source/UserSession/UserProfileImageUpdateStatus.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Synchronization/Transcoders/ZMSelfTranscoderTests.m
- Tests/Source/UserSession/UserProfileImageUpdateStatusTests.swift
* Updated SelfTranscoder to pick up changes for profile picture assets
* Removed some states from the `UserProfileImageUpdateStatus` that are not relevant anymore because it is handled by SelfTranscoder
* Made sure we run on sync thread and sprinkled tests with `waitForAllGroupsToBeEmpty`
> Profile picture v3: Updating profile

- Source/Calling/ZMFlowSync.m
- Tests/Source/Calling/ZMFlowSyncTests.m
When we receive a call after having killed the app we didn't display incoming
call notification because AVS wasn't ready to process calling messages. The
reason for this is that we weren't sending the calls/config request which AVS
needs to complete before it can do anything.
This PR allows this request to be made at all times. Previously it wasn't
made since the push channel wasn't open.
https://wearezeta.atlassian.net/browse/ZIOS-8282
> Fix call APNS after app is killed

- Source/Calling/SystemMessageCallObserver.swift
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallStateObserverTests.swift
This PR contains two changes
1. We didn't insert a call system message when you canceled an outgoing call
2. The rules for when to insert a missed call vs. performed call has changed.
The rules are now the following
missed call system message: only inserted for unanswered incoming calls
performed call system message: inserted for all outgoing calls and for connected incoming calls.
https://wearezeta.atlassian.net/browse/ZIOS-8313
> Update call system message logic

- Source/UserSession/UserProfileImageUpdateStatus.swift
- Tests/Source/UserSession/UserProfileImageUpdateStatusTests.swift
Unify the API to change a profile picture. The UI is supposed to call
```swift 
UserProfileImageUpdateStatus.updateImage(imageData: newProfileImageData)
```
in order to upload a new profile image, using this API ensures we update the user profile with v3 and the deprecated method which does not use `/assets/v3`.
> Unify API to set a profile picture

- Source/Synchronization/ZMSyncStrategy.m
- Source/UserSession/UserProfileImageUpdateStatus.swift
- Tests/Source/UserSession/UserProfileImageUpdateStatusTests.swift
* Add function to re-upload existing user images without preprocessing them again.
* `UserProfileImageUpdateStatus` is a `ZMContextChangeTracker` now and will check if it needs to re-upload the image to v3 if the self user changes, does not need to be updated from the backend and if there are  no medium and small image data as well as no asset v3 identifiers in the database yet.
* This functionality is still missing integration tests (which in turn require `wire-ios-mocktransport` to handle the v3 upload).
> Re-upload existing image when user does not have v3 image yet

- Source/Public/zmessaging.h
- Source/UserSession/ZMUserSession+Background.m
- Source/UserSession/ZMUserSession+Internal.h
- Source/UserSession/ZMUserSession+MessageLikeAction.swift
- Source/UserSession/ZMUserSession+OperationLoop.h
- Source/UserSession/ZMUserSession.m
- zmessaging-cocoa.xcodeproj/project.pbxproj
* We did not return after the call to kick off the like action, which could result in the completion handler being called too early.
* More importantly we did not start a proper background task on the `ZMOperationLoop`.
* Shuffled around some properties and include some files in the public header to expose the operation loop and relevant methods to Swift.
> Fix liking a message from a push notification

- Source/UserSession/ZMUserSession+Background.m
* Revert changing the logic checking which action to perform as all tests checking if the completion handler is invoked where failing.
* I heavily assume that the test failures are actually just a side effect of the completion handler always being called at the end of this function, which might not be the desired behaviour, but will debug and change this after the current release.
> Revert changing action handling logic

- Tests/Source/Data Model/ZMUser+Testing.m
- Tests/Source/Integration/SlowSyncTests.m
Mock transport returns phone and email only for self user. Few methods that check users would fail as it would compare the current data with the response and see that values are missing.
> Fixing test failures after mock transport update

- Source/UserSession/Search/Internal/ZMSearch.m
- Source/UserSession/Search/Internal/ZMSearchRequestCodec.h
- Source/UserSession/Search/Internal/ZMSearchRequestCodec.m
- Tests/Source/UserSession/Search/ZMSearchDirectoryTests.m
- Tests/Source/UserSession/Search/ZMSearchRequestCodecTests.m
* Remove levels url parameter.
* Reduce requested search result size to 10.
> Remove levels parameter from search, reduce search result size to 10

- Source/Calling/AVSWrapper.swift
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallStateObserverTests.swift
* Fixes comparing the return value of some `wcall` C function to to the wrong value, from the documentation: 
>  Returns 0 if successful
* Do not append additional performed call system message for terminating v3 calls. A `ZMSystemMessage` of type `.missedCalll` is already appended by the SystemMessageCallObserver when the call is terminated (or times out).
> Fix checking the wrong return value 

- Source/Calling/ZMCallKitDelegate.m
* See https://github.com/wireapp/wire-ios/pull/825.
* This flag should be set to `YES` when CallKit is enabled, then AVS won't start the audio before the audio session is active.
> Set setUiStartsAudio when CallKit is enabled

- Source/Notifications/Push notifications/Helpers/SessionTracker.swift
- Tests/Source/Notifications/PushNotifications/SessionTrackerTest.swift
For Swift classes `NSKeyedArchiver` encodes class names with format `moduleName.className`. In an unfortunate case that it can't find this class it throws an (ObjC) exception. 
We recently renamed the project to `WireSyncEngine` and this causes problems if we have saved sessions on disk.
In addition there was a bug in `SessionTracker` (mistyped key ` "iniatorID"` instead of ` "initiatorID"`) that prevented any sessions to be read from disk altogether.
> Fix: crash when unarchiving objects saved before framework rename

- Source/UserSession/BackgroundAPNSPingBackStatus.swift
- Tests/Source/UserSession/BackgroundAPNSPingBackStatusTests.swift
Adding a observer without retaining the token was causing a deadlock.
> Fix tests hanging due to a observer deadlock

- Source/Synchronization/Strategies/TypingStrategy.swift
- Tests/Source/Synchronization/Strategies/TypingStrategyTests.swift
* When debugging the flaky `TypingStrategyTests` I noticed that the amount of `TypingStrategies` being alive is the same as the amount of tests that have previously run.
* When running the whole test suite there are a lot of tests running before the `TypingStrategyTests`, which means there could be hundreds of leaked `TypingStrategy`s, as the `isTyping` request generation is time sensitive this could be the root cause of the flakiness (e.g. when the huge amount of leaked strategies receive the notification first then the actual sut in the tests might get it too late).
* The `TypingStrategy` was never torn down in tests. The problem was that we were using the `NotificationCenter` block API to add observers, but were not holding on to the observer tokens and deregistering them in …
> Fix leaks in TypingStrategy

- Source/Calling/WireCallCenterV2.swift
- Tests/Source/Calling/WireCallCenterV2Tests.swift
- Tests/Source/Integration/CallingTests.m
The bug happens in this scenario:
1) User is in a call
2) User ends the call (callDeviceIsActive is set to false)
3) At the same time there is another change in the conversation on the ui, e.g unreadCount / lastReadTimestamp causing a NSManagedObjectsDidChange notification to be fired
4) The stateSnapshot updates due to the notification, but does not notify the NotificationDispatcher (that's the bug)
5) The callState is merged. If the state in the stateSnapshot changes, the NotificationDispatcher notifies about the conversationList. Since the stateSnapshot has already been updated, we do not notify the dispatcher here
Step 4) is now also notifying the dispatcher
> always notify conversationList updated voiceChannelState

- Source/Calling/AVSWrapper.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
When a user is called while his device is offline and the app is killed, they will currently not receive a system message for the missed call once the app restarts. The reason is that we are forwarding the call events from the notification stream to AVS before the readyHandler is called. 
Fix: We are now buffering call events until the readyHandler is called.
> buffer call events until avs is ready

- Source/UserSession/Search/Internal/ZMSearch.m
- Tests/Source/UserSession/Search/ZMSearchDirectoryTests.m
- The bug is introduced due to the recent changes on the backend.
- We can safely assume that we can search locally for the connections.
> Always include local seach for connected users

- Cartfile
- Cartfile.resolved
- Source/Calling/WireCallCenter.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
- Tests/Source/Integration/CallingV3Tests.swift
AVS added a new callEndReason which we can use to decide whether or not a call has been left or actually ended.
> use new AVS version

- Source/Calling/ZMCallFlowRequestStrategy.m
- Source/UserSession/OperationStatus.swift
- Source/UserSession/SyncStatus.swift
- Tests/Source/Calling/ZMCallFlowRequestStrategyTests.m
Also added some debug logs to the `OperationStatus` and `SyncStatus`.
> Fix for call config not being fetched in the background

- Source/Calling/ZMCallKitDelegate+WireCallCenter.swift
- Source/Calling/ZMCallKitDelegate.m
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
**Motivation for this PR**
Incoming calls in muted conversations are not supposed to activate CallKit nor show the internal call UI.
**Also included in this PR:** 
If you are trying to answer a call with callKit and the the callController does not have a call for the conversation yet, the answer would fail with UnknownCallUUID error. 
Solution: When we receive this error we request starting a new call.
Likewise if we try to create a new call, but the callUUID already exists, it currently fails with callUUIDAlreadyExists error code. 
Solution: When we receive this error we request answering the existing call.
> do not report calls to callKit in silenced conversations

- Cartfile
- Cartfile.resolved
- Source/Calling/WireCallCenter.swift
- Source/Calling/WireCallCenterV3+Notifications.swift
- Source/Calling/WireCallCenterV3.swift
- Source/Calling/ZMCallKitDelegate+WireCallCenter.swift
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
- Tests/Source/Integration/CallingV3Tests.swift
To move incoming calls up in the conversation list (e.g. when the call is muted and there is no call overlay), we need to update the lastModifiedDate for the conversation using the message timeStamp of the incoming call.
Note: ideally we should also use the message timestamp for the closed call to insert a missed call message (we are currently using the local time). An API change for AVS is requested.
> Set lastModifiedDate for incoming call

- Source/Analytics/RequestLoopAnalyticsTracker.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Utility/RequestLoopAnalyticsTrackerTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
* Sanitise request paths for loop tracking (replace UUIDs and client IDs with `"{id}"`).
* Add tests for `RequestLoopAnalyticsTracker`.
> Sanitise request paths for loop tracking, add tests

- Source/Analytics/RequestLoopAnalyticsTracker.swift
- Tests/Source/Utility/RequestLoopAnalyticsTrackerTests.swift
* Fix `conversations/{id}/typing` exclusion.
> Fix /typing exclusion

- Tests/Source/Integration/CallingV3Tests.swift
- Tests/Source/Integration/IntegrationTestBase.m
- Tests/Source/MessagingTest.m
Been bothering us for some time. The date passed to AVS gets truncated to integers which can lead to problems if we compare last modified date to current date.
> Fixing flaky calling test

- Source/UserSession/ZMUserSession+Background.m
Previously when acting on an APNS, the app would be launched, we would perform a quicksync and only then perform the action (e.g. accepting an incoming call). The reason for this is that the notifications might be outdated and the incoming call might have already ended. By performing the sync before the action, we would have the actual state of the call and would not for example accidentally call back in an already ended call.
Due to changes in the handling of call APNS, we are now already performing a sync when receiving a call APNS. When the app launches due to an action on an APNS (swipe or tap) it would wait forever for the sync to be complete and therefore not perform the actions (until the next quicksync).
We are now checking if the sync is already done and if the pushChannel is …
> process actions directly if sync done & pushChannel is open

- Source/Calling/WireCallCenterV3+Notifications.swift
- Tests/Source/Calling/VoiceChannelParticipantV3SnapshotTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
When a user joins a group call from two devices, AVS will return two `CallMember` structs with the same userId (but possibly with different audioEstablished flag). We don't expect that and crash. 
We are now filtering the duplicate members and keep the one with the highest connection state (e.g. the one with audioEstablished true). 
It needs to be discussed whether we will need to handle multiple CallMembers for the same user in the future. In that case we need to get the clientID from AVS in order to be able to distinguish the members.
> filter out duplicate call member, keep highest connection state

- Source/Notifications/Push notifications/Notification Types/ZMLocalNotificationForCallState.swift
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherCallingTests.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForCallEventTests.swift
When a user has two clients (A and B) and calls from A, we currently create an APNS on B about an incoming call. AVS has the flag shouldRing set to false in this case. 
We should therefore not create an APNS when the flag shouldRing is false.
> Do not create APNS when shouldRing is false for incoming call

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
* While the payload when getting a team conversation does not include an object containing the `managed` we still need to include it when creating a team conversation.
> Fix conversation creation payload

- Source/Synchronization/Transcoders/TeamSyncRequestStrategy.swift
- Tests/Source/Integration/TeamTests.swift
- Tests/Source/Synchronization/Transcoders/TeamSyncRequestStrategyTests.swift
It can happen that a user is offline for longer than 4 weeks, in this case said user will miss events and we will perform a slow sync. In the case the user got removed from a team that the user already has locally in that period, we want to ensure that we delete that team from the client.
The `/teams` request will only return the teams the user is still a member in of course, so we fetch all local teams and mark them as `needsToBeUpdatedFromBackend`, we reset this flag for all teams we fetch during the slow sync, (we just fetched them so there is no need to do it again after the slow sync completed). After the slow sync we will try to fetch the deleted teams and receive a 4xx response and delete the team locally.
> Ensure we delete teams we did not receive a deletion event for

- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
We don't have email and phone number of other users and with SMB the 1to1 conversation might not be available, so always using user remote identifier as CallKit handle.
> Always using user remote identifier as CallKit handle

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
- Source/UserSession/SyncStatus.swift
- Tests/Source/UserSession/SyncStatusTests.swift
* Users might receive team related update events while not being able to parse them because they didn't update yet. To work around this we now force a slow sync in a HotFix to refetch all teams and all (team) conversations which might have been added before updating.
> Add a HotFix to enforce a slow sync when updating sync-engine to v88

- Source/Synchronization/Transcoders/TeamSyncRequestStrategy.swift
- Source/Synchronization/Transcoders/ZMConnectionTranscoder.m
- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Source/Synchronization/Transcoders/ZMLastUpdateEventIDTranscoder.m
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Source/Synchronization/Transcoders/ZMSelfStrategy+Internal.h
- Source/Synchronization/Transcoders/ZMSelfStrategy.h
- Source/Synchronization/Transcoders/ZMSelfStrategy.m
- Source/Synchronization/Transcoders/ZMUserTranscoder.m
- Source/Synchronization/ZMSyncStrategy.m
- Source/UserSession/SyncStatus.swift
- Tests/Source/Integration/SlowSyncTests.m
- Tests/Source/Synchronization/SynchronizationMocks.swift
- Tests/Source/Synchronization/Transcoders/ZMSelfTranscoderTests.m
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
- Tests/Source/UserSession/SyncStatusTests.swift
When fetching users during slowSync, the user payload does not contain an email address thereby deleting the selfUser's email address. During slowSync we should therefore also fetch the selfUser at the end.
Also changed: The slowSync strategies are now calling back the slowSyncStatus callBack with their respective phase - This way we avoid entering a wrong phase before the current phase has completed.
> Fetch selfUser at the end of slowSync

- Source/Synchronization/Transcoders/ZMLastUpdateEventIDTranscoder.m
- Source/UserSession/SyncStatus.swift
- Tests/Source/Synchronization/Transcoders/ZMLastUpdateEventIDTranscoderTests.m
- Replaced the assert with `ZMLogError`.
Idea for the future improvement: 
Create the precondition method that checks the condition and fails the test but crash on production.
> Fixed assert breaking tests

- Source/Synchronization/Transcoders/ZMUserTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMUserTranscoderTests.m
* After not fetching the self user in the`.fetchingUsers` sync phase with the introduction of the `.fetchingSelfUser` sync phase we failed to advance the current phase in the case that there are no local users. This will always be the case for users who just registered. See c6b80ed421f7f44944c9485ae6de27c68d50c560 for reference.
> Finish .fetchingUsers sync phase manually if there are no local users

- Source/Synchronization/Transcoders/TeamSyncRequestStrategy.swift
* After changing the logic to delete local teams not returned from the `/teams` endpoint instead of trying to refetch them (and then delete them in case of a 4xx response) some code resetting the flag to fetch them was still left in the code.
> Remove redundant code

- Source/Calling/ZMCallKitDelegate+WireCallCenter.swift
When an incoming group call times out, we are currently not ending the ringing. We receive a call ended callback from AVS with reason `STILL_ONGOING` and switch our internal callState from `.incoming(shouldRing: true)` to `.incoming(shouldRing:false)`. This has (for some reason) not been properly handled in the app.
> report call ended when group call times out

- Source/UserSession/ZMUserSession+Background.m
- Tests/Source/UserSession/ZMUserSessionTests.m
In some cases when a call timed out AVS would notify us about the timeout the next time the app enters the foreground. We would then create a notification (while the applicationStatus is still .background). iOS would then call `application: didReceiveLocalNotification:` which is usually only called when the user either taps on a notification while the app is already running. This in turn causes an automatic callback, because we assume the user actively tapped on the notification. 
To avoid automatic callbacks, missed call notifications now only open the conversation - but do not call back automatically anymore unless the call is still ongoing.
> do not call back automatically when acting on a missed call notification

- Source/UserSession/ZMUserSession+AddressBook.swift
* Add new public method to only upload contacts if there is no team `uploadAddressBookIfAllowed`, this check is more a fail-safe and we should still check this condition beforehand.
* This method will log an error as I would still suggest it being a programmer error to end up in a situation were we already asked the user for permissions as well as called to upload the contacts without checking if they belong to a team.
> Only upload address book in case there is no team

- Source/UserSession/ZMUserSession+Background.m
* We were passing a conversation from the UI context to the `LocalNotificationDispatcher`. The dispatcher internally only operates on the sync context.
* There is still another issue regarding the reply logic, we currently add a message observer to get notified whether the message was sent successfully or not. However, this observer does never fire at the moment, resulting in our background task timeout timer firing and finishing the background task with a result of `ZMBackgroundTaskResultFailed`. This bug is the cause for us always showing a `"Message failed to send"` notification when replying from a notification (this does not apply to liking from a notification as we are not showing any failure notifications in that case). I am still investigating the reason why the observer does not …
> Fix CoreData multithreading violation when sending a reply from a notification

- Source/Synchronization/Strategies/TeamDownloadRequestStrategy.swift
- Tests/Source/Synchronization/Strategies/TeamDownloadRequestStrategyTests.swift
Also changed logic for checking if the team is `binding`, so if the payload cannot be parsed the team would not be deleted.
> Fixed tests for new binding argument

- Source/Analytics/RequestLoopAnalyticsTracker.swift
- Tests/Source/Utility/RequestLoopAnalyticsTrackerTests.swift
Previously we would track request loops when fetching the user list as `/users/{id},{id}` which makes grouping different since the number of ids varies. We will now only track `/users/{id}`.
> remove list parameters for tracking request loops

- Tests/Source/E2EE/UserClientRequestFactoryTests.swift
- Tests/Source/E2EE/UserClientRequestStrategyTests.swift
- Tests/Source/Integration/IntegrationTestBase.m
- Tests/Source/Integration/LoginFlowTests.m
- Tests/Source/Integration/SlowSyncTests.m
- Tests/Source/Integration/UserProfileTests.m
- Tests/Source/MessagingTest.m
- Tests/Source/Synchronization/Strategies/DeleteAccountRequestStrategyTests.swift
- Tests/Source/Synchronization/Strategies/SelfContactCardUploadStrategyTests.swift
- Tests/Source/Synchronization/SynchronizationMocks.swift
- Tests/Source/Synchronization/Transcoders/ZMLoginCodeRequestTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMLoginTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMPhoneNumberVerificationTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMRegistrationTranscoderTests.m
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
- Tests/Source/UserSession/ApplicationStatusDirectoryTests.swift
- Tests/Source/UserSession/BackgroundAPNSPingBackStatusTests.swift
- Tests/Source/UserSession/ZMAccountStatusTests.swift
- Tests/Source/UserSession/ZMAuthenticationStatusTests.m
- Tests/Source/UserSession/ZMClientRegistrationStatusTests.m
- Tests/Source/UserSession/ZMUserSessionTests.m
- Tests/Source/UserSession/ZMUserSessionTestsBase.m
- WireSyncEngine.xcodeproj/project.pbxproj
Make test compile. Added TODOs for when I commented something out.
The following files has been removed from the test target since they need to be re-factored to use the unauthenticated session:
`ZMUserSessionRegistrationTests.m`
`EmailRegistrationTests.m`
`PhoneRegistrationTests.m`
`ZMUserSessionAuthenticationTests.m`
`LoginFlowTests.m`
> Registration improvements: make tests compile

- Source/AccountManager/SessionManager+ServerConnection.swift
- Source/AccountManager/SessionManager.swift
- WireSyncEngine.xcodeproj/project.pbxproj
We already have a `AccountManager` class in data model and the name wasn't good match for what it was doing anyway.
also renamed `AccountStateDelegate` to `SessionManagerDelegate` and cleaned up the method names.
> Rename AccountManager to SessionManager

- Source/Public/WireSyncEngine.h
- Source/Public/ZMUserSession.h
- Source/SessionManager/SessionManager+Logs.swift
- Source/SessionManager/SessionManager.swift
- Source/Synchronization/Transcoders/ZMLastUpdateEventIDTranscoder.m
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Source/UnauthenticatedSession/UnauthenticatedOperationLoop.swift
- Source/UserSession/ZMUserSession+Internal.h
- Source/UserSession/ZMUserSession+Logs.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Integration/IntegrationTest.h
- Tests/Source/Integration/IntegrationTest.m
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/Integration/IntegrationTestBase.m
- Tests/Source/Integration/PhoneRegistrationTests.m
- Tests/Source/Integration/UserProfileTests.m
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationSetTests.swift
- Tests/Source/Synchronization/Transcoders/ZMRegistrationTranscoderTests.m
- Tests/Source/Test-Bridging-Header.h
- Tests/Source/UserSession/ZMAuthenticationStatusTests.m
- Tests/Source/UserSession/ZMUserSessionTests.m
- Tests/Source/Utility/ApplicationMock.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Since the `ZMUserSession` has been replaced by the `SessionManager` as the entry point to SE we also need to update our integration tests to reflect that. Modifying the existing `IntegrationTestBase` was difficult since it inherits from `MessagingTest` which relies heavily on MOCs.
I therefore decided to create a `IntegrationTest` base class which tries to remain as close as possible to a real setup. The class is defined in obj-c but the implementation is in swift because obj-c classes can't inherit from swift classes.
> Fix phone registration tests

- Source/SessionManager/SessionManager.swift
- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
- Source/Synchronization/ZMOperationLoop.h
- Source/Synchronization/ZMOperationLoop.m
- Source/Synchronization/ZMSyncStrategy.h
- Source/Synchronization/ZMSyncStrategy.m
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
- Source/UnauthenticatedSession/ZMAuthenticationStatus.h
- Source/UnauthenticatedSession/ZMAuthenticationStatus.m
- Source/UserSession/ClientUpdateStatus.swift
- Source/UserSession/ZMUserSession+Internal.h
- Source/UserSession/ZMUserSession.m
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/Integration/LoginFlowTests.m
- Tests/Source/Synchronization/SynchronizationMocks.swift
- Tests/Source/Synchronization/Transcoders/ZMLoginCodeRequestTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMLoginTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMPhoneNumberVerificationTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMRegistrationTranscoderTests.m
- Tests/Source/UserSession/ZMAuthenticationStatusTests.m
- Tests/Source/UserSession/ZMUserSessionTestsBase.m
- WireSyncEngine.xcodeproj/project.pbxproj
Issues fixed while migrating tests:
* We didn't create an unauthenticated session if you got logged out.
* If your client got deleted we we will receive a event which logs you out. If you tried to log in again the first attempt would fail since we would again detect that your client was deleted.
> Fix login integration tests

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/LoginFlowTests.m
The login flow could get stalled if we login after the user session has already been created.
> Fix broken login flow tests

- Source/UserSession/SyncStatus.swift
- Tests/Source/Integration/ConversationTests+Ephemeral.swift
- Tests/Source/Integration/IntegrationTestBase.h
- Tests/Source/Integration/IntegrationTestBase.m
- Tests/Source/Integration/SendAndReceiveMessagesTests.m
* Fix `SendAndReceiveMessagesTests` and request loop during slow sync when receiving a 404 when requesting `/notifications`.
> Fix SendAndReceiveMessagesTests and slow sync request loop on /notifications 404

- Source/Synchronization/Transcoders/ZMLastUpdateEventIDTranscoder.m
- Tests/Source/Integration/SlowSyncTests.m
Some of the tests were getting into a request loop because of incorrectly handled case when payload is nil
> Fix slow sync tests

- Source/UserSession/UserProfileUpdateNotifications.swift
- Tests/Source/UserSession/UserProfileUpdateStatusTests.swift
Automatic retaining closure capture strikes the memory again.
> Fix retain cycle in user profile observer

- Tests/Source/Integration/CallingV3Tests.swift
AVS uses integer for timestamp, so tests that check if timestamp was updated after some action could sometimes fail. Fixed this by rounding the timestamp up. Although it could potentially be in the future, we only check if timestamp is larger than something we already have.
> Flaky calling tests: avoid failures by rounding timestamp up

- Source/Public/ZMUserSession.h
- Source/SessionManager/LocalStoreProvider.swift
- Source/SessionManager/SessionManager.swift
- Source/UserSession/ZMUserSession+Internal.h
- Source/UserSession/ZMUserSession.m
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/LocalStoreProviderTests.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/UserSession/BackgroundAPNSConfirmationStatusTests.swift
- Tests/Source/UserSession/BackgroundAPNSPingBackStatusTests.swift
- Tests/Source/UserSession/ZMUserSessionTests.m
- Tests/Source/UserSession/ZMUserSessionTestsBase.m
- WireSyncEngine.xcodeproj/project.pbxproj
It was tricky to test storage related behaviour (migration, store doesn't exist etc.), so I added a protocol that encapsulates the data and methods used for this. This is then injected to session manager/user session and enables us to easily mock the behaviour in tests.
This will unfortunately conflict with https://github.com/wireapp/wire-ios-sync-engine/pull/466, but at same time IMHO make it slightly simpler.
> Injecting store details

- Source/Public/ZMUserSession.h
- Source/Synchronization/Transcoders/ZMSelfStrategy.m
- Source/Synchronization/ZMHotFix.m
- Source/UserSession/SyncStatus.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Synchronization/ZMHotFixTests.m
This PR add new property `hasCompletedInitialSync`. We currently have a similar property in the UI but it's unreliable since it's based on the `initialSyncCompleted` notification which doesn't guarantee the order in which the observers are executed.
Additionally we now also skip applying all hot fixes for on a fresh install and therefore avoids some unnecessary requests.
> Initial sync fixes

- Source/Synchronization/NSManagedObjectContext+EventDecoder.swift
* Fix core data multithreading assertion when setting context type on eventMOC.
> Fix core data multithreading assertion when setting context type on eventMOC

- Source/UnauthenticatedSession/UnauthenticatedOperationLoop.swift
- Source/UnauthenticatedSession/UnauthenticatedSession+Login.swift
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
- Source/UnauthenticatedSession/ZMAuthenticationStatus.m
- Tests/Source/MessagingTest.m
- Tests/Source/UserSession/UnauthenticatedSessionTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
On automation it was noticed that the login error is not always appearing. The error is produced by the timer in `ZMAuthenticationStatus`. I checked the timer and it worked correctly.
The improvement proposed here is to fail the login if the device appears to be offline.
> Fail login immediately when offline

- Source/SessionManager/SessionManager.swift
Some devices would retain the cookie in the keychain causing the
login to get stuck. We can't work around this by deleting all keychain
items if we don't have data store. This fix is not necessary in the
upcoming multi account setup.
https://wearezeta.atlassian.net/browse/ZIOS-8844
> Delete keychain items on a fresh install

- Source/Synchronization/ApplicationStatusDirectory.swift
- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
- Source/UserSession/ClientUpdateStatus.swift
- Tests/Source/E2EE/UserClientRequestStrategyTests.swift
- Tests/Source/UserSession/ClientUpdateStatusTests.swift
We longer get a authenticationDidSucceed notification on launch since we
can assume we are logged in if the user session is created.
> Mark need to fetch clients on init since we are always logged in now

- Source/Public/WireSyncEngine.h
- Source/Public/ZMUserSession.h
- Source/SessionManager/SessionManager.swift
- Source/UserSession/ZMBlacklistVerificator.h
- Source/UserSession/ZMUserSession.m
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Since the introduction of the core-data free login blacklisting is not enforced until you've logged in. 
Move the blacklist checker from `ZMUserSession` to `SessionManager`.
It would be nice to write a test for blacklist logic inside SessionManager.  In order to do so we should create a protocol for the`ZMBlacklistVerificator` and inject it into the SessionManager. I would do this a follow up PR since I want to continue with the RC.
> Move blacklist checker to SessionManager

- Source/SessionManager/LocalStoreProvider.swift
- Source/SessionManager/SessionManager.swift
- Source/Synchronization/ZMSyncStrategy.m
- Source/UserSession/ZMUserSession.m
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/UserSession/ZMUserSessionTestsBase.h
- Tests/Source/UserSession/ZMUserSessionTestsBase.m
The `LocalStoreProvider` object is not retained in the `SessionManager` (neither should or was `self`in any of the involved completion handlers), but only used to invoke the `create...` method method on it which in turn will pass a complete instance of `LocalStoreProvider` in its completion handler. This instance is then passed to the user session init. This API design had a couple of shortcomings which are addressed in this PR.
Before this change an instance of `LocalStoreProvider` was created with its `contextDirectory` set to `nil`. After invoking the async `create...` method on that object the completion handler was called passing on the object itself with the directory set. This PR converts the `create...` method to be a `static` one. The completion handler still hands over a …
> Move LocalStoreProvider creation into static function

- Source/UserSession/ZMUserSession+Background.m
- Source/UserSession/ZMUserSession.m
When registering for remote notifications, we were not checking if the app was being run on the device, which has no push notifications.
Before registering for notifications, we now check if the simulator is being used, if so, we log a message and return early.
> guard against registering for remote notifications when using simulator

- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Team accounts should use team image, even if it's not available yet.
> Do not set account image for accounts with team

- Source/UserSession/CallStateObserver.swift
With CallKit and notifications enabled, the user was not receiving any notifications that they had missed a call. More specifically, when A calls B, and B does not pickup and eventually A cancels or the call times out, then B will have no notification that A ever called.
When observing the call state, we were only generating a missed call notification when the user missed a group call that was terminated normally. We now generate the notification if the previous condition is true **OR** the call was canceled (from the sender side).
> show missed call notification when using CallKit

- Source/UserSession/FileRelocator.swift
It's dangerous to crash the app on detecting any unknown files in the Caches directory since potentially
they could be created by the system. This PR will change the fatal to only crash on internal builds.
> Relax constraint on finding unknown files in the Caches directory

- Source/Synchronization/ZMOperationLoop+Background.h
- Source/Synchronization/ZMOperationLoop+Background.m
- Source/Synchronization/ZMOperationLoop.h
- Source/Synchronization/ZMOperationLoop.m
- Source/UserSession/ZMUserSession.m
- Tests/Source/Synchronization/ZMOperationLoopTests.m
With the coming support of multiple users registering for the same push token the backend is going to include the user id into the incoming notification payload. In the future we are going to forward those notifications to the proper sync engine.
Currently the incoming notification could potentially be for the other user too, but we have no sync engine running for that user.
We are going to temporarily discard the notifications that are coming not for the current user.
> Discard notifications for other users

- Source/Calling/WireCallCenterV3.swift
- Source/Calling/WireCallCenterV3Factory.swift
- Source/Synchronization/Strategies/CallingRequestStrategy.swift
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/Calling/CallSystemMessageGeneratorTests.swift
- Tests/Source/Calling/VoiceChannelParticipantV3SnapshotTests.swift
- Tests/Source/Calling/VoiceChannelV3Tests.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
- Tests/Source/UserSession/ZMUserSessionTestsBase+Calling.swift
When the `WireCallCenterV3` is created we initialize the wcall in the init, and wcall is dispatching immediately asynchronously the callback to download the call config. The `transport` is necessary to download the call config, but it is assigned only after the `WireCallCenterV3.init` is done. This creates the race condition, where it could happen that the async callback from AVS could arrive before the init is done, so the transport is not assigned yet.
Pass transport as an init argument, to guarantee that it is set when any callback is called.
> Fixed call config race condition

- Source/Calling/ZMCallKitDelegate.h
- Source/Calling/ZMCallKitDelegate.m
- Tests/Source/Calling/ZMCallKitDelegateTests.swift
It wasn't possible to receive or make calls after switching accounts, this seems to be caused by us not invalidating the old CallKit provider.
> Invalidate CallKit provider when tearing down a user session

- Source/Calling/ZMCallFlowRequestStrategy.m
- Source/Synchronization/Transcoders/ZMLoginTranscoder.m
- Source/Synchronization/Transcoders/ZMRegistrationTranscoder.m
- Source/Synchronization/ZMOperationLoop+Notifications.swift
- Source/Synchronization/ZMOperationLoop.h
- Source/Synchronization/ZMOperationLoop.m
- Source/UnauthenticatedSession/ZMAuthenticationStatus.h
- Source/UnauthenticatedSession/ZMAuthenticationStatus.m
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/ZMCallFlowRequestStrategyTests.m
- Tests/Source/Integration/ConnectionTests.m
- Tests/Source/Synchronization/ZMOperationLoopTests.m
- WireSyncEngine.xcodeproj/project.pbxproj
Removed all relevant NSNotificationCenter-based notifications. Those that are left are OK to still use NSNotificationCenter, while `ZMLaunchedWithPhoneVerificationCodeNotificationName` is still broken and would need to be revised later in a separate PR.
> Remove NSNotificationCenter based notifications

- Source/SessionManager/SessionManager+ServerConnection.swift
- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
I added observers for when a new user session is created in the `SessionManager`. I could not reuse the already existing  delegate as the observer needs to be added later and multiple observers might be needed.
In doing this, I had to rename the method to register `ServerConnection` observer as the name was clashing.
> Notify when a new user session is created

- Source/Synchronization/Transcoders/ZMSelfStrategy.m
- Source/Synchronization/ZMSyncStrategy.m
The same behaviour can be achieved with a normal instance variable. Having dispatch once causes analysis warnings.
> Remove unnecessary dispatch_once

- Source/UserSession/UserProfileUpdateNotifications.swift
UI expects that it gets called on the main thread when observing user profile changes.
> Dispatch UserProfile notifications on the main thread

- Source/UserSession/ZMUserSession.m
Skipping notifying the UI would leave the UI in a inconsistent state because we wouldn't be notified again if the app entered the foreground.
> Don't skip notifying network state if app is in the background

- Source/Public/ZMUserSession.h
- Source/SessionManager/SessionManager.swift
Issue happened because the `ZMUserSession` created from the push never got `SessionManager` assigned.
Implemented the single method `configure(session userSession: ZMUserSession, for account: Account)` to configure the new user session.
> Register session manager to user session

- Source/SessionManager/SessionManager.swift
This change avoids having a time when there is no active session while we switch to another session. Not having an active session causes the UI to crash in many places during a switch.
> Wait for a new UserSession to be ready before removing the old one

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
We sometimes crash when we transition fast between logged in / logged out state. For example when you open the app and discover that your client has been deleted. The crashes happen because we load the UI asynchronously and  therefore might reference the user session after it has been destroyed.
When the `SessionManager` want to tear down a user session it will now ask the UI to logout and tell us when it's done doing that. Only after being told the UI is done transitioning to the logged out state will we begin tearing down the user session. 
NOTE: We could also do a similar thing when switching between accounts.
> Wait for UI to be torn down on logout

- Source/SessionManager/SessionManager.swift
`closeAndDeleteCookie` is dangerous, since then the session would be torn down but not deallocated and persist in `backgroundUserSessions` as the reference.
> Correctly tear down the background session

- Source/SessionManager/SessionManager.swift
- Source/Utility/DispatchQueue+SerialAsync.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/Utility/DispatchQueueSerialAsyncTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Session loading is async, this makes it possible to accidentally load the session twice when the session loading event (push) is happening quickly one after another.
> Fixed possible multi session creation via push

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/EmailRegistrationTests.m
- Tests/Source/Integration/IntegrationTest.h
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/Integration/PhoneRegistrationTests.m
- Tests/Source/SessionManager/SessionManagerTests.swift
Since logout is now asynchronous the account deleted needed to be refactored.
I also deleted `sessionManagerCreated(unauthenticatedSession:)` since didn't have much
of purpose anymore and was interfering with the logout. This could happen if it was
executed before the `sessionManagerDidFailToLogin()` or `sessionManagerWillLogout()`,
we would then lose the error message.
This should fix the pre-filling of the email on logout.
> Fixes for account deletion & logout

- Source/SessionManager/SessionManager.swift
- Source/UserSession/ZMUserSession+Background.m
- Source/UserSession/ZMUserSession.m
Problem appears when 2 user sessions are active (A, B) -- for example user started the app and switched from A to B and back: A is active, B on background.
1. User sends the app to the background -> Observation system is paused
2. Someone creates the conversation with user from B and writes the message while the app is in the 
3. User activates the app
4. The observation of the list has to catch up, and now it's done in UI and only for the active session with `    [ZMConversationList refetchAllListsInUserSession:ZMUserSession.sharedSession]`
5. The list on the session A is up to date, but on B it's missing the new conversation
Consequences: conversation is missing from the list if user activates B, the dot is absent for B.
Make `ZMUserSession` refresh it's lists when the app is going to …
> Conversation list off fix

- Source/SessionManager/SessionManager.swift
A second part of fixing the same problem as https://github.com/wireapp/wire-ios/pull/1316
It manifests when logging in to an account that doesn’t have the cookie anymore. The reason behing the problem is that there is already an active user session available when trying to login to another account. This puts session manager in weird state and prevents login from proceeding.
N.B. There are no tests for this and I had trouble writing it because MockTransport doesn't support multiple accounts. Some more thinking is needed to come up with a solution to this.
> Fix: Stuck during login

- Source/Notifications/Push notifications/LocalNotificationDispatcher+Messages.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
The only system message notifications that were being dispatched were concerning members joining/leaving group conversations. But we only want to be notified if someone adds/deletes us from a conversation.
Additionally, we no longer need to bundle these notifications since we are not collecting participation notifications from other members (bundled notifications lead to "People were added to the group")
> filter system messages for push/chathead notifications

- Source/SessionManager/SessionManager.swift
we were crashing on switching between accounts
https://rink.hockeyapp.net/manage/apps/65633/app_versions/1150/crash_reasons/188662498
when running `select()` to switch active account the following happens:
1. start tearing down UI and display the skeleton
2. load the new session and set `activeUserSession`
3. tearing down the UI finishes and we nil out the `activeUserSession`
4. we start loading the UI but it will crash because `activeUserSession` is nil 
Delay loading the new session until we've finished tearing down the UI
> Don't start loading loading the new user session until the UI has been torn down

- Source/Data Model/Push Token/ZMPushToken.h
- Source/SessionManager/SessionManager+Push.swift
- Source/Synchronization/Strategies/PushTokenStrategy.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/Synchronization/Strategies/PushTokenStrategyTests.swift
The iOS client crashes when you login on the release candidate build.
https://wearezeta.atlassian.net/browse/ZIOS-9032
The Release candidate build is a special build were we have taken the app store build but re-signed it with a different provisioning profile so that it can run on our test devices. This however makes the push token entitlements invalid and we wont' get a device token. This wasn't a problem until we moved the push token handling to Swift, we now end up force unwrapping a nil value.
Annotate the `ZMPushToken` with nullability so that we don't force unwrap a nil value.
> Annotate ZMPushToken with nullability to avoid force unwrap in Swift

- Source/Calling/WireCallCenterV3.swift
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
AVS does not manage ending other incoming calls when we answer a call so we must handle this
in the call center. We did already do this but only in the UI so it would not work for callkit calls.
> End other calls when answering/starting call

- Source/Synchronization/ApplicationStatusDirectory.swift
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Source/Synchronization/ZMSyncStrategy.m
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
For some users frequently it is not possible to send the message because of the timeout.
It comes out that at least one of the issue cases can be reproduced with the following steps:
1. Configure the client to have 2 accounts logged in (A is active, B inactive)
2. Kill the client
2. Enable Wi-Fi
2. Start the client
3. Disable Wi-Fi
4. Send the message from another device to the B (inactive) account
5. Activate B
-> Any message sent on B would not be delivered.
During the investigation it came clear that no request was generated, since the `ApplicationStatus` in `AbstractRequestStrategy` was signaling that `notificationFetchStatus` is still `.inProgress`, which means that the sync engine was thinking that we are still fetching the notification stream due to the push received. This is …
> Possible fix for messages getting stuck

- Source/Calling/CallKitDelegate.swift
Obj-C code was calling another method: 
https://github.com/wireapp/wire-ios-sync-engine/blob/118.0.0/Source/Calling/ZMCallKitDelegate.m#L110
Most likely missed while porting to Swift.
> Fixed swift porting issue with localization

- Source/Public/NSError+ZMUserSession.h
- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
It was possible to add more than three accounts by triggering a logout and then logging into a new account.
We do an additional account limit check before adding the account.
> Add account limit check to SessionManager

- Source/Calling/CallKitDelegate.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
We must tell callkit that the call is established when the data channel is established
and not when the audio is flowing.
> Fix incoming callkit call not connecting

- Source/UserSession/ZMUserSession+Actions.swift
Swiping on an APNS notification for incoming calls only opens the app, it does not switch to the appropriate account to display the conversation and calling overlay
Previously, when handling the incoming call notification, we were requiring that `actionIdentifier == ZMCallAcceptAction`. However, when swiping right on notification, the `actionIdentifier` is nil (since the notification is just being opened, not triggering an action), and consequently we return early.
Just before returning, we open the conversation attached to the notification. This will switch accounts if necessary, and show the call screen overlay.
> always open conversation when calling APNS is opened

- Source/Calling/CallKitDelegate.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
Not correctly informing Callkit that the call had connected would trigger and error when the remote party ended the call.
https://wearezeta.atlassian.net/browse/ZIOS-9093
> Fix using wrong UUID when reporting call connection state of call

- Source/UserSession/ZMUserSession+Push.swift
- Tests/Source/UserSession/ZMUserSessionTests.m
Since iOS11, tapping on incoming call notification for the inactive account would not switch to that account to display the call overlay.
On iOS 11, tapping a call notification would invoke this method with an active app state, meaning we would not create and process the pending notification and thus not handle the action. By not requiring the app to be `inactive` or in `background`, the notification action is always handled. Allowing an active state is acceptable because this method is only called when tapping a system notification, which can only be done when the app is not in the foreground. If a call comes for the inactive account while the app is in the foreground, the `LocalNotificationDispatcher` will funnel the notification to the `ChatHeadsViewController`, which will handle the …
> don’t require non active app state to handle call action

- Source/Synchronization/Transcoders/ZMConversationTranscoder.h
- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Source/Synchronization/ZMObjectStrategyDirectory.h
- Source/Synchronization/ZMSyncStrategy+EventProcessing.h
- Source/Synchronization/ZMSyncStrategy+EventProcessing.m
- Source/Synchronization/ZMSyncStrategy.m
- Tests/Source/Integration/ConnectionTests.m
- Tests/Source/Integration/ConversationsTests.m
- Tests/Source/Synchronization/SynchronizationMocks.swift
- Tests/Source/Synchronization/Transcoders/ObjectTranscoderTests.h
- Tests/Source/Synchronization/Transcoders/ObjectTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderSystemMessageTests.swift
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
- Tests/Source/Test-Bridging-Header.h
- WireSyncEngine.xcodeproj/project.pbxproj
ZMConversationTranscoder has taken over the task of inserting system messages.
*NOTE:* also noticed that processDownloadedEvents was never called anywhere and
that therefore all events are considered "live".
---
When a user changes a conversation name or add/remove a participant we currently will insert
two system message for this event. This happens because the change event arrives twice, first
in the response of POST response and second in the notification stream.
Add a check before inserting these system messages for if the change has already been applied.
> Fix for double system message

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
We don't show the cancel-login button when switching to an account which is unauthenticated. This is because we don't show cancel button if there's a login error for the currently selected account, but in this case the login error is actually not from the selected account.
In order to correctly decide when to show the cancel button we need to know which account failed to log in. Therefore I'm adding an `account` parameter to the `sessionManagerDidFailToLogin()` delegate method.
> Add account parameter to failed-to-login delegate method

- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification+Events.swift
`ZMLocalNotification`s for `conversationCreate` events were displaying the conversation name (initially a list of user's first names) in the chatheads, because if the chatted is for the active account, the conversation name stored in the `userInfo` is used as the title.
For event notifications that do not require a conversation (even if they may have one), do not store the conversation name in the `userInfo`.
> only store conversation name if notification requires it

- Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification+Calling.swift
- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification+Events.swift
- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification+Messages.swift
- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
When this setting is enabled, then the APNS notification should have no title and the body should say *New message*.
Note: since this setting affects only APNS notifications, the logic only affects the `ZMLocalNotification`s `uiNotification` properties.
> Respect "hide notification preview" setting

- Source/Calling/CallKitDelegate.swift
- Source/UserSession/ZMUserSession.m
Disabling Callkit would make all calls not connect until the next restart.
Update `setUiStartsAudio` flag on media manager when disabling Callkit, otherwise AVS will never start the audio recording.
> Fix calls not connecting after disabling Callkit

- Source/UserSession/ZMUserSession.m
The fields on the shared instance of `BackgroundActivityFactory` are:
- Shared application
- Main group queue
Those are reset every time the `ZMUserSession` is created and in `SessionManager`.
It is enough to initialize the fields in the `SessionManager` once.
> Do not set the BackgroundActivityFactory from the ZMUserSession

- Source/Utility/ZMSound.swift
In preparation for supporting `none` sound effect and ringtones I've added the the default sounds as enum cases and create two groups: `soundEffects` and `ringtones`.
> Add default sounds to ZMSound

- Source/Utility/ZMSound.swift
We were force unwrapping nil in the case that the sound file wasn't in our bundle, leading to a crash on start up when trying to set the custom sound.
Safely unwrap the path.
> don't force unwrap file path

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
Method `-[NSManagedObject fetchRequest]` is only available on iOS 10.
Objective-C compiler is not checking the usage of new selectors. Shame!
> -fetchRequest is not availble: Fixed crash on iOS9

- Source/Synchronization/Strategies/RegistrationStatus.swift
- Source/Synchronization/Strategies/TeamRegistrationStrategy.swift
- Source/Synchronization/Strategies/TeamToRegister.swift
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
- Tests/Source/Integration/TeamCreationTests.swift
- Tests/Source/Synchronization/Strategies/EmailVerificationStrategyTests.swift
- Tests/Source/Synchronization/Strategies/RegistrationStatusTestHelper.swift
- Tests/Source/Synchronization/Strategies/RegistrationStatusTests.swift
- Tests/Source/Synchronization/Strategies/TeamRegistrationStrategyTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
We are adding a new flow for creating team (together with admin account). The current registration is handled by `ZMAuthenticationStatus` which is pretty complicated. The plan is to slowly transition to a new Swiftified `RegistrationStatus` which encodes states into an enum with associated values.
* Added a new `TeamRegistrationStrategy` which handles team creation. It is very similar to `ZMRegistrationTranscoder`
* Added new method for starting team registration which expects `TeamToRegister` object. This should be created by UI when all needed information is gathered.
> Create team strategy

- Source/Calling/CallKitDelegate.swift
- Source/Calling/SystemMessageCallObserver.swift
- Source/Calling/WireCallCenterV3+Notifications.swift
- Source/Calling/WireCallCenterV3.swift
- Source/Notifications/Push notifications/LocalNotificationDispatcher+Calling.swift
- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification+Calling.swift
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/Calling/CallSystemMessageGeneratorTests.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
- Tests/Source/Integration/CallingV3Tests.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherCallingTests.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForTests_CallState.swift
When a group ends the push notification says the self user called
the user id associated with the terminating event is the self user.
The user id associated with the event is not relevant. We should instead use the userId associated with the incoming call event.
The sender parameter on the calling update methods has always been a bit unclear to which user it actually refers. This PR replaces it with a `caller` parameter which is always the user which initiated the call.
> Make call center API more clear

- Source/SessionManager/SessionManager.swift
- Source/Synchronization/Strategies/RegistrationStatus.swift
- Source/Synchronization/Strategies/TeamToRegister.swift
- Tests/Source/Integration/TeamCreationTests.swift
- Tests/Source/Synchronization/Strategies/RegistrationStatusTests.swift
- Tests/Source/Synchronization/Strategies/TeamRegistrationStrategyTests.swift
There were several issues that were noticed after integrating the API call with real data:
* We were not posting the email activation code together with payload
* `icon` in team payload is required. To align implementation with Android we simply send `abc`, because we don't yet support team images.
* Flag that shows if we have just completed registration is needed in the UI.
> Team creation tweaks

- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification.swift
iOS9 devices don't show the APNS `alertTitle` in the lock screen or banners, only in the notification center.
Combine the title and body text (separated by a newline) and use it as the notification's `alertBody`.
> combine title & body for APNS if iOS9

- Source/Public/NSError+ZMUserSession.h
- Source/SessionManager/SessionManager.swift
- Source/Synchronization/Strategies/EmailVerificationStrategy.swift
- Source/Synchronization/Strategies/TeamRegistrationStrategy.swift
- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
- Source/Synchronization/Strategies/UserProfileUpdateRequestStrategy.swift
- Source/UnauthenticatedSession/UnauthenticatedSession+Login.swift
- Source/UnauthenticatedSession/UnauthenticatedSession+Registration.swift
- Source/UserSession/NSError+Localized.swift
- Source/UserSession/NSError+ZMUserSession.m
- Source/UserSession/NSError+ZMUserSessionInternal.h
- Source/UserSession/ZMClientRegistrationStatus.m
- Source/UserSession/ZMUserSessionErrorCode+Localized.swift
- Tests/Source/E2EE/UserClientRequestStrategyTests.swift
- Tests/Source/Integration/PhoneRegistrationTests.m
- Tests/Source/Integration/UserProfileTests.m
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/Synchronization/Strategies/RegistrationStatusTestHelper.swift
- Tests/Source/Synchronization/Transcoders/ZMLoginCodeRequestTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMPhoneNumberVerificationTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMRegistrationTranscoderTests.m
- Tests/Source/UserSession/UnauthenticatedSessionTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
There are some errors that we show to the user and we want them to be localized.
There was a method called `LocalizedDescriptionStringFromZMUserSessionErrorCode` which actually produced a description that is not localized and only usable for debugging purposes.
Added strings for all errors that we currently show in team registration flow.
> Added error localization

- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
Call timer gets reset when someone joins a call.
The `establishedDate` gets updated when the established-call-handler is called. In group calls that once per call participants which has the effect that timer gets reset when some joins the call.
Work around this behaviour by no updating `establishedDate` if the call is already established.
> Fix call timer getting on every time someone joins a call 

- Resources/Base.lproj/Push.strings
- Source/Notifications/Push notifications/Helpers/ZMLocalNotificationLocalization.m
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationLocalizationTests.swift
The notification title "in Team" (occurs when we have a team name, but no conversation name) has been changed to simply "Team". Two push string keys were removed since we only need localization when we have both the conversation name and the team name. Since we don't call these push strings anymore, we won't have issues with missing translations.
> change notification title from  “in Team” to “Team”

- Source/UserSession/ZMUserSession.m
An incoming Callkit call will fail if the is app opened while the call is ongoing.
We currently re-configure the `callNotificationStyle` when we load UI. The reason for this is probably to cover case that Callkit needs be disabled when you add a second account. This re-configuring will destroy and re-create the `CallKitDelegate` for users with only one account and fail any ongoing calls.
Don't re-create the `CallkitDelegate` if it already exists.
> Don't re-create the CallkitDelegate if it already exists

- Source/Public/ZMUserSession.h
- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Source/UserSession/ZMUserSession.m
Send a notification when we detect more than one locally removed group participants. In the UI we only support removing participants one by one so this should only happen if something is out of sync.
> Send notification when detect more than 1 removed participant

- Source/Synchronization/Decoding/EventDecoder.swift
- Tests/Source/Synchronization/EventDecoderTests.swift
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
Generic message update path
1. ZMUpdateEvent arrives
- on websocket
- via notifications stream
- decrypted in event decoder
2. Update events are processed by all event consumers
- CallingRequestStrategy, ZMEventConsumer, PushTokenStrategy, ClientMessageTranscoder, ...
Relevant for generic messages are CallingRequestStrategy, ClientMessageTranscoder, AvailabilityRequestStrategy
Validating the generic message in every event consumer is quickly getting out of control.
We should introduce a validation (filter) step before we give the update event to the event consumers.
> Filter invalid events before forwarding to consumers

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
You would sometimes end up being stuck on the migration screen which never goes away.
On app app launch migration happens with the following steps:
`activateUserSession(for account: Account) ` is called . 
This will cause the following delegate methods to be called:
- `sessionManagerWillOpenAccount` - UI shows loading screen
- `sessionManagerWillStartMigratingLocalStore`  UI shows migration screen
-  `sessionManagerActivated(userSession:)` UI shows main app UI
However if you have already launched the app and you receive an APNS on a second account which requires migration the following will happen.
`withSession(for account: Account)` is called.
This will cause the following delegate method to be called:
`sessionManagerWillStartMigratingLocalStore` UI shows migration screen.
So since we …
> Extend API to tell which account is being migrated

- Source/Synchronization/Strategies/TeamInvitationRequestStrategy.swift
- Tests/Source/Synchronization/Strategies/TeamInvitationRequestStrategyTests.swift
* The error label in case an email is already registered on Wire was wrong.
> Adjust expected error label for team invitations

- Source/Data Model/ServiceUser.swift
- Source/UserSession/Search/SearchDirectory.swift
- Source/UserSession/Search/SearchResult.swift
The service user image updates where not propagated.
The issue happened since the service users where not added to the list of observed search users.
Additionally, fixed the warnings introduced with services release.
> Fixed service images update propagation; warnings

- Source/Analytics/NotificationsTracker.swift
- Source/Notifications/Push notifications/ZMPushRegistrant.swift
- Source/SessionManager/PushDispatcher.swift
After shipping tracking implemented in #664 and looking through data there were some curious discrepancies. 
Calls to increment counter values were called from multiple threads but there were no code to handle this.
Added isolation queue so that we would serialize all the calls for incrementing counters. Also added one more counter that tracks how many times the app didn't have enough time to process the notification and the background task expired.
> Improve notifications tracking

- Source/UserSession/Search/SearchTask.swift
- Tests/Source/UserSession/SearchTaskTests.swift
The search query must be trimmed in order to search for the bots correctly.
> Trim the service search query

- Source/UserSession/ZMUserSession+Push.swift
The client seem to crash when receieving the push and try to forward it to one of the user sessions.
The user session, that is managed by the session manager, can be deactivated and deallocated in case of memory pressure. The moment when the user session is torn down and deallocated is separated in time.
The push that app receives from APNS is proposed to all existing user sessions that where created by the session manager. The session manager keeps the weak references to all user sessions that are still in memory.
The client seem to crash when receieving the push and try to forward it to the user session that was torn down, but was not deallocated yet.
As a temporary solution to allow users to keep receiving the pushes the client will check if the user session was not torn down yet …
> Do not crash on inactive SE push

- Source/Data Model/ServiceUser.swift
- Tests/Source/Data Model/ServiceUserTests.swift
It is necessary to differentiate the different error causes from the call to add the bot to the conversation.
> Bots adding error handling

- Source/UserSession/Search/SearchTask.swift
- Tests/Source/UserSession/SearchTaskTests.swift
New tag is necessary, since the BE is searching the integrations first by the tag, and then by the provider. This creates the issue that the BE is fetching first 100 services for tag `tutorial` and then filtering them by the provider. Sometimes the services are in the second part of the list, so the result is returned empty from the backend.
> Use integration as default tag

- Source/Data Model/ServiceUser.swift
The error is reported correctly now only when the new conversation is created.
> Report offline error when adding service while offline

- Source/UnauthenticatedSession/UnauthenticatedSession+Login.swift
- Tests/Source/UserSession/UnauthenticatedSessionTests.swift
There was no control over login requests made without an internet connection, so the app was going into a requests loop because of the lack of connection.
I've added the same reachability checks that are made with email login. I've also added a new test.
> ZIOS-9527: Added reachability check when logging with phone.

- Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Localization.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForTests_CallState.swift
When receiving a push about missed called from your second device it would contain a localization key.
Missed calls from your self was calculated to have the key `push.notification.call.missed.group.self` which doesn't exist. The `self` suffix for a localization key actually only exists for adding and removing participants.
Remove logic which adds `self` when the sender is the self user. This case is already handled by special case for adding and removing participants.
> Fix wrong localization key for missed calls

- Source/Calling/CallKitDelegate.swift
- Source/Calling/FlowManager.swift
- Source/Calling/ZMCallFlowRequestStrategy.h
- Source/Calling/ZMCallFlowRequestStrategy.m
- Source/Public/ZMUserSession.h
- Source/SessionManager/SessionManager+AVS.swift
- Source/SessionManager/SessionManager.swift
- Source/UserSession/ZMUserSession+Internal.h
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/CallKitDelegateTests.swift
- Tests/Source/SessionManager/SessionManagerAVSTests.swift
- Tests/Source/UserSession/ZMUserSessionTests.m
- WireSyncEngine.xcodeproj/project.pbxproj
The logs for CallKit weren't ending up in the voice log.
The CallKitDelegate was using a method for logging on the flow manager which had been de-activated.
- Deleted the deactivated method from the FlowManager type.
- Cleaned up a few places were the flow manager was used for logging.
- Moved the AVS logging methods from the ZMUserSession to the SessionManager.
> Include callkit logs into voice log

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
- Tests/Source/Synchronization/ZMHotFixDirectoryTests.swift
- Tests/Source/Synchronization/ZMHotFixTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
After introduction of permissions for guests in conversations we need to download current permissions for all existing conversations
Added a hotfix to mark all team group conversations as needed to be updated from backend.
> Refetch group conversations in teams to get new permission data

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
A change to the access mode of conversation would move it to the top of the conversation list.
All updates event update `lastModifiedDate` on conversation unless explicitly stated not to.
Add `ZMUpdateEventType.accessModeUpdate` to the list of ignored events.
> Don't move conversation to top when access mode changes

- Source/Data Model/Conversation+AccessMode.swift
- Tests/Source/Integration/ConversationTests+Guests.swift
- Tests/Source/Registration/AddressBookTests.swift
- Tests/Source/Synchronization/ZMConversationSetAccessModeTests.swift
New property on `ZMConversation` to unify the logic for understanding if the current self user can change the access mode of the conversation.
> New getter to determine if the conversation access can be managed

- Source/SessionManager/SessionManager.swift
- Source/UnauthenticatedSession/ZMAuthenticationStatus.m
- Source/UnauthenticatedSession/ZMAuthenticationStatus_Internal.h
- Tests/Source/Integration/PhoneRegistrationTests.m
- Tests/Source/Synchronization/Transcoders/ZMPhoneNumberVerificationTranscoderTests.m
- Tests/Source/UserSession/ZMAuthenticationStatusTests.m
We currently handle registration with already registered phone/email in a special fashion. This unfortunately is prone to breaking and in fact does from time to time.
We will try to simply return errors as we get them from the server and handle all scenarios in UI.
> Fix authentication issues

- Source/UnauthenticatedSession/UnauthenticatedSession+Login.swift
- Source/UnauthenticatedSession/UnauthenticatedSession+Registration.swift
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
If we have airplane mode turned on during registration the requests are being retried continuously. When logging in we check for reachability and show error instead.
Unify checks for reachability in both login and registration.
> Added simple block for offline check

- Source/UserSession/OpenConversationObserver/UserExpirationObserver.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/UserSession/UserExpirationObserverTests.swift
It appears that ZMTimer is calling it's callback on the background thread. Now the call is dispatched to the correct thread.
> Dispatch to the correct thread

- Source/Synchronization/Transcoders/ZMLoginTranscoder+Internal.h
- Source/Synchronization/Transcoders/ZMLoginTranscoder.h
- Source/Synchronization/Transcoders/ZMLoginTranscoder.m
- Source/Synchronization/Transcoders/ZMRegistrationTranscoder.h
- Source/Synchronization/Transcoders/ZMRegistrationTranscoder.m
- Source/UnauthenticatedSession/UnauthenticatedSession+Login.swift
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
- Source/UnauthenticatedSession/ZMAuthenticationStatus.h
- Source/UnauthenticatedSession/ZMAuthenticationStatus.m
- Source/UnauthenticatedSession/ZMAuthenticationStatus_Internal.h
- Source/UserSession/PreLoginAuthenticationNotification.swift
- Tests/Source/E2EE/UserClientRequestFactoryTests.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/Integration/LoginFlowTests.m
- Tests/Source/Synchronization/SynchronizationMocks.swift
- Tests/Source/Synchronization/Transcoders/ZMLoginCodeRequestTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMLoginTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMPhoneNumberVerificationTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMRegistrationTranscoderTests.m
- Tests/Source/UserSession/UnauthenticatedSessionTests.swift
- Tests/Source/UserSession/ZMAuthenticationStatusTests.m
We would like to offer a possibility to restore from backup after login. This needs some changes in the authentication flow to not continue registering clients and in general spinning up CoreData before we import things.
Added one more phase in the authentication - WaitingToImportBackup. It will wait here until a corresponding method is called to continue the regular auth flow. We do this by remembering the response we got after login and not passing it to UserInfoParser (which in turn kicks off authenticated session creation) until we are done with import.
Still need to:
> Authentication flow: Added a step for backup import

- Source/SessionManager/SessionManager+Backup.swift
- Tests/Source/SessionManager/SessionManagerTests+Backup.swift
* Expose method to clear backups folder so we don't have to use methods on `StorageStack` from the UI.
* Fix imports directory folder name.
* Add tests.
> Expose method to clear backups folder

- Source/Public/ZMUserSession+Authentication.h
- Source/UserSession/AccountStatus.swift
- Source/UserSession/ZMUserSession+Authentication.m
- Tests/Source/Integration/LoginFlowTests.m
- This was used before when we used to show the new device / no history screen after the user was fully signed in.
- Now the ZMUserSession is not created yet when the screen must be displayed.
> Removed unused code for checking if the database exists

- Source/SessionManager/SessionManager+Backup.swift
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
- Source/UnauthenticatedSession/ZMAuthenticationStatus.h
- Source/UnauthenticatedSession/ZMAuthenticationStatus.m
- Tests/Source/SessionManager/SessionManagerTests+Backup.swift
- Tests/Source/Synchronization/Transcoders/MockUserInfoParser.swift
- Tests/Source/UserSession/UnauthenticatedSessionTests.swift
- Tests/Source/UserSession/ZMAuthenticationStatusTests.m
There could be a situation that after logging in the user selects backup of a different account. We should prevent that because the app will not function properly. 
We store the login response inside `ZMAuthenticationStatus`, so we just extract it and pass down to data model for verification.
This simplifies the API from UI side as it needs to just make sure that the user is logged in at this point and pass the URL of the backup file.
> Checking if user imports backup of the account that is logged in

- Source/SessionManager/SessionManager+Backup.swift
- Tests/Source/SessionManager/SessionManagerTests+Backup.swift
The name specified as `Wire-<user_handle>-Backup_Date.ios_wbu`.
> Include user handle in the backup name

- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
comparing CallState.establishedDataChannel always returns false.
Fix compare function
> Fix Callstate compare function not including .establishedDataChannel

- Source/Public/ZMUserSession.h
- Source/SessionManager/SessionManager.swift
- Source/UserSession/ZMUserSession+Push.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/CallKitDelegateTests.swift
The app icon was not showing unread conversation for the first notification you get. Only after second one it shows up.
Unread conversations were counted when notification stream is done fetching. This was done in UI context, but at that point the changes are not yet saved and merged into UI context. So in this situation unread count on UI context is still 0, while on sync context there are unread conversations
Calculate the unread count in sync context and pass the number back to UI for updating the badge.
> Fix: app icon badge number does not show notification

- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
We were not using the correct `ZMUpdateEventSource` value when performing a background fetch (triggered by the OS). As a result of this a user high this an update event for a new message (for example when on bad network) the app might perform a background fetch at a later point where we will fetch the message but we will never present a local notification to the user.
> Fix local push notifications not being shown when performing background fetches

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
In some cases the app would get stuck on the launch screen
This would happen when the selected account was logged out. During the launch sequence the SessionManager would inform its delegate that the current account is logged out before reaching the end of the init method. This caused problems since the delegate (`AppRootViewController`) didn't yet have a reference to the session manager at this point.
Delay the creation of the user session by extracting it from init method into a separate method. An alternative solution would be to include the `SessionManager` in all the delegate methods.
> Extract creation of initial user session into separate method

- Source/UserSession/Blacklist.swift
- Source/UserSession/ZMBlacklistDownloader.m
- Tests/Source/UserSession/ZMBlacklistDownloaderTest.m
- WireSyncEngine.xcodeproj/project.pbxproj
When the blacklist JSON contains the version number formatted as the number and not the string, the Wire app would crash. Moreover, it would continue crashing even if the blacklist file is fixed.
The blacklist parsing was written in ObjC, and it was easy to miss the wrong type passed around.
~Add the type check in Obj-C~ Rewrite the JSON parsing in Swift and fix the problem in 3 lines of code.
I had to remove some tests that imply that in case of failure the download callback has to be called: it is wrong, since the receiver of the download callback is not checking the data passed in it.
Whole thing better be rewritten in Swift.
> Fixed blacklist parsing crash

- Source/Data Model/ZMUser+Consent.swift
- Tests/Source/Data Model/ZMUserConsentTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
NB: this API is only available on staging backend.
Adds the support for getting and setting the user marketing consent state.
Tests would come as the second PR. Was tested against the real backend.
> BE API for user consent

- Source/Calling/CallKitDelegate.swift
- Source/Calling/VoiceChannel.swift
- Source/Calling/VoiceChannelV3.swift
- Source/UserSession/ZMUserSession+Actions.swift
- Tests/Source/Integration/CallingV3Tests.swift
We weren't calling `VoiceChannel.ignore()` for dismissing incoming calls.
Simplify the `VoiceChannel`interface by letting `VoiceChannel.leave()` handle both ignoring an incoming call and leaving an ongoing call.
> Remove VoiceChannel.ignore()

- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallStateObserverTests.swift
* Do not unarchive silenced conversations when call is incoming.
> Do not unarchive silenced conversations when call is incoming

- Source/Calling/VoiceChannelV3.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
When user joins the call, it's not clear if the ongoing call is video or not. Old behavior was that the video was turned on per default, which can confuse the user.
Another undesired behavior was that when user joined from the CallKit, the app was sending the empty video stream.
We set video disabled when joining the call, if we are joining the ongoing call, same goes for the CallKit case.
> Join call without video on, CallKit: default no video

- Source/Synchronization/Strategies/CallingRequestStrategy.swift
Calling message weren't delivered while app is in background in some cases.
Calling messages weren't being sent on the voip session, which means they are sent on the background session.
Mark calling messages to be sent on the voip session.
> Use voip session for calling messages

- Source/Notifications/Push notifications/PushNotificationCategory.swift
Localization is broken for push notification actions.
Localization strings are build using helper method which was missing a `.`.
Add missing `.`
> Add missing . in localizations string builder method

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
It's necessary to re-fetch the group conversations to receive the value of the message expiration timer.
> Hotfix: refetch conversations

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
* Don't update last modified date for update events of type `.messageTimerUpdate`.
> Don't update last modified date for update events of type .messageTimerUpdate

- Source/Data Model/Conversation+MessageDestructionTimeout.swift
- Tests/Source/Integration/ConversationTests+MessageTimer.swift
According to the BE API, to set the timer off we must set it to NULL value.
> Fixed setting the conversation timer to OFF

- Source/Synchronization/Transcoders/ZMConversationTranscoder.swift
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.swift
When a user changes the timer of a conversation, the system message is appended twice. This is because SE is considering the change sent from `ZMTransportSession`. I'm discarding the message if there are changes and if they're made by the current user.
**Problem**: this solution doesn't work with _Off_ - in this case, the change is not ignored because here `.none` is different than `nil`:
https://github.com/wireapp/wire-ios-sync-engine/blob/4bef033b9ee20872d9c69b03c9e6682b550b6d10/Source/Synchronization/Transcoders/ZMConversationTranscoder.swift#L50-L52
> Avoid double timer system messages

- Resources/Base.lproj/Push.strings
- Source/Notifications/Push notifications/Notification Types/LocalNotificationContentType.swift
- Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Localization.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Event.swift
* Fix push strings for message timer update events.
> Fix push strings for message timer update events

- Source/Public/ZMUserSession.h
- Source/Synchronization/Strategies/ProxiedRequestStrategy.swift
- Tests/Source/Synchronization/Strategies/ProxiedRequestStrategyTests.swift
As the UI will start making requests to the YouTube data API, we need to proxy these requests to the backend.
As BE already supports proxying to YouTube, we add the `ProxiedRequestTypeYouTube` with the correct path, and add a test case for this request type.
> ZIOS-10256: Support YouTube API request proxying

- Source/Registration/SharedIdentity/SharedIdentitySessionRequestDetector.swift
- Source/Utility/Pasteboard.swift
- Tests/Source/MockPasteboard.swift
- Tests/Source/Registration/SharedIdentitySessionRequestDetectorTests.swift
* Include isNew field in shared identity detector result.
* Remove Objective-C compatibility (the `DetectorResult` is Swift only and we only use this class from Swift anyways).
> Include isNew field in shared identity detector result

- Source/SessionManager/SessionManagerURLHandler.swift
- Source/SessionManager/SessionManagerURLHandlerError.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Before this PR, we were dismissing the URL action if the callback was not valid. This means that when the users were redirected to the app from a seemingly valid URL, we would not show an alert to tell them something went wrong. 
This is a problem for troubleshooting issues, as we would have no context.
When decoding the `URLAction`, we return a company login error when the company login success could not be processed.
The error codes were borrowed from actual error codes from Apple to make sure we avoid conflicts, and are as follows:
| Wire | Apple Equivalent | Raw Value |
|------|------------------|-----------|
| SessionManagerURLHandlerError.missingRequiredParameter | CarbonCore.missingRequiredParameterErr | -2063 |
| SessionManagerURLHandlerError.invalidCookie | Security. …
> Do not fail silently when SSO success URL callback is not valid

- Source/Synchronization/Strategies/PushTokenStrategy.swift
- Source/UserSession/ZMUserSession+Push.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/CallKitDelegateTests.swift
- Tests/Source/Synchronization/Strategies/PushTokenStrategyTests.swift
- Tests/Source/UserSession/ZMUserSessionTests.m
The push token was not registered during fresh login and it was not possible to recover by resetting the push token from Settings.
We were getting the push token before user client was registered and since we could not save it anywhere it was discarded. Trying to reset token from UI would also fail because it expected to have a token on user client.
When client is registered during login we register push token again which will trigger the request to register it with backend. When validating push token we also try to register it if it's not there yet.
> Fix push token registration

- WireSyncEngine.xcodeproj/xcshareddata/xcschemes/WireSyncEngine.xcscheme
When running tests the console would not contain any network calls.
After moving to new logging system we were muting the output of os_log with an environment variable. This was a leftover from a bug in Xcode 8 that would print enormous amount of information to the console.
> Enabled logging

- Source/Calling/WireCallCenterV3.swift
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
The web socket was misbehaving during calls preventing call events to be processed.
The web socket will fail if the app is in the background and the user is not connected to the active call since sockets will eventually close in the background. VoIP sockets are not working since iOS 10.
Don't allow the web socket to be open unless the user is participating in the call.
> Only open websocket in the background when a call is active

- Source/Calling/CallKitDelegate.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationLocalizationTests.swift
Sometimes it could happen that a user receives an incoming call via CallKit, but the caller name is a cryptic identification string.
This happens in situations when the conversation in which the call is being made is unknown to the client. There already exists localisation measures to deal with missing caller/conversation names, however this logic is never reached. It depends on knowing the `conversationType`, which unfortunately is indeterminate.
Provide a fallback string for CallKit in the case that no other suitable string was found. This fallback is "Someone calling in a conversation".
> Provide a fallback for localized caller name

- Source/Calling/AVSWrapper.swift
`wcall_init` was called every time an account was loaded
static flag `isInitialized` wasn't set
Wrap `wcall_init` in a static function closure which is only executed once.
> Fix wcall_init being called multiple times

- Source/Calling/WireCallCenterV3.swift
- Source/Notifications/Push notifications/LocalNotificationDispatcher+Calling.swift
- Source/Notifications/Push notifications/Notification Types/ZMLocalNotification+Calling.swift
The web client sends `WCALL_REASON_REJECTED` call termination reason messages when the user rejects the call on one client so that other clients stop ringing. 
As discussed with @typfel, while we are not going to handle this case yet, we don't want it to appear as an unknown error.
> Add call rejected elsewhere end reason

- Source/Calling/CallKitDelegate.swift
- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/MessagingTest.h
- Tests/Source/MessagingTest.m
Answering a CallKit call in an unknown conversation fails immediately.
When the call is answered via the CallKit screen, the `join` method is called on the conversation's `VoiceChannel`. This voice channel object is optional and is computed, however it depends on the `conversationType`, which is undetermined for an unknown conversation. Consequently, the call fails.
We cannot simply fetch the conversation because downstream syncing has been disabled in the background. Instead, we can prevent the CallKit call from appearing, and instead alert the user of the incoming call via APNS. This approach forces the user to open the app, which also gives them the opportunity to see who is calling them (since the CallKit screen would have no information about the caller whatsoever).
> Don't use CallKit for unknown conversations

- Source/UserSession/CallEventStatus.swift
- Tests/Source/UserSession/CallEventStatusTests.swift
The app would still get suspended while processing call events in some cases.
If `finishedProcessingCallEvent` was called before `waitForCallEventProcessingToComplete` we would not wait for the timeout timer to finish.
Check if we have a timer running in `waitForCallEventProcessingToComplete`.
> Fix race condition while waiting for call events

- Resources/Base.lproj/Push.strings
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification.swift
- Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Configuration.swift
- Source/Notifications/Push notifications/Notification Types/NotificationAction.swift
- Source/Notifications/Push notifications/Notification Types/PushNotificationCategory.swift
- Source/UserSession/ZMUserSession+Actions.swift
- Source/UserSession/ZMUserSession+Push.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForTests_CallState.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
- Tests/Source/UserSession/ZMUserSessionTests+PushNotifications.swift
The mute action should be displayed for the non-team users only. Team users must see no action.
> Allow mute action for notification for non-team users

- Source/Synchronization/ZMOperatonLoop+Background.swift
- Source/UserSession/CallEventStatus.swift
App would crash with 
```
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSCFSet: 0x283d55dd0> was mutated while being enumerated.'
```
in `unreadConversationCountInContext:`
This is indicating the we are executing a count request from the wrong thread. Looking at the stack trace we confirm that it indeed executing the count request on the sync managed object context from the main thread. The stack trace begins from a timer which was newly added to handle processing of call events.
Switch back to sync thread in the completion handler.
> Fix completion handler not being executed on the SE moc

- Source/Calling/AVSWrapper.swift
- Source/Calling/WireCallCenterV3+Events.swift
Call UI wouldn't dismiss when an outgoing call times out.
We were always expecting a userId in the `call closed` handler which we don't get when a call times out.
Make `userId` optional.
> We should not expect to always get a userId in the close call handler

- Tests/Source/E2EE/ConversationTests+OTR.m
Fixed tests due to new changes about assets sending on slow networks - see https://github.com/wireapp/wire-ios-data-model/pull/547 for more info
> Fixed tests, because OTR assets can expire with new changes

- Source/Calling/AVSWrapper.swift
- Source/Calling/CallKitDelegate.swift
- Source/Synchronization/Strategies/CallingRequestStrategy.swift
Sometimes users see the missed calls from year 2067.
It seems like we are using the double timestamp (unix_time * 2) somewhere. I can imagine that we have the code where we already have the correct timestamp, and we are adding the offset to it again.
1. We receive the call message
2. CallingRequestStrategy is creating the CallEvent with: 
` currentTimestamp = Date().addingTimeInterval(serverTimeDelta)`
`serverTimestamp = eventTimestamp` where 
`eventTimestamp = value of ”time” from ZMUpdateEvent payload`
3. AVSWrapper is forwarding to the AVS 
```
  let currentTime = UInt32(callEvent.currentTimestamp.timeIntervalSince1970)
let serverTime = UInt32(callEvent.serverTimestamp.timeIntervalSince1970)  -> wcall_recv_msg(…., currentTime, serverTime, …) 
```
The signature of wcall_recv_msg is:
``` …
```
> Added logging to locate the wrong timestamp error

- Source/SessionManager/BackendEnvironmentProvider+Cookie.swift
- Source/SessionManager/SessionFactories.swift
- Source/SessionManager/SessionManager.swift
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/UserSession/UnauthenticatedSessionTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Moved the isAuthenticated check that depends on the backend URL to `BackendEnvironmentProvider `. Seems to be cleaner solution, but in the end just swapping 2 arguments.
> Move isAuthenticated to BackendEnvironmentProvider

- README.md
Since you no longer have a .circleci/config.yml, I updated the build badge to use the Azure Pipelines build. Not sure if you want to scope this to a particular branch, but I scoped it to `develop`.
> Replace build badge with Azure Pipelines build

- Source/E2EE/ZMUserSession+OTR.m
- Source/Public/ZMUserSession+OTR.h
- Source/Synchronization/Strategies/UserClientRequestFactory.swift
- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
- Source/UserSession/ClientUpdateStatus.swift
- Source/UserSession/ZMClientRegistrationStatus.m
- Tests/Source/E2EE/ConversationTests+OTR.m
- Tests/Source/Integration/ClientManagementTests.m
- Tests/Source/Integration/LoginFlowTests.m
- Tests/Source/UserSession/ClientUpdateStatusTests.swift
- Tests/Source/UserSession/ZMClientRegistrationStatusTests.m
Some necessary changes in order to allow SSO to work:
- Do not require adding email when signing in first time. Before we needed to add email in order to register the first client.
- Change the way we delete the clients, try without credentials first, and ask for login/password in case of an error.
Accompanying UI PR is also coming.
> SSO login: do not require email and password for device management

- Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
- Tests/Source/Integration/ConnectionTests.m
We have received user complaints about missing messages. The notification alert would be visible in lock screen, but the message would be missing.
We could not reproduce the issue, but looking at crash logs when this happens we see that it crashes because of locked database file after delayed save. There is no good reason to have a delayed save when processing events because we do work in reasonably sized batches. 
Switch to regular save.
> Save immediately after processing events

- Tests/Source/SessionManager/SessionManagerTests.swift
`testThatSessionManagerSetsUpAPNSEnvironmentOnLaunch` test seems to be crashing test suite lately. For no good reason there is a force-unwrap that depends on Integration test SessionManager to be created.
Use mock environment directly
> Fix flaky test

- Tests/Source/Utility/BackendEnvironment+mock.swift
- Tests/iOS Test Host/Test-Host-Info.plist
When looking at logs of failing tests on SyncEngine there were some errors from App Transport Security about invalid certificate. We currently use https://example.com as backend in tests and at the moment a request is made to fetch client blacklist in tests (https://github.com/wireapp/ios-architecture/issues/53). It seems that example.com certificate has expired today and request is failing.
It's not clear why tests would crash in this situation and on local machine I could not reproduce this. It does seem however that it's caused by not being able to fetch blacklist. When using non-secure example.com we see tests fail instead of crash.
Use non-secure example.com. A key enabling insecure loads was added to info.plist. Use production endpoint for blacklist fetching. Try to refactor code to …
> Updated mock environment to not use HTTPS endpoint

- Source/SessionManager/SessionManager.swift
After https://github.com/wireapp/wire-ios/pull/2970 we have noticed that app stays in syncing mode until the app is force-quit.
From logs it seems that background tasks are not created when processing.
If some of the notifications processing expire, we should resume `BackgroundActivityFactory` after coming to foreground. Otherwise no background tasks will be created and we will be stuck.
> Possible fix for syncing issue

- Source/Synchronization/Transcoders/ZMConversationTranscoder.swift
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.swift
Read receipt system message would appear twice when you toggle the read receipt in a group.
The receipt mode update event will appear twice, first as the response from the request to change the setting and later from the notification stream.
Discard update receipt mode events when the change has already been applied.
> Don't insert read receipt system messages twice

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Source/Synchronization/Transcoders/ZMConversationTranscoder.swift
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.swift
We still had issues with duplicate `receipt-mode` events if toggled back and forth.
Filtering out events that doesn't change the value only works the duplicated events come in one by one.
Verify the events have newer timestamp than previously processed events.
> More robust check against duplicate events

- Source/Data Model/NSManagedObjectContext+LastNotificationID.swift
- Source/UserSession/CallEventStatus.swift
- Source/UserSession/PushNotificationStatus.swift
Looking at logs we noticed this situation:
1. User receives calling message. Background tasks get created and destroyed correctly
2. User receives another calling message. Background tasks get created but never finished
3. Push completion handler for calling message no.2 would never get called and the task would expire eventually.
When we receive a calling message we start a 2s timer to make sure all the things inside AVS are initialized. For unknown reason the timer would fire once, but not the second time it was created.
NSTimer works by scheduling things in run loop and it's not obvious what happens when it is used on background queue. In addition all this happens while app is running in background. The solution was to replace NSTimer with `ZMTimer` which is a wrapper around GCD timer …
> Background task would not be finished after receiving call messages

- Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
Read receipt events would not be processed after coming back online.
When processing a batch of events we would first process all the `message-add` events and then continue with all the `conversation-update` events. This results in the read receipt status for a conversations being out of sync while processing the message events since the conversation events (read receipt events) haven't been applied yet.
Let all event consumers process an event before continuing to process the next event.
> Process each event completely before processing the next one

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
We need to slow sync group conversations and the self user read receipt setting after upgrading to a version which supports read receipts. This fixes the edge case were the read receipt setting is turned on in a conversation before the user has had the chance to upgrade Wire.
> Add a hotfix for syncing read receipts setting after upgrading

- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Events.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Event.swift
When team member starts a one-to-one conversation the other side would see a "<Name> created a group conversation".
Team one-to-one conversation are group conversation under the hood so they will generate `conversation.create` events.
Add an additional check to verify that the new conversation is actually a group conversation.
> Don't show group created push for team one-to-one conversations

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Tests/Source/Synchronization/ZMHotFixDirectoryTests.swift
When we need to re-fetch group conversations after upgrading it can need quite a lot of requests.
Exclude groups which you are no longer a member of.
> Only refetch conversations you are still a member of

- Source/UserSession/ZMUserSession+Actions.swift
Background task would not finish if read
Not taking new .read state into account
see https://github.com/wireapp/wire-ios-request-strategy/pull/98
> Fix not finishing background task if read

- Source/UserSession/ZMUserSession+Actions.swift
- Tests/Source/UserSession/ZMUserSessionTests+PushNotifications.swift
Read receipts were not sent after replying and adding a like to a notification.
I've added the logic to send them if needed.
> ZIOS-11019: Added read receipts when replying and adding like to a notification

- Source/SessionManager/SessionManager+Push.swift
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Source/UserSession/PushNotificationStatus.swift
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
- Tests/Source/Synchronization/ZMOperationLoopTests.m
- Tests/Source/UserSession/PushNotificationStatusTests.swift
We have noticed that when a user receives multiple push notifications in one go (e.g. coming back online) the background tasks would not get finished correctly.
PushKit expects us to call completion handler when we are done processing push payload. In our case we call this when notification stream has been downloaded and all events were processed. 
When there are multiple pushes coming in one go we get all the needed information by fetching notification stream only once. To make sure we don't miss any events we keep track of what we received from pushes and what was downloaded from notification stream inside `PushNotificationStatus`. The logic was not working correctly because we would save the last notification ID AFTER we do calculations of what events were fetched. This caused a bug …
> Fix notifications background processing

- Source/UserSession/ZMUserSession+Push.swift
Added extension inside `ZMUserSession+Push` for `UNNotificationContent` in order to provide logs just with the information needed for debugging.
> ZIOS-11130: Added UNNotificationContent extension to redact content info

- Source/Registration/Company/CompanyLoginErrorCode.swift
- Source/Registration/Company/CompanyLoginRequester.swift
- Source/SessionManager/SessionManagerURLHandler.swift
- Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
We want to be able to parse the SSO code for company login from a link the user clicks. See https://github.com/wireapp/ios-architecture/issues/64 for detailed breakdown.
In the UI, the app delegate calls the `SessionManagerURLHandler` to parse the received URL. We updated it to support the `start-sso` host and parsing for the UUID. We added two actions that the URL can cause: starting the SSO flow or warning the user that the link is invalid.
This PR will be merged to the feature branch for this project.
> ZIOS-11162: Implement SSO link parsing

- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerURLHandler.swift
- Source/UserSession/PreLoginAuthenticationNotification.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
We want to be able to start the SSO flow when the user taps a special link. The detailed breakdown can be found at https://github.com/wireapp/ios-architecture/issues/64.
In this PR, we introduce the logic to notify the UI that an SSO login code has been clicked and that we should perform the necessary operations to start the flow.
We add a `companyLoginCodeDidBecomeAvailable` event to the authentication status notifications. When the user taps the link and the UI validated the state (see https://github.com/wireapp/wire-ios/pull/3157), we send the notification with the code from the link to the session manager, who will then start the authentication flow.
To start the flow, it logs out if necessary, and calls the `sessionManagerWillLogout` method with an error containing the SSO code under …
> Handle valid SSO link clicks in session manager

- Source/Registration/Company/CompanyLoginErrorCode.swift
- Source/Registration/Company/CompanyLoginRequester.swift
- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerURLHandler.swift
- Source/UserSession/PreLoginAuthenticationNotification.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
We want to be able to start the SSO flow when the user taps a special link. The detailed breakdown can be found at https://github.com/wireapp/ios-architecture/issues/64.
This PR holds all the approved changes made for this feature.
> [Feature] SSO Links

- Source/SessionManager/SessionManager.swift
When the user tried to log in for the second time, they got stuck in an infinite spinner.
In the add account method, we were checking if there was an unauthenticated session to skip the method that fails if there is no active session (because we don't need to tear it down if it doesn't exist) and start the authentication flow directly.
But after you log in for the first time, we keep the unauthenticated session, which means the next time you try to add an account, we're gonna skip the tear down of the active session, which caused the unauthenticated session to try to update the email address of the current account instead of logging in.
Check if there is no active session to skip the active session tear down.
We will need to do a patch update of 227.0, because we don't want to include the …
> ZIOS-11185: Fix logging in with a second account

- Source/Registration/Company/CompanyLoginRequester.swift
- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerURLHandler.swift
- Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
If the user launched the app from scratch after they signed in, tapping an SSO link has no effect.
The handling of the link assumed that there was an unauthenticated session, which isn't always the case (for ex, if the user launches the app and never started the login flow).
- Force-create an unauthenticated session when the SSO link is tapped.
- Do not cache the SSO team lookup results (in case the team gets deactivated later).
> ZIOS-11207: Fix unresponsive SSO link

- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerURLHandler.swift
When launching the app from scratch with an SSO link, the flow would appear briefly and disappear after a few seconds if there is already an account logged in.
When the app launches, we try to select the first available account. This causes a race condition with the URL handling:
- we launch the app and start asynchronously loading the resources on disk
- we handle the URL synchronously and tell the app state controller to go unauthenticated and the SSO flow starts
- the asynchronous loading finishes and tells the app state controller to go authenticated
- the SSO flow is dismissed and the conversation list is displayed
Do not select the initial account if the URL action at launch causes a logout action.
> ZIOS-11190: Fix dismissing SSO flow if the user is already logged in

- Source/Synchronization/ZMOperationLoop.m
- Tests/Source/Synchronization/ZMOperationLoopTests.m
Looking at real-live logs after #968 we have noticed that sometimes the background task introduced there is not ended which causes the app to stay in background longer.
There is this curious extra notification that we try to do when dispatch group on sync MOC is empty. It seems in some cases this never gets run. This needs further debugging, but since the dispatch group is only useful in tests it's quite low priority.
Remove extra notification and code to wait until group is empty. There is also no need for the extra background task because we should have either delayed save or next request happening at that point already.
> Make sure there is an active background task

- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
Sometimes, the session manager recreates user sessions. However, the authentication coordinator in the UI sets up observers on the session to detect events. Thus, we need a mechanism to detect new unauthenticated sessions so that we can recreate these observers.
> ZIOS-11250: Add observation mechanism for new unauthenticated sessions

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
- Tests/Source/Synchronization/ZMHotFixTests.m
- Tests/Source/Synchronization/ZMHotFixTests.swift
When upgrading from 3.26 to 3.27, some users did not have the `managed_by` flag set in their self profile. It caused an issue with identifying their level of permissions to edit their profile picture and name.
Add a hotfix patch to refetch the self user properties when updating the app.
> Hotfix path: refetch the self user properties after update

- Source/Synchronization/ZMHotFixDirectory+Swift.swift
- Source/Synchronization/ZMHotFixDirectory.m
- Tests/Source/Synchronization/ZMHotFixTests.swift
We need to re-download the team members after the `createdBy` and `createdAt` fields were introduced.
> Add hotfix for re-downloading team members

- Source/Calling/CallKitDelegate.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
Support for AVS using vanilla WebRTC. This has changed the semantics of `.establishedDataChannel` and  `.established`:
Previously `.establishedDataChannel` always happened before `.established`, that's no longer true so we now also need to report Callkit calls as connected on `.established`.
> Don't rely on order of .established & .establishedDataChannel

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
The initial sync on a large account takes a long time to finish.
The profiling report for a large account shows that a significant amount of time is spent in core data's save method, which is triggered when inserting a conversation.
Remove a delayed save after inserting a new conversation. This save should not be necessary since we enqueue a save after the request response has been processed.
> Reduce unnecessary saving during the initial sync

- Source/Synchronization/ApplicationStatusDirectory.swift
- Source/Synchronization/Strategies/TeamSyncRequestStrategy.swift
- Source/Synchronization/Transcoders/ZMConnectionTranscoder.m
- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Source/Synchronization/Transcoders/ZMLastUpdateEventIDTranscoder.m
- Source/Synchronization/Transcoders/ZMSelfStrategy.m
- Source/Synchronization/Transcoders/ZMUserTranscoder.m
- Tests/Source/Synchronization/ZMHotFixTests.m
It's been observed that the notification stream is fetched unnecessarily during the initial sync. Since this fetch doesn't include the `since` query parameter it will contain "old" events which are a wasted effort to consume.
When logging in into an account the user creates a new client, which will cause the backend to send a push notice prompting us to update the `PushNotificationStatus`. This in turn causes the the `ZMMissingUpdateEventsTranscoder` to create a request to fetch notification stream, which will not include the `since` parameter because it is only be persisted after the sync is finished. Doing a `/notifications` request without the `since` parameter will return all events the backend still has stored.
Don't allow fetching the APNS notifications while we are syncing. 
NOTE: …
> Don't allow notification fetching from APNS during syncing

- Source/DeepLink/DeepLinkError.swift
- Source/DeepLink/URL+DeepLink.swift
- Source/SessionManager/SessionManagerURLHandler.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Supporting the URL scheme type for opening a user profile or a conversation.
Modify `sessionManagerShouldExecuteURLAction` of protocol `SessionManagerURLHandlerDelegate` to return a flag that the `URLAction` is executed successfully or not.
> Feature: Go to a specific user profile when clicking on a link outside/inside the app

- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
Follow up on https://github.com/wireapp/wire-ios-sync-engine/pull/986
We were still performing `/notifications` requests during sync
`isFetchingStreamForAPNS` was not using the `notificationFetchStatus` logic.
Query the application status for the `notificationFetchStatus`
> Notification fetching follow up

- Source/SessionManager/SessionManager+Push.swift
- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerURLHandler.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
Add a new `func showUserProfile(user: UserType)` to `ShowContentDelegate`.
~~For `ShowContentDelegate.showConversation` method, change the argument `session` to optional to allow the showConversation in current session.~~
Remove the return of `sessionManagerShouldExecuteURLAction`
> Add show user profile method to ShowContentDelegate

- Source/SessionManager/SessionManagerURLHandler.swift
- Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
Change the URLAction to .warnInvalidDeepLink when the user/convsersation ID is not found in a user session.
> Fix: When the user/convsersation ID is not found in a user session, change URLAction to warning

- Source/SessionManager/SessionManager+Push.swift
- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerURLHandler.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
- Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
Create a new enum value `.connectToUser(id: UUID)` when the user opens a deep link with a user id of an unconnected user.
Update the protocols for the connection request UI actions.
> add new enums and protocol methods

- Source/SessionManager/SessionManager+Push.swift
- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerURLHandler.swift
- Source/UserSession/Search/SearchDirectory.swift
- Source/UserSession/Search/SearchResult.swift
- Source/UserSession/Search/SearchTask.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
- Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
- Tests/Source/UserSession/SearchTaskTests.swift
Add `lookup(userId: UUID) -> SearchTask` to the `SearchDirectory`. This method fetches a user by UUID and returns the results in the form of a `SearchUser`.
> Lookup user by UUID

- Source/UserSession/NotificationInContext+UserSession.swift
- Source/UserSession/SyncStatus.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/UserSession/SyncStatusTests.swift
- Tests/Source/UserSession/ZMUserSessionTests+Syncing.swift
The certain elements of the UI (group settings) would be disabled when they shouldn't.
The UI elements were waiting for the initial sync to complete which now never happens since we've split up the syncing into slow sync and quick sync.
Set `hasCompletedInitialSync` to `YES` when initialising the `ZMUserSession` if there's no need to perform a slow sync.
> Fix initial sync-is-completed state handling

- Source/Synchronization/ZMHotFixDirectory.m
Since backend introduced the `email` for team users we need to re-fetch all users in the team.
> Re-fetch team users after email field was introduced

- Source/Synchronization/Strategies/TypingStrategy.swift
- Tests/Source/Synchronization/Strategies/TypingStrategyTests.swift
If a user that is currently typing gets removed from conversation the typing indicator stays visible.
We would only expire the indicator after 60s of inactivity, but ignore the fact that user already left the conversation.
Listen for `member-leave` event and reset the typing status.
> Fix: typing indicator still visible when user is removed from conversation

- Source/Public/ZMUserSession.h
- Source/UserSession/ZMUserSession.m
- Tests/Source/UserSession/ZMUserSessionTests.m
Add `enqueueDelayedChanges` to `ZMUserSession`, which the UI can use when it needs to do many changes in a tight loop. The enqueued changes will then be coalesced into one save operation.
> Add method enqueueDelayedChanges for performing changes with a delayed save

- Source/UserSession/CallStateObserver.swift
- Tests/Source/Calling/CallStateObserverTests.swift
If CallKit is enabled you don't receive any notifications for muted conversations.
We don't forward call events to the notification dispatcher if we have CallKit enabled.
We should make an exception and forward call events if the conversation is muted.
> Forward call event to notification dispatcher if the conversation is muted

- Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Configuration.swift
When user disables message contents preview in notifications we still allow replying from notification action.
We were falling back to a default action list for messages (reply) instead of handling it correctly.
Add a case when content is hidden.
> Not showing notification actions when content is hidden

- Source/Synchronization/Strategies/CallingRequestStrategy.swift
- Tests/Source/Synchronization/Strategies/CallingRequestStrategyTests.swift
When requesting call config we can receive responses that are of no interest for AVS - e.g. clients missing (status code 412). There is no need to forward those, only successful ones are useful.
Filter all responses and forward only those with status code 200.
> Forwarding only successful responses to AVS

- Source/Calling/CallKitDelegate.swift
- Source/Calling/VoiceChannel.swift
- Source/Calling/VoiceChannelV3.swift
- Source/Calling/WireCallCenterV3.swift
- Source/UserSession/ZMUserSession+Actions.swift
There are situations when you would want to join another call while there is an ongoing call already. It was not working and after ending the current call you would not be able to join another call.
There is a race condition because ending call is asynchronous. We would immediately try to start a call  after finishing the previous one, but this needs to happen in a completion handler.
Add a completion handler to the end call method. Also relaxed a bit what is considered an active call - added all states where CallKit would be involved.
> Fix: allow joining other call when you already have an active call

- Source/SessionManager/SessionManager.swift
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
If you get logged out when switching accounts, pressing the log out button doesn't work.
We attempt to log out the selected account, according to the account manager, when you press the log out button but that's actually the account you were switching from since the switch never completed.
Expose which account an unauthenticated session is associated with so that the UI can pick the correct account to log out from.
> Fix logout not working on non active account

- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
Tests are unstable because downloading the blacklist fails
We are attempting download the production blacklist in the tests which is not guaranteed to always be stable.
Disable the the blacklist downloading if `blacklistDownloadInterval` is `< 0` and pass `-1` in the tests.
One could imagine mocking the blacklist in the tests but that requires quite some re-factoring.
> Don't attempt to download the blacklist in the tests

- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
When removing a device, no alert dialog is shown after entered a short invalid password. The spinner never dismisses. 
The back-end gives a different error response other than invalid password error.
Treat `"bad-request"` response as invalid password response
> Fix: When removing a device, no alert dialog is shown after entered a short invalid password

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/IntegrationTest.h
- Tests/Source/Integration/IntegrationTest.m
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
Add an option for deleting account data when users's authentication is invalidated
I'm introducing `SessionManagerConfiguration` which holds configurable options of the `SessionManager`. This will allow us to add new options in the future without having to change the signature of the `SessionManager` init method.
In this PR I'm adding `deleteAccountOnAuthenticationFailure` which controls if the account data is deleted in addition to the cookie when a user session authentication gets invalidated.
While adding tests for the new authentication behaviour I noticed that the integration tests where using two separate cookie storages: `ztest.example.com` and `example.com`.  I fixed this by always creating the cookie storage from the `MockEnvironment`.
> Add option for deleting account data when authentication is invalidated

- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
Renamed session manager flags, following https://github.com/wireapp/wire-ios-build-configuration/pull/13
> Fix: renamed session manager flags

- Source/Synchronization/EventProcessingTracker.swift
- Tests/Source/Synchronization/EventProcessingTrackerTests.swift
App crashes when calling `EventProcessingTracker.debugDescription`
Getting `eventAttributes` from the queue other than `isolationQueue` may cause an access violation. 
Get `persistedAttributes` from `isolationQueue`.
> Fix: app crash when calling EventProcessingTracker.debugDescription

- Source/Calling/CallKitDelegate.swift
CallKit button for opening the Wire app was missing its icon.
`logo` image doesn't exist anymore
Wire logo has been re-added as `wire-logo-letter`
> Fix missing CallKit Wire button icon

- Source/Calling/AVSCallMember.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
Call participants don't appear in group calls
Since AVS 5.1 the call participants are received as JSON which fails to decode.
Fix call participant JSON decoding by correcting typo: `vrrecv` -> `vrecv`
> Fix call participants not appearing in group calls

- Source/Calling/CallKitDelegate.swift
- Source/Calling/FlowManager.swift
- Source/Calling/MediaManager.swift
- Source/Public/ZMUserSession.h
- Source/SessionManager/SessionFactories.swift
- Source/SessionManager/SessionManager.swift
- Source/Synchronization/ZMOperationLoop.h
- Source/Synchronization/ZMSyncStrategy.h
- Source/UserSession/ZMUserSession+Internal.h
- Source/UserSession/ZMUserSession+Private.h
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/FlowManagerTests.swift
- Tests/Source/Calling/MockMediaManager.swift
- Tests/Source/Integration/IntegrationTest.h
- Tests/Source/Integration/IntegrationTest.m
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/UserSession/ZMUserSessionTestsBase.m
- WireSyncEngine.xcodeproj/project.pbxproj
Introduce MediaManagerType for easier mocking of the AVSMediaManager
This is done in a effort to remove all usage of OCMock in the integration tests so that we can move them completely to Swift.
> Introduce MediaManagerType for easier mocking of the AVSMediaManager

- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Events.swift
- Source/Synchronization/Strategies/TeamDownloadRequestStrategy+Events.swift
- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Tests/Source/Synchronization/Strategies/TeamDownloadRequestStrategy+EventsTests.swift
Stop processing the `team.conversation-delete event` since it has been replaced by the `conversation.delete` event in all cases.
> [Fix] Stop processing the team.conversation-delete event

- Source/Calling/SystemMessageCallObserver.swift
- Tests/Source/Calling/CallSystemMessageGeneratorTests.swift
If you have two devices A & B and you make an outgoing call from device A, it would get reported as a missed call on device B. In addition to the missed call system message this would also trigger a push notification.
It doesn't make sense to miss a call from yourself so we should instead report this as a "performed call".
> [Fix] Don't report incoming calls from yourself as "missed"

- Source/SessionManager/SessionManager.swift
- Source/UserSession/PostLoginAuthenticationNotification.swift
- Source/UserSession/ZMUserSession+Authentication.swift
- Tests/Source/E2EE/UserClientRequestStrategyTests.swift
- Tests/Source/UserSession/ZMUserSessionTests+Authentication.swift
- Tests/Source/UserSession/ZMUserSessionTestsBase.h
- Tests/Source/UserSession/ZMUserSessionTestsBase.m
- WireSyncEngine.xcodeproj/project.pbxproj
Add `logout(credentials:, completion:)` to the `ZMUserSession` which logs a user out  by deleting the self client. Deleting a client invalidates any cookie associated with the client.
> Add method for logging out from a user session

- Source/SessionManager/SessionManager+Authentication.swift
- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
When re-authenticate on reboot is enabled:
- User is logged out every time the app goes into the foreground
- User is logged out if no previous boot time was stored
This was due the clock can't be guaranteed to be the same on the milliseconds between runs
Value wasn't unwrapped so default comparison behaviour was applied
Tolerate clock shifts up to 1 seconds (maybe needs to be higher?)
Unwrap the value before performing the comparison.
> Fix: re-authenticate on reboot triggering too often

- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
1. Cookie wasn't deleted when logged the user out
2. SessionManager would attempt to start the user session again after logging the user out
3. On second relaunch of the app data would be deleted
1. `ZMUserSession ` doesn't exist when we logout the user on launch
2. SessionManager tries to launch the `ZMUserSession` in `SessionManager.start()`
3.  If cookie is deleted in combination with `wipeOnCookieInvalid = true` we get this behaviour. 
1. Delete the cookie directly without going through the `ZMUserSession`
2. Move the logout on reboot into the SessionManager.start() code path
3. Don't update the systemBootTime until after we've re-authenticated.
> Fix issues with authenticate on reboot

- Source/UserSession/ZMUserSession+Authentication.swift
- Tests/Source/UserSession/ZMUserSessionTests+Authentication.swift
SSO users would get an error when trying to logout
SSO user's don't have a password but still included the `password` field in the DELETE request which the backend didn't accept.
Don't include an empty password in the DELETE request.
> Fix: logout not working for SSO users

- Source/Synchronization/Strategies/LabelDownstreamRequestStrategy.swift
- Tests/Source/Synchronization/Strategies/LabelDownstreamRequestStrategyTests.swift
Folders you just created would go missing if you put the app into background / foreground
When we create folders we don't this will end up as events in the notification stream. If the put the app into background / foreground this will trigger us to process notification steam which will includes these events if nothing else happened in between.
create folder A
create folder B
create folder C
current state: [A, B, C]
process folder events:
event1 [A]
event2 [A, B]
event3 [A, B, C]
When processing event 1 we will delete folder B and C since they are not included in the update. This should be a problem since they will get added back in event 2 & 3. But this didn't happen because when we process event 2 & 3 we will fetch the existing folder B & C and update them instead because they haven't …
> Fix: incorrectly deleting folders when processing the event stream

- Source/Data Model/Conversation+AccessMode.swift
We would crash the app if you try to create guest link without sufficient permissions. This can happen if you are removed from the conversation while being at the guest settings screen.
We intentionally crash the app if the user doesn't have sufficient permissions
Return an `.invalidOperation` error instead of crashing.
> Fix: don't crash when modifying guest link without sufficient permissions

- Source/Registration/ContactAddressBook.swift
Catch the exception throw by `enumerateContacts` to study the cause of the crash.
> Fix: catch exception when calling enumerateContacts

- Source/UserSession/UserProfileImageUpdateStatus.swift
Unwrap `operation.downsampleImageData` which the type is `Data!` before access.
> Fix: app crash when calling completedDownsampleOperation

- Source/UserSession/UserProfileImageUpdateStatus.swift
- Source/UserSession/ZMUserSession+ConversationDirectory.swift
Fix the issue that when accessing `ZMUserSession.conversationDirectory`, `managedObjectContext` would be nil if current `ZMUserSession` is deleted.
Needs releases with:
> Fix: app crash when call ZMUserSession.conversationDirectory

- Source/Calling/AVSCallMember.swift
- Source/Calling/CallParticipantSnapshot.swift
- Source/Calling/CallState.swift
- Source/Calling/WireCallCenterV3+Notifications.swift
This PR contains changes to address an AVS related crash.
Since AVS 5.3, we now allow a user to join a group call with more than one device. This means that a call participant is no longer unique by their user id, we must also take their client id into account. Although we already store the client id, there are several places where we still only refer to the user id. This is due to the fact that when we post a `WireCallCenterCallParticipantNotification`, we were sending on the `UUID` referring to the user's remote identifier.
Pass the entire `CallParticipant` through the notification and make `CallParticipant` hashable over the user id and client id.
> [Fix] Call participant notification

- Source/Calling/CallParticipantSnapshot.swift
- Tests/Source/Calling/CallParticipantsSnapshotTests.swift
When the other participant in a one to one call has video enabled, their video is not visible in the call.
In group calls, whenever a participant joins the call we get their client id via the participants changed callback. However this is not the case in one to one calls. As a result, when the other participant enables video, the video state changed callback is invoked (with the client id), and we try to update our internal list of participants (in this case just one). There was a logic error when trying to find the participant instance to update (with the client id and the video state), where we were already expecting the client id to be set. As a result, we didn't update the participant, because we were trying to match the user id and client id.
Refactor the logic used in the video …
> [Fix] No video received in one to one call

- Source/Calling/CallKitDelegate.swift
Calls started from outside the app (Phone app / CallKit interface) would only open the app but no calls would be made.
Given that CallKit is enabled
Each new call (joined or started) is given a handle (`CXHandle`). 
It is simply a way to identify the call. 
When a user starts a Wire call via the Phone app, or through CallKit's interface,
The AppDelegate's `application(_:continue:restorationHandler:)` method is called.
An instance of `NSUserActivity` is passed as parameter and contains the contact (`INPerson`) that the user selected.
This `INPerson` instance has an `INPersonHandle` property that corresponds to the call's handle (`CXHandle`)
Using the handle, we're able to start a call to the intended conversation.
However, the wrong property of the `INPerson` instance was used.
use …
> [Fix] Fails to start calls from outside the app with CallKit

- Source/Data Model/Conversation+Role.swift
- Tests/Source/Data Model/Conversation_RoleTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
This PR provides a method to update the role for a given user in a given conversation. Invoking this method will perform a request to update the backend and then upon successful completion update the local database.
> [Feature] Sync conversation role updates

- Source/UserSession/Search/SearchTask.swift
the search was using the wrong context to get the self user. this was causing a crash.
> fix using wrong context

- Source/Data Model/Conversation+Role.swift
Conversation change notifications were not being fired when we update the participant roles. This led to UI states being out of sync with the local database.
The CoreData context was not being saved after modifying the participant roles.
Invoke a save.
> [Fix] Save context after updating roles

- Source/Synchronization/Transcoders/ZMConversationTranscoder.swift
Fix the crash when receipt event has a nil time stamp.
> Fix: processReceiptModeUpdate has nil lastServerTimestamp

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Source/Synchronization/Transcoders/ZMConversationTranscoder.swift
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.swift
Roles for a conversation should be fetched from a team or the conversation. When we have access to the team metadata (i.e. we are part of the team), we should fetch roles from the team. If not, then from the conversation.
The code was checking if the conversation is in a team, but not if it's our team. If the conversation is in another team, we should fetch the roles from the conversation, as we won't have access to that team.
> Fetch conversation roles for conversations in other teams

- Source/Synchronization/Strategies/VerifyPasswordRequestStrategy.swift
- Source/Synchronization/ZMSyncStrategy.m
- Source/UserSession/ZMUserSession+VerifyPassword.swift
- Tests/Source/Synchronization/Strategies/VerifyPasswordRequestStrategyTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Addition of a new request strategy to verify the account password.
Since there isn't an endpoint to verify the password, It will use the `update password` endpoint (done similarly on Android).
> [Feature] new request strategy to verify password

- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
The legal hold status is not updated in conversations after restoring from backup in the following scenario:
1. User A is put under legal hold
2. Legal hold indicator gets active in conversation C1
3. User A makes a backup
4. User A is removed from legal hold
5. User A restores the backup
Conversation C1 would still indicate that it's under legal hold even though we know it's not since user A was the only participant under legal hold.
When restoring a backup we re-fetch the list of clients belonging to the self user and delete any no longer existing clients. This would delete the legal hold client but not trigger a re-calculation of the legal hold status in the conversations where the self user is a participant.
Delete any no longer existing clients using the `deleteClientAndEndSession()` …
> [Fix] legal hold not being updated in conversations after restoring from backup

- Source/SessionManager/ProcessInfo+SystemBootTime.swift
- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
`systemUptime` isn't updated when iOS system is asleep, which leads to calculating incorrect boot time.
Calculate boot time more accurately using the kernel boot time
> [Fix] wrong system boot time

- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
GIVEN device was rebooted AND logout on reboot is enabled
AND user is logged out (no `selectedAccount`)
WHEN app launches
THEN app is stuck on load screen
if there is no `selectedAccount`, application execution comes to a dead end
continue execution if `selectedAccount` is nil
> [Fix] App stuck on load screen 

- Source/Notifications/Push notifications/Helpers/NotificationUserInfo.swift
- Source/Notifications/Push notifications/Helpers/ZMLocalNotificationSet.swift
- Source/Notifications/Push notifications/LocalNotificationDispatcher+Calling.swift
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification.swift
- Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Localization.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForTests_CallState.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationSetTests.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_ExpiredMessage.swift
This PR is part of an ongoing effort to all public references that leak concrete user objects. See the architecture issues for more info: https://github.com/wireapp/ios-architecture/issues/89
Public exposure of `ZMUser` has been removed from the following cluster of files:
- `NotificationUserInfo.swift`
- `ZMLocalNotification.swift`
- `LocalNotificationType+Localization.swift`
- `LocalNotificationDispatcher+Calling.swift`
I came across a lot of unnecessary public access modifiers, so I've removed those too to harden the SE boundary.
> [Refactor] UserType in Notification Classes

- Source/Public/NSError+ZMUserSession.h
- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerConfiguration.swift
- Source/UserSession/ZMUserSession+VerifyPassword.swift
- Tests/Source/Calling/CallKitDelegateTests.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
Delete the selected account after `n` failed password attempts (only affects appLock)
> [Feature] wipe after failed unlock

- Source/Registration/ContactAddressBook.swift
App crash after adding a catch in  https://github.com/wireapp/wire-ios-sync-engine/pull/1103
Calling `fatal` always crashes
In this case, we should not crash the app when `enumerateContacts` throws. Logging the error instead.
> Log error instead of fatal

- Source/Data Model/Conversation+Participants.swift
- Source/Data Model/Conversation+Role.swift
- Tests/Source/Data Model/Conversation+ParticipantsTests.swift
- Tests/Source/Integration/ConversationTests+LegalHold.swift
- Tests/Source/Integration/ConversationTests+Participants.swift
This PR is part of an ongoing effort to all public references that leak concrete user objects. See the architecture issues for more info: wireapp/ios-architecture#89
Public exposure of ZMUser has been removed from the following cluster of files:
- Conversation+Participants.swift
- Conversation+Role.swift
> [Refactor] UserType in Conversation Classes

- Source/UserSession/ZMUserSession+LegalHold.swift
- Tests/Source/Integration/ZMUserSessionLegalHoldTests.swift
This PR is part of an ongoing effort to all public references that leak concrete user objects. See the architecture issues for more info: wireapp/ios-architecture#89
Public exposure of ZMUser has been removed from the following cluster of files:
LegalHold.swift
> [Refactor] UserType in Legal Hold Classes

- Source/Calling/CallKitDelegate.swift
- Source/Calling/SystemMessageCallObserver.swift
- Source/Calling/VoiceChannel.swift
- Source/Calling/VoiceChannelV3.swift
- Source/Calling/WireCallCenterV3+Notifications.swift
- Source/SessionManager/SessionManager.swift
- Source/UserSession/CallStateObserver.swift
This PR is part of an ongoing effort to remove all concrete user objects from the UI project. See the architecture issues for more info: https://github.com/wireapp/ios-architecture/issues/89.
All public references `ZMUser` have been hidden in the following files:
- `VoiceChannel.swift`
- `VoiceChannelV3.swift`
- `CallKitDelegate.swift`
- `SystemMessageCallObserver.swift`
- `CallStateObserver.swift`
- `WireCallCenterV3+Notifications.swift`
> [Refactor] Hide Concrete Users in Calling Classes

- Source/UserSession/Search/SearchDirectory.swift
- Source/UserSession/Search/SearchResult+AddressBook.swift
- Source/UserSession/Search/SearchResult.swift
- Source/UserSession/Search/SearchTask.swift
- Tests/Source/DatabaseTest.swift
- Tests/Source/DiskDatabaseTest.swift
- Tests/Source/UserSession/SearchDirectoryTests.swift
- Tests/Source/UserSession/SearchResultTests.swift
- Tests/Source/UserSession/SearchTaskTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
In order to convert the `ZMUserSession` to Swift we need to remove any usage of OCMock where it mocks the user session.
---
Refactor search classes and tests to inject the `ZMManagedObjectContextProvider` and `TransportSessionType` instead of the `ZMUserSession`.
> Remove the need for mocking the user session with OCMock (Part 1)

- Source/Data Model/Conversation+Deletion.swift
- Source/Data Model/ZMUser+Consent.swift
- Source/UserSession/CallStateObserver.swift
- Source/UserSession/ZMUserSession+Calling.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/CallKitDelegateTests+Mocking.h
- Tests/Source/Calling/CallKitDelegateTests+Mocking.m
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
- Tests/Source/Data Model/Conversation+DeletionTests.swift
- Tests/Source/Data Model/ZMUserConsentTests.swift
- Tests/Source/DatabaseTest.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherCallingTests.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
In order to convert the ZMUserSession to Swift we need to remove any usage of OCMock where it mocks the user session.
---
Following the strategy we've arrived at in https://github.com/wireapp/wire-ios-sync-engine/pull/1164 I'm removing more usage of the `mockTransportSession`.
> [Refactor]  Remove the need for mocking the user session with OCMock (Part 3)

- Source/SessionManager/AVSLogObserver.swift
- Source/SessionManager/SessionManager.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Move `AVSLogObserver` form UI project and convert it to Swift.
> Fix: move AVSLogObserver from UI project

- Source/UserSession/ZMUserSession+Clients.swift
The device screen shows a spinner which doesn't go away.
Spinner is shown when fetching self clients but it never goes away since the UI never gets notified that clients have been fetched. It doesn't get notified because there's a condition not call the observer if the list of clients is empty.
Always notify the observer, the existing logic got broken when it was translated to Swift https://github.com/wireapp/wire-ios-sync-engine/pull/1159.
> [Fix] Observer not being notified when clients list is empty

- Source/SessionManager/SessionManager+URLActions.swift
- Tests/Source/SessionManager/SessionManagerTests+URLActions.swift
If the app is launched with a deep link action we should show an error dialogue if the user is not logged in.
These actions were delayed to in order to be performed when a user session becomes available.
Throw an error immediately if the user is not authenticated.
> [Fix] Deep link error alert while logged out

- Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
- Source/UserSession/ZMUserSession+Authentication.swift
- Source/UserSession/ZMUserSession.m
- Tests/Source/Calling/CallStateObserverTests.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherCallingTests.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
The `LocalNotificationDispatcher` was canceling notifications and performing a delayed save from its `tearDown` method. This is problematic since: 
- The user session is not in a known state during tear down and causes flakyness in tests.
- This could in theory get triggered when the system is under memory pressure, and we release our background user sessions. That would have the side effect of clearing all notifications from the Notification Center, which doesn't make any sense.
Remove the `tearDown` method and cancel notifications on logout instead.
> [Fix] Cancel notifications on logout instead of on tear down

- Source/SessionManager/SessionManager.swift
The UserSession would be retained after being torn down after we receive a memory pressure warning.
We where iterating over the `backgroundUserSessions` dictionary and modifying it at the same time. This was causing the user session to be retained even though it's been removed from the dictionary.
Extract the list of sessions to tear down into a temporary variable.
> [Fix] User session still being retained after being torn down

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Changed the ZMConversationTranscoder log tag to `event-processing`
- Made the code more readable by renaming users to removedUsers
Needs releases with:
> [Fix] Renamed log tag to event-processing and improved the variable naming

- Cartfile
- Cartfile.resolved
- Source/Calling/AVSCallMember.swift
- Source/Calling/AVSWrapper+Handlers.swift
- Source/Calling/AVSWrapper.swift
- Source/Calling/CallParticipantSnapshot.swift
- Source/Calling/CallState.swift
- Source/Calling/NetworkQuality.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3+Notifications.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/CallParticipantsSnapshotTests.swift
- Tests/Source/Calling/VoiceChannelV3Tests.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
This PR integrates [API changes](https://github.com/wearezeta/avs/blob/master/docs/api/api_changes_5.6.txt) for AVS 5.6
We now get the clientId in more callbacks, which allows us to refactor how we maintain the list of call participants. Currently, we only get the clientId when the video state changes or the list of participants changes. A consequence of this is that any changes to the participants where we only have the userId might update the wrong participant (since a single userId can be shared with different participants). This issue is now resolved with these changes.
> [Refactor] Integrate AVS 5.6

- Source/Calling/AVSWrapper.swift
- Source/Calling/WireCallCenterV3+Events.swift
No system message saying "You called" shows up after calling and hanging up
client id was returning nil and it was not necessary
Removed not necessary handling clientId parameter
> [FIX] Missing "You called" message after hanging up

- Source/Calling/AVSWrapper.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
Some test after the last merge are failing
Not updating tests before last merge
Remove not necessary clientId parameter from certain tests
> [Fix]: tests were failing

- Cartfile
- Cartfile.resolved
- Source/Calling/AVSCallMember.swift
- Source/Calling/AVSWrapper+Handlers.swift
- Source/Calling/AVSWrapper.swift
- Source/Calling/CallParticipantSnapshot.swift
- Source/Calling/CallState.swift
- Source/Calling/NetworkQuality.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3+Notifications.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/CallParticipantsSnapshotTests.swift
- Tests/Source/Calling/VoiceChannelV3Tests.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
There were some regressions introduced after integrating AVS 5.6. Some of these regressions can only be fixed with new changes on the AVS side. These changes are included as part of AVS 6, however AVS 6 integration is not complete yet.
So that these regressions don't block the next release, it has been decided to rollback to the previous AVS version.
> [Chore] Revert to AVS 5.5.6

- Tests/Source/Data Model/ServiceUserTests.swift
UserType requirements changed in https://github.com/wireapp/wire-ios-data-model/pull/933. This PR fixes conformance in the test target.
> [Chore] Fix UserType conformance

- Source/Calling/AVSWrapper+Handlers.swift
- Source/Calling/AVSWrapper.swift
This PR cleans up the AVS handler definitions to provide a bit more information about their types and what they are used for. No logic has changed.
> [Feature] AVS 6: clean up handler definitions

- Source/Calling/AVSCallMember.swift
- Source/Calling/AVSWrapper.swift
- Source/Calling/CallParticipantSnapshot.swift
- Source/Calling/CallState.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/CallParticipantsSnapshotTests.swift
- Tests/Source/Calling/VoiceChannelV3Tests.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
A call participant is identified by both a user id and a client id. Currently the client id of a participant is shared by AVS through certain callbacks. As a result, we often have an incomplete / insufficient data to uniquely identify participants and it leads to the extra complexity of having an optional client id when it should be non optional.
With AVS 6, we are given the client id in more callbacks, which allows us to make the call participants client id non optional. This leads to further refactoring, such as modeling an `AVSClient` as a pair of user id and client id, to represent some device in a call.
The AVS binary is not yet published, therefore the current version of AVS is running in this PR. As a result this may not build or tests may fail.
> [Feature] AVS 6: introduce AVSClient

- Source/Registration/Company/CompanyLoginRequestDetector.swift
- Source/Utility/Pasteboard.swift
- Tests/Source/MockPasteboard.swift
- Tests/Source/Registration/CompanyLoginRequestDetectorTests.swift
SSO code would get detected over and over again on iOS 13.
I suspect that `UIPasteboard.changeCount` behaves differently on iOS 13 
Calculate `isNew` by comparing the SSO string instead.
> [Fix] SSO detection on iOS 13

- Source/Calling/AVSCallMember.swift
- Source/Calling/AVSWrapper+Handlers.swift
- Source/Calling/AVSWrapper.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
A new requirement of AVS is that a list of user clients for a particular conversation must be provided on demand. AVS makes this request through the new `wcall_req_clients_h` handler (aka `Handler.RequestClients`).
When the handler is called, we must determine all clients (except the self client) in the given conversation and return it to AVS in json format. A client (aka `AVSClient`) is simply a user id and client id pair which was introduce in https://github.com/wireapp/wire-ios-sync-engine/pull/1209.
This PR enables json encoding of `AVSClient`, defines the handler and sets up the callbacks.
The AVS binary is not yet published, therefore the current version of AVS is running in this PR. As a result this may not build or tests may fail.
> [Feature] AVS 6: provide a list of clients

- Source/Calling/AVSWrapper.swift
- Source/Calling/CallParticipantSnapshot.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/CallParticipantsSnapshotTests.swift
There are two different flows for handling participant change updates depending whether the call is a group call or not. Group participant changes are communicated together in a json payload, delivered through the  participant change handler. For 1:1 calls, the audio and video states are communicated separately through the audio established and video state changed handlers. 
With the refactoring for AVS 5.6, the first flow (participant change handler) was [opened up also for 1:1 conversations](https://github.com/wireapp/wire-ios-sync-engine/pull/1207/files#diff-695f8fc6ef3bd31aa718582c2abc2c7bL319).
This led to some unwanted [side effects](https://wearezeta.atlassian.net/browse/ZIOS-12718) due to the two different code paths. After some some adjustments on the AVS side to make the …
> [Feature] AVS 6: Use participant change handler for audio / video state updates

- Cartfile
- Cartfile.resolved
- Source/Calling/AVSCallMember.swift
- Source/Calling/AVSWrapper+Handlers.swift
- Source/Calling/AVSWrapper.swift
- Source/Calling/CallParticipantSnapshot.swift
- Source/Calling/CallState.swift
- Source/Calling/NetworkQuality.swift
- Tests/Source/Calling/CallParticipantsSnapshotTests.swift
This PR integrates the following AVS 5.6 changes:
- new network state `problem`
- new audio state `networkProblem`
- changed callback signatures to include the client id
The previous integration of AVS 5.6 (which has been reverted) contained several refactorings which are not included here, because it required some changes only introduced in AVS 6. This implementation solely addresses the API changes from the AVS library.
> [Feature] AVS 5.6

- Source/Data Model/Conversation+Participants.swift
- Tests/Source/Data Model/Conversation+ParticipantsTests.swift
In large teams you'll lazily discover that team users have been deleted by sending them a message, if you try to add them to a group conversation before that it will fail and we should recover by re-fetching the user profiles of the users you tried to add.
> [Feature] Refresh user data when adding a participant to a group fails

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Source/Synchronization/Transcoders/ZMConversationTranscoder.swift
- Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
When typing a message into a conversation that contains a deleted member, we discover they are deleted and remove them from the conversation, but we don't display a system message.
Sending a message to a deleted member will cause the  member to be synced with the backend. This is how we discover if they have been deleted or not. However, existing logic will also cause the conversation to be synced to the backend. The conversation is synced first and as at result it already removes the deleted member, but it does not add the system message. When syncing the deleted member, we append a system message and remove them from all group conversations they belong to, except for the initial conversation because they have already been removed.
We need to sync the potentially deleted member before …
> [Fix] Missing system messages when member deleted

- Source/Calling/AVSWrapper+Handlers.swift
- Source/Calling/AVSWrapper.swift
- Source/Calling/CallCenterSupport.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3.swift
- Source/Synchronization/Strategies/CallingRequestStrategy.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
This PR implements the logic to send an SFT calling message. 
The SFT call begins by setting the conversation type to `conference`. AVS will then invoke the `wcall_sft_req_h` handler (aka `SFTCallMessageSend`). In this handler we need to trigger a PUT request to the given url and passing the given data. After the request is made and the response received, the result is then passed back to AVS through the `wcall_sft_resp` function.
This PR relies on an unpublished AVS binary and therefore will not compile in this PR. Nonetheless, if approved I would merge it to the feature branch and validate it later when possible.
> [Feature] AVS 6: send SFT call message

- Source/Calling/AVSBridging.swift
- Source/Calling/AVSWrapper+Handlers.swift
- Source/Calling/AVSWrapper.swift
AVS 6.0.18 adds the conversation type to the incoming call handler. This will be used later by QA to determine which type of calls they are testing (legacy group calls or SFT conference calls). 
This PR relies on an unpublished AVS binary and therefore will not compile in this PR. Nonetheless, if approved I would merge it to the feature branch and validate it later when possible.
> [Feature] Add conversation type parameter to incoming call handler

- Source/Calling/AVSWrapper.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3.swift
When a client starts an SFT call, AVS will ask for the list of all other clients in the conversation. However, it's possible that the list is out of sync with the backend. 
This can happen if new participants are added to the conversation after the call connects. It can also happen if the self client is unaware of other clients in the conversation. In this case, the backend will report the missing clients when the OTR call message is sent.
Observe changes to the participants for the conversation and recalculate the client list and send it to AVS when needed. Observation only begins once calculate the client list for the first time, and ends when the SFT call is ended. If missing clients were detected from the backend response, then existing logic will trigger a sync of the conversation, …
> [Feature] Inform AVS of client list updates when conversation changes

- Source/Calling/CallCenterSupport.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Synchronization/Strategies/CallingRequestStrategy.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
- Tests/Source/Synchronization/Strategies/CallingRequestStrategyTests.swift
This PR extends the capability of `CallingRequestStrategy` to provide a way to fetch a list of all clients in a given conversation. This method is intended to be used to provide AVS with a client list for use with SFT calls and replaces the previous approach of generating a (potentially out of date) list via the conversation object.
It works by sending an OTR message with an empty payload and zero recipients in a specific conversation. The backend will return a 412 response indicating that the message is missing recipients (as expected). In the payload of the response we will find a list of all missing clients, which will be the list of all clients in the conversation. This list is then passed into a completion handler.
This is a follow up of …
> [Refactor] AVS 6 client discovery

- Source/SessionManager/SessionManagerConfiguration.swift
This PR allows the `callCenterConfiguration` field in `session_manager.json` to be optional. In case the field is missing, the default `WireCallCenterConfiguration` is used.
> [Refactor] Call center configuration

- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
This PR makes use of the `WireCallCenterConfiguration` introduced in https://github.com/wireapp/wire-ios-sync-engine/pull/1238 to conditionally start a conference call.
> [Feature] Conditionally start conference call

- Source/Calling/WireCallCenterConfiguration.swift
- Source/SessionManager/SessionManagerConfiguration.swift
- Tests/Source/SessionManager/SessionManagerConfigurationTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Can not decode session manager json file that omits an optional key.
When decoding the key `messageRetentionInterval`, it was not being considered as optional
Use `decodeIfPresent`
> [Fix] Session manager configuration decoding

- Source/Calling/WireCallCenterV3+Notifications.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
This PR simply adds the conversationId to the `WireCallCenterCallErrorNotification`. This allows observers of the notification to determine which conversation the call error occurred in.
> [Feature] Pass the conversationId through the call error notification

- Source/Data Model/Typing.swift
- Source/Synchronization/Strategies/TypingStrategy.swift
- Tests/Source/Synchronization/Strategies/TypingStrategyTests.swift
Is typing update requests are sent so often while typing that they trigger request loop warnings on internal builds.
For every keystroke we call `ZMConversation.setIsTyping(true)` which posts a notification to the `TypingStrategy`. Upon receiving this notification the self user is marked as "typing" in that conversation, this leads to the creation of a `TypingEvent` which will create a request if the typing event is not equal to the typing event stored in `lastSentTypingEvent`. This equality is among other things based on the date when the event was created, if the event are closer in time than `Typing.defaultTimeout / Typing.relativeSendTimeout` they are considered equal. Those constants are currently defined as:
`Typing.defaultTimeout = 60`
`Typing.relativeSendTimeout = 5`
That means …
> [Fix] Is typing updates sent too often

- Source/Synchronization/Strategies/SearchUserImageStrategy.swift
App crash at `requestedPreviewAssets.lazy.filter` where `requestedPreviewAssets` is `[UUID : SearchUserAssetKeys?]`
Unkown, but the `lazy.filter` can be refactored. 
User `first(where:)` instead and refactor with De Morgan's laws.
> App crash at lazy.filter

- Resources/Base.lproj/ZMLocalizable.strings
- Source/Public/NSError+ZMUserSession.h
- Source/Registration/RegistrationStatus.swift
- Source/Synchronization/Strategies/RegistationCredentialVerificationStrategy.swift
- Source/UserSession/NSError+ZMUserSession.m
- Source/UserSession/NSError+ZMUserSessionInternal.h
- Source/UserSession/ZMUserSessionErrorCode+Localized.swift
- Tests/Source/Synchronization/Strategies/EmailVerificationStrategyTests.swift
When the server was responding that the email during the registration had a blocked domain a generic error message was shown, instead of showing an ad hoc one.
specific status code 451 and description label "domain-blocked-for-registration" were not treated.
specific status code 451 and description label "domain-blocked-for-registration" are now treated.
> [Fix]: Correct Error Message For Blocked Domain During Registration

- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Events.swift
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification.swift
To be able to use the `ZMLocalNotification` in the UI project, this class must be public.
> [Refactor] Make the ZMLocalNotification public

- Source/Calling/WireCallCenterConfiguration.swift
- Make the `useConferenceCalling` property mutable to allow UI to toggle conference calling
> [Fix] make conference calling setting property mutable

- Tests/Source/SessionManager/SessionManagerTests.swift
`SessionManagerTests.testThatItMarksConversationsAsRead` is flaky.
Marking as read is performed on the sync context now so that operation is now asynchronous, which caused the test to be flaky.
Wait for all groups to empty to be sure that all mark as read operations have finished.
> [Fix] flaky test

- Source/Data Model/NSManagedObjectContext+CTCallCenter.swift
- Source/SessionManager/SessionManager.swift
- Source/UserSession/ZMUserSession+Calling.swift
UI needs a way to set the `useConferenceCalling` property on `WireCallCenterV3`.
This is done similarly to the way `useConstantBitRate` is set.
> [Fix] provide public interface to set conference calling property

- Source/Calling/AVSWrapper+Handlers.swift
- Source/Calling/AVSWrapper.swift
- Source/Calling/CallCenterSupport.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3.swift
- Source/Synchronization/Strategies/CallingRequestStrategy.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
- Tests/Source/Synchronization/Strategies/CallingRequestStrategyTests.swift
This PR includes changes to send targeted calling messages when requested by AVS. Only some messages should be targeted, in which case AVS will invoke the `wcall_send_h` handler with a list of target clients passed in through the `targets` argument. If `targets` is `null`, then the message is not targeted and all clients participating in the conversation will receive the message.
**JIRA:** https://wearezeta.atlassian.net/browse/ZIOS-13424
> [Feature] Targeted calling messages

- Source/Data Model/Conversation+AccessMode.swift
- Source/Data Model/Conversation+MessageDestructionTimeout.swift
- Source/Data Model/Conversation+Participants.swift
- Source/Data Model/Conversation+ReadReceiptMode.swift
- Source/Data Model/ServiceUser.swift
- Source/Synchronization/Decoding/EventDecoder.swift
- Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoder.m
- Source/Synchronization/ZMOperationLoop+PushChannel.swift
- Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
- Source/Synchronization/ZMSyncStrategy.h
- Source/Synchronization/ZMSyncStrategy.m
- Source/Synchronization/ZMUpdateEventsBuffer.h
- Source/Synchronization/ZMUpdateEventsBuffer.m
- Source/UserSession/SyncStatus.swift
- Source/UserSession/ZMUserSession+EncryptionAtRest.swift
- Source/UserSession/ZMUserSession.swift
- Tests/Source/Integration/APNSTests+Swift.swift
- Tests/Source/Integration/APNSTests.m
- Tests/Source/MockUpdateEventProcessor.swift
- Tests/Source/Synchronization/EventDecoderTests.swift
- Tests/Source/Synchronization/Transcoders/ZMLastUpdateEventIDTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMMissingUpdateEventsTranscoderTests.m
- Tests/Source/Synchronization/ZMOperationLoopTests.m
- Tests/Source/Synchronization/ZMSyncStrategyTests.m
- Tests/Source/UserSession/ZMUserSessionTests+EncryptionAtRest.swift
- Tests/Source/UserSession/ZMUserSessionTestsBase.h
- Tests/Source/UserSession/ZMUserSessionTestsBase.m
- WireSyncEngine.xcodeproj/project.pbxproj
When we enable EAR we can only process update events when the application is running in the foreground because only then will we have access to the database key, which allows us to insert messages. Therefore I've changed it so that we only decrypt and store update events when running in the background, the event processing will happen when the app goes into foreground *or* when the database is unlocked.
In the future we might allow some events to processed background which does not need to insert messages, like conversation events.
Sending delivery receipts is still something we need to do in background which will break now, since that's currently happening when events are processed. This will be implemented in a separate PR though.
The `ZMSyncStrategy` tests are in a bad state where the …
> [Feature] Only process update events when the app is in the foreground

- Source/Calling/AVSBridging.swift
- Source/Calling/AVSWrapper.swift
- Source/Calling/CallSnapshot.swift
- Source/Calling/VoiceChannel.swift
- Source/Calling/VoiceChannelV3.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Mock.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
When we receive an incoming call, AVS tells us what kind of call it is, whether it is a legacy group call or a conference call. This information is useful to the UI in that we can selectively remove some restrictions (such as video group limits) for conference calls only.
This PR uses this information to set the `isConferenceCall` property in the `CallProperties` protocol. This is then propagated to the `VoiceChannel` which is the main calling object used from the UI.
> [Feature] Add isConferenceCall property to VoiceChannel

- Source/Public/NSError+ZMUserSession.h
- Source/Public/ZMAccountDeletedReason.swift
- Source/SessionManager/SessionManager.swift
- Source/SessionManager/ZMAccountDeletedReason.swift
- WireSyncEngine.xcodeproj/project.pbxproj
expose `SessionManager.deleteAllAccounts` and add new reason `ZMAccountDeletedReasonDatabaseWipped`
> expose wipeDatabase for deleting all accounts

- Source/UserSession/ZMUserSession+EncryptionAtRest.swift
After enabling encryption at rest (and keeping the app in the foreground), no messages can be encrypted.
The database key is not found in the managed object context because it is only set after unlocking the database after successful app lock authentication.
Store the database key in the managed object context after creating it. Additionally, clear the database key after deleting it.
> [Fix] Missing database key after enabling encryption at rest

- Source/UserSession/ZMUserSession+EncryptionAtRest.swift
- Tests/Source/UserSession/ZMUserSessionTests+EncryptionAtRest.swift
If encryption at rest is enabled for an account on a device and then the app is reinstalled, then enabled encryption at rest again would fail.
The encryption keys are persisted in the keychain. When the app is reinstalled and new keys are created, we get an error stating there already exists keys with the given identifier.
Always delete existing keys before creating new ones.
> [Fix] Can not enable encryption at rest keys exist in keychain

- Source/Synchronization/NSManagedObjectContext+EventDecoder.swift
- Tests/Source/Synchronization/Strategies/CallingRequestStrategyTests.swift
Event database is dropped and re-created when upgrading to the EAR branch
The persistent store for the event managed object context is not configured to support migration.
Configure the persistent store to support migration.
> [Fix] Enable database migration for the event database

- Source/Notifications/Push notifications/Notification Types/LocalNotificationContentType.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Event.swift
User notifications (stating "New message") appear when no new message is visible.
The notification is generated for a confirmation message (which is not visible in the conversation). 
Don't generate notifications for confirmation messages.
> [Fix] Don't create notifications for confirmation messages

- Source/Notifications/Push notifications/LocalNotificationDispatcher+Calling.swift
- Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+AvailabilityAlert.swift
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Calling.swift
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Events.swift
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+ExpiredMessages.swift
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification.swift
- Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Configuration.swift
- Source/Notifications/Push notifications/Notification Types/PushNotificationCategory.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForTests_CallState.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_ExpiredMessage.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
The user notification actions for replying to and liking a message do not work when encryption at rest is enabled.
When encryption at rest is enabled, the database is locked while the app is in the background. For this reason, we can not perform these actions.
Hide the actions when encryption at rest is enabled.
Encryption at rest is enabled per account. Therefore the actions are only hidden for user notification associated with accounts in which the the feature is enabled.
> [Chore] Hide user notification actions when EAR is enabled

- Source/Synchronization/Strategies/LabelDownstreamRequestStrategy.swift
- Tests/Source/Synchronization/Strategies/LabelDownstreamRequestStrategyTests.swift
The labels would get re-fetched over an over again.
If the `needsToRefetchLabels` property was ever set to true if would never be set to false and thus we would download the labels over and over again. 
The `needsToRefetchLabels` property is only set to true in a hot fix patch which was added when the folder feature was released.
Reset `needsToRefetchLabels` to false after fetching the labels.
> [Fix] label refetch not being reset after fetching labels

- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
When EAR is enabled and your self client gets deleted you'll get logged out, If you log back in again your messages will not be readable.
The message encryption is tied to your self client ID.
Delete the account/database if your client gets deleted remotely.
> [Fix] Delete account when self client is deleted remotely

- Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
- Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification.swift
- Source/Notifications/Push notifications/Notification Types/LocalNotificationContentType.swift
- Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_UnreadCount.swift
- WireSyncEngine.xcodeproj/project.pbxproj
After we split the event processing into two phases the badge count is no longer updated when a push notification is received.
The badge count is updated by calculating the number of conversation which has unread messages. The number of unread messages in a conversation is updated when we read or insert new messages in a conversation, but since we no longer insert messages in the database during the first event phase the unread message count doesn't get updated until open the app.
Update the unread count when displaying a notification for a message which should increase the badge count. This will only be an estimation of the unread count because this solution doesn't take into account that you might have read messages on a second device. The correct unread count will be calculated during …
> [Feature] Update badge count when processing notifications in the background

- Source/Synchronization/ZMOperatonLoop+Background.swift
- Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
- Tests/Source/Integration/APNSTests+Swift.swift
- Tests/Source/Integration/ConversationTests+List.swift
- Tests/Source/Integration/ConversationTests+OTR.swift
- Tests/Source/Integration/ConversationTests+Participants.swift
- Tests/Source/Integration/ConversationTestsBase.m
- Tests/Source/Integration/SendAndReceiveMessagesTests+Swift.swift
Badge count is not updated after receiving push notifications.
From looking at logs I can see that we are not saving SE before attempting re-calculate the badge count, which means that any increases to estimated unread count of conversations will not be included.
Explicitly save the SE context after processing events in the background.
I added a test for this unfortunately is still passing without this change due to a delayed saved which gets performed at the right time.
> [Fix] Attempt to fix badge count not updating by explicitly saving

- Source/UserSession/ZMUserSession+EncryptionAtRest.swift
- Tests/Source/UserSession/ZMUserSessionTests+EncryptionAtRest.swift
App would crash when attempting to activate EAR during login
When EAR is enabled by default we activate it when the user session is created, but If you have reached the maximum number of devices you will be asked to remove a device before we have a fully functional user session. Importantly the self user is not yet accessible, which causes the EAR activation to fail since it accesses the self user in order to look up the userID (remoteIdentifier). This results in a crash due to force unwrapping an optional (nil) value.
Look up the userID on the `storeProvider` instead
> [Fix] Crash when enabling EAR during login

- Cartfile
- Cartfile.resolved
- Source/Calling/CallClosedReason.swift
Add `outdatedClient` to `CallClosedReason` which is needed for outdated client alerts in UI
Change was originally released as a hotfix for 3.64.
> [Chore] add `outdatedClient` to CallClosedReason

- Source/UserSession/ZMUserSession.swift
- Tests/Source/UserSession/ZMUserSessionTests+Syncing.swift
When the app comes to the foreground after accumulating several update events, it can take a while to complete syncing.
Previously update events were processed in the background when we received remote pushes. After implementing encryption at rest, this is no longer the case and most update events are now processed when the app returns to the foreground. It can easily happen that a device accumulates a lot of update events needing processing, which can lead to slow synchronization times.
A way we can speed this up is to disable the observation system during this event processing stage. The observation system is used to keep the UI up-to-date when events are processed, however it is quite an expensive and makes little sense during the quick sync phase, as it essentially "replays" the …
> [Performance] Disable observation system during quick sync

- Tests/Source/Integration/APNSTestsBase.h
- Tests/Source/Integration/APNSTestsBase.m
- Tests/Source/Integration/EventProcessingPerformanceTests.swift
- Tests/Source/Integration/IntegrationTest.swift
- WireSyncEngine.xcodeproj/project.pbxproj
- WireSyncEngine.xcodeproj/xcshareddata/xcbaselines/3E1860C2191A649D000FE027.xcbaseline/8C2DC110-E573-497C-922A-2C909350F73B.plist
- WireSyncEngine.xcodeproj/xcshareddata/xcbaselines/3E1860C2191A649D000FE027.xcbaseline/Info.plist
- WireSyncEngine.xcodeproj/xcshareddata/xcschemes/WireSyncEngine.xcscheme
Add performance tests for event processing in order to better profile and evaluate performance improvements. 
NOTE: The tests are disabled in the suite since they are quite slow to run.
> [Feature] Add performance tests for event processing

- Source/UserSession/ZMUserSession.swift
- Tests/Source/UserSession/ZMUserSessionTests+Syncing.swift
This reverts commit f92188f068ad30fb8941dd019f2ae12e73cea76e because the observation system was getting stuck in a disabled state after the quick sync finished.
> Revert "[Fix] Disable observation system during quick sync (#1314)"

- Source/Calling/CallParticipantSnapshot.swift
- Source/Calling/CallSnapshot.swift
- Source/Calling/VoiceChannel.swift
- Source/Calling/VoiceChannelV3.swift
- Source/Calling/WireCallCenterV3+Degradation.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/CallSnapshotTestFixture.swift
- Tests/Source/Calling/VoiceChannelV3Tests.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
- New behaviour for dropping calls when a security degradation occurs.
- Allow a degraded incoming call to be joined
Drop the call if the security level of **the conversation** degrades. 
Degradation may occur in following scenario:
_GIVEN_ **all conversation participants** are verified 
_WHEN_ one or more participants become unverified
_THEN_ conversation security degrades
Drop the call if the security of **any call participant** degrades.
Degradation may occur in following scenario:
_GIVEN_ **any call participant** is verified 
_WHEN_ a verified participant becomes unverified
_THEN_ call security degrades
> [Feature] call degradation

- Source/SessionManager/SessionManager+Backup.swift
- Tests/Source/SessionManager/SessionManagerTests+Backup.swift
When you sent a backup file through the email, the Gmail app changes the file extension.(xxx.ios_wbu to xxx.ios-wbu).
There is the Gmail app issue.
https://support.google.com/mail/thread/15716995?hl=en
Do not check the file extension and accept both file extensions.
wireapp/wire-ios/pull/4634
> [Fix] Do not check the file extension

- Source/Notifications/Push notifications/Notification Types/LocalNotificationContentType.swift
- Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
Message edits is generating notifications and therefore also increases the badge count, which doesn't go away if the original message has already been read.
After the encryption at rest refactoring we are increasing the badge count (unread count) when we are scheduling a notification if the message is of a type which should increase the unread count. This unread count will later be re-calculated when the actual message is inserted during the second phase of the event processing.
However for message edits we don't insert a new message but instead modify an existing message and therefore we also don't re-calculate the unread count, which means that unread count will stay until another message arrives in the conversation.
1. Re-calculate the unread count also when applying message edits.
2. …
> [Fix] Don't generate notifications for edit messages

- Source/UserSession/ZMUserSession.swift
- Tests/Source/Integration/SlowSyncTests.m
- Tests/Source/UserSession/NetworkStateRecorder.swift
- Tests/Source/UserSession/ZMUserSessionTests+Syncing.swift
- Tests/Source/UserSession/ZMUserSessionTests.m
Syncing indicator isn't shown when processing events received in the background.
The syncing indicator is only shown when we perform the quick sync but we are now processing previously received events before the quick sync. If many events have been accumulating this processing can take a few seconds.
Indicate that we are syncing before processing previously received events.
> [Fix] Indicate syncing while processing events

- Source/SessionManager/SessionManager.swift
- Source/UserSession/ZMUserSession+Calling.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
When the user has an ongoing call and wants to switch the account a confirmation alert is presented. When the user confirm the alert the account is switched and all the calls are ended.
In order to have a better testability of the `SwitchingAccountRouter` (`wire-ios`) I moved from the `UI` all the task that should be performed directly in the sync-engine in a way that now the `UI` should take care to just show the alert when it is necessary. This means that:
1) All the checks if there are ongoing calls are mede in the `sync-engine`
2) If the switch is confirmed all the call are ended in the `sync-engine`
> [Refactoring]: SwitchingAccountRouter Tests

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
UI currently has logic for determining if a call `sessionManagerWillMigrateAccount()` should display the migration screen or not. It's better to have this logic inside the SessionManager.
Changes:
- Only call `sessionManagerWillMigrateAccount()` when we load a session which will become the active session. That is don't call it when loading a session for processing a push notification.
- Make the `Account` parameter non-optional in the session loading methods
- Delete the `sessionManagerWillMigrateLegacyAccount` delegate method, use `sessionManagerWillMigrateAccount` use instead.
This PR is part of a series refactoring necessary to enable migrations to and from EAR.
> [Refactor] SessionManager account migration

- Source/SessionManager/SessionManager.swift
- Source/SessionManager/SessionManagerConfiguration.swift
- Tests/Source/SessionManager/SessionManagerConfigurationTests.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
Add SessionManagerConfiguration option to enable EAR by default.
This change is necessary because when I introduce EAR migration I don't want to perform a migration EAR is enabled by default. That would require me to add new public API to the `ZMUserSession` which could easily be miss-used, I there decided move all of the EAR by default logic to SE.
This PR is part of a series refactoring necessary to enable migrations to and from EAR.
> [Refactor] Add SessionManagerConfiguration option to enable EAR by default

- Source/SessionManager/SessionManager.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
At the app launch when the user was unauthenticated the app remain stuck 
Some changes were made and the `UI` was was not informed anymore by the `SessionManager` that the unauthenticated session was created and the `AppState` didn't change
Even if we noticed that the old solution to inform the UI when an UnauthenticatedSession is created smells a bit, the fastest solution to solve the issue is using the same approach and now the UI is informed using the  `sessionManagerDidFailToLogin` delegate method of the `SessionManager` and the `AppState` changes.
> [Fix]: Inform the UI when an UnauthenticatedSession is created

- Tests/Source/E2EE/ConversationTests+OTR.m
- Tests/Source/Integration/APNSTests.m
- Tests/Source/Integration/ClientManagementTests.m
- Tests/Source/Integration/ConnectionTests.m
- Tests/Source/Integration/ConversationTests+OTR.swift
- Tests/Source/Integration/ConversationTestsBase.m
- Tests/Source/Integration/ConversationsTests.m
- Tests/Source/Integration/LoginFlowTests.m
- Tests/Source/Integration/SendAndReceiveMessagesTests.m
- Tests/Source/Integration/SlowSyncTests.m
- Tests/Source/Integration/UserProfileTests.m
- Tests/Source/Integration/UserTests.m
Test target has compoile error with Xcode 12.2
`MockTransportSession<MockTransportSessionObjectCreation> *session` can not be casted.
Fix the block's parameter.
> Fix: Xcode 12 test target build issue

- Source/SessionManager/SessionManager+Push.swift
- Source/Utility/Application.swift
Compilation failed with Xcode 12 on CI machines
Unknown (crashed with reason Segmentation fault 11)
But it seems that `shouldRegisterUserNotificationSettings` is an optional protocol method, which is not implemented in sync engine
Create `NotificationSettingsRegistrable` for `shouldRegisterUserNotificationSettings` method and make `WireApplication` in UI project conforms it.
> fix: NotificationSettingsRegistrable protocol

- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
the method of the `SessionManagerDelegate` (in the new version it is not there anymore)
```swift
func sessionManagerDidFailToLogin(account: Account?,
from selectedAccount: Account?,
error: Error)
```
is currently called in situations which is unexpected, this means that we have been forced to add filtering logic in the `UI` to disregard these situations.
adding where necessary
```swift
let account = accountManager.account(with: accountId)
guard account == accountManager.selectedAccount else { return }
```
we ensure that the `sessionManagerDidFailToLogin` it is now called when it necessary and we don't need anymore to pass to the `UI` the `account: Account?` and the `selectedAccount: Account?`.
JIRA: [SQCORE-215](https://wearezeta.atlassian.net/browse/SQCORE-215)
> [Refactor]: SessionManagerDelegate: improve sessionManagerDidFailToLogin method usage

- Source/SessionManager/SessionManager+EncryptionAtRest.swift
Messages are not received after migrating away from EAR
EncryptionKeys are not deleted from key chain after migrating away from EAR.
Delete encryption keys from keychain
> [Fix] Delete encryption keys when migrating away from EAR

- Source/Calling/VoiceChannel.swift
- Source/Calling/VoiceChannelV3.swift
- Tests/Source/Calling/VoiceChannelV3Tests.swift
Change the `firstDegradedUser` type to protocol type `Usertype` for UI project easier to mock.
> Fix: change voice channel protocol member firstDegradedUser type form ZMUser to usertype

- Source/Calling/CallState.swift
- Tests/Source/Calling/CallParticipantTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
After https://github.com/wireapp/wire-ios-sync-engine/pull/1358 is merged, UI tests failed
`state` is added to the hash calculation, which is not included before.
Remove the unnecessary hash components and make a test to describe this requirement.
> remove state from CallParticipant hash

- Source/SessionManager/SessionManager.swift
- Source/Utility/Application.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- Tests/Source/Utility/ApplicationMock.swift
According to the [RFC](https://wearezeta.atlassian.net/wiki/spaces/IOS/pages/159646019/Simplify+API+for+Login+Registration) about the login and registration API one of the improvement we would like to add is removing the async creation of the `SessionManager` in the `AppRootRouter`. To achieve this goal some changes are made in the `SessionManager`:
- remove the method:
```swift
public static func create(
appVersion: String,
mediaManager: MediaManagerType,
analytics: AnalyticsType?,
delegate: SessionManagerDelegate?,
presentationDelegate: PresentationDelegate?,
application: ZMApplication,
environment: BackendEnvironmentProvider,
configuration: SessionManagerConfiguration,
detector: JailbreakDetectorProtocol = JailbreakDetector(),
completion: @escaping (SessionManager) -> Void
```
- expose …
> [Refactor]: Removed SessionManager Async Creation Method

- Tests/Source/UserSession/ZMUserSessionTestsBase.m
There's a failed `testThatItPostsNotification_WhenLogoutRequestSucceeds` test.
In the `ZMUserSession` initialiser, we create a selfUser in `uiMoc` without the `remoteIdentifier` that is causing the test to fail.
Create a `selfUser` before initialise the userSession in `ZMUserSessionTestsBase`.
> [Fix] Failed testThatItPostsNotification_WhenLogoutRequestSucceeds test

- Source/Synchronization/ZMHotFixDirectory.m
Restart the slow sync when upgrading in order to recover any potentially lost connections caused by https://github.com/wireapp/wire-ios-data-model/pull/1107
> [Fix] Restart slow sync when upgrading in order to restore lost connections

- Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
I've observed that scheduled notifications are sometimes not displayed. To investigate this further I'm adding logs for when scheduling a notification succeeds / fails.
> [Chore] Add logs for when scheduling a notification succeeds / fails

- Source/Calling/AVSActiveSpeakerChange.swift
- Source/Calling/CallParticipantsListKind.swift
- Source/Calling/CallState.swift
- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/CallParticipantTests.swift
- Tests/Source/Calling/CallParticipantsKindTests.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
Updated the `CallParticipant`'s property `isActiveSpeaker: Bool` into `activeSpeakerState: ActiveSpeakerState`.
This allow the `.active` case of `ActiveSpeakerState` enum to carry an associated value for the instantaneous audio level, which should be used to pulse the participant's microphone / show the active speaker frame.
> [Refactor] active speaker state

- Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
When message is edited the original message notification is deleted from the Notification Center.
This was introduced by https://github.com/wireapp/wire-ios-sync-engine/pull/1325, where we stopped inserting notifications for edits but we didn't remove the logic for removing the original notification.
Stop removing the notifications from Notification Center on edits.
> [Fix] Edited message was incorrectly deleted from notification center

- Source/SessionManager/SessionManager.swift
for ore info about the issue see the bug ticket [here](https://wearezeta.atlassian.net/browse/SQCORE-511). Anyway this happens always, not just when the user has the maximum of the devices registered as written in the ticket.
when we inform the `UI` with 
```swift
if session.isLoggedIn {            
self.delegate?.sessionManagerDidReportLockChange(forSession: session)
}
```
we still didn't select the account. The account selection is done in the `completion(session)`
move the `completion(session)` before we inform the UI through the `delegate`. 
I have tried many scenarios and it seems to work. Anyway it would be nice if who is reviewing this PR will think a bit if there is some edge cases on which this solution doesn't work.
> [fix]: SQCORE-511 Logout is not working when switch account.

- Source/Synchronization/EventProcessor.swift
Tests were logging the data store was deleted while Core Data was having an open file descriptor attached to it.
We weren't closing the persistence store when shutting down a user session. This can lead to data loss as we experienced in https://github.com/wireapp/wire-ios-data-model/pull/1071
Close the persistence store on deinit.
See also https://github.com/wireapp/wire-ios-data-model/pull/1149
> [Fix] Close the event persistence store when the EventProcessor deinits

- Source/SessionManager/SessionManager+Push.swift
App sometimes crash if the user session is shutdown quickly after it started.
When the user session is started we asynchronously update the push token. If the user session shut down before this asynchronous call is performed `setPushKitToken()` will be called on the torn down  user session where the managed object contexts have deallocated, which will cause a nil unwrapping crash.
Hold a weak reference to the user session so that we don't call `setPushKitToken()` if it has been shutdown.
> [Fix] Crash after tearing down user session quickly

- Source/Calling/CallParticipantSnapshot.swift
- Tests/Source/Calling/CallParticipantsSnapshotTests.swift
Sometimes an ongoing call will be terminated with the reason `.securityDegraded` although the user did not verify any participants beforehand.
`isTrusted` evaluates to `true` when the evaluated user's clients list is empty
use `isVerified` instead of `isTrusted`
> [Fix] call degradation logic

- Source/Synchronization/Transcoders/ZMConnectionTranscoder.m
- Source/UserSession/NotificationInContext+UserSession.swift
- Tests/Source/Data Model/ServiceUserTests.swift
- Tests/Source/Integration/ConnectionTests.m
- Tests/Source/Synchronization/Transcoders/ZMConnectionTranscoderTest.m
BE will add `error code 412` in response to posting a new connection if it's a legal hold policy conflict.
When we receive this error code, we should notify the UI project and display an alert with a message.
> [Feature] Handling error messages when requesting new connections

- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- Source/UserSession/NotificationInContext+UserSession.swift
BE will add error code `412` in response to posting a new conversation if there is a legal hold policy conflict.
When we receive this error code, we should notify the UI project and display an alert with a message.
TODO: I haven't added any tests, but if you don't mind I'll add them later
> [Feature] Handling error messages when adding new conversation

- Source/Synchronization/ZMHotFixDirectory.m
- Source/UserSession/ZMUserSession.swift
- Tests/Source/Integration/SlowSyncTests.m
- Tests/Source/Synchronization/ZMHotFixTests.swift
- Update capabilities `"capabilities": ["legalhold-implicit-consent"]` after registration for all new clients
- Change a HotFixPatch version
> [Fix] Update capabilities for new clients

- Source/DeepLink/URL+DeepLink.swift
- Source/SessionManager/URLActions.swift
- Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
- Tests/Source/SessionManager/URLActionTests.swift
- Introduce a new url action `joinConversation` which will be used to join a conversation with a key and a code.
- Extend the `DeepLinkURLActionProcessor` to handle this new deep link. It currently just asks for user confirmation. 
- Added unit tests for parsing the new deep link.
> Parse join conversation deep link

- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
- Source/UserSession/PreLoginAuthenticationNotification.swift
- Source/UserSession/ZMClientRegistrationStatus.h
- Source/UserSession/ZMClientRegistrationStatus.m
- Source/UserSession/ZMClientRegistrationStatus.swift
- Tests/Source/UserSession/ZMClientRegistrationStatusTests.h
- Tests/Source/UserSession/ZMClientRegistrationStatusTests.m
- Tests/Source/UserSession/ZMClientRegistrationStatusTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
Remove @objc signature of `LoginCredentials.dictionaryRepresentation` for the requirement of XCFramework.
Convert `ZMClientRegistrationStatus.didFailToRegisterClient` to Swift since it calls the above function.
Convert `testThatItReturns_FetchingClients_WhenReceivingAnErrorWithTooManyClients` to Swift to prove that `ZMClientRegistrationStatus.didFailToRegisterClient` call be called with Swift code.
> Fix: remove LoginCredentials.dictionaryRepresentation @objc signature

- Source/UserSession/ZMUserSession.Configuration.swift
- Tests/Source/UserSession/ZMUserSessionTests.m
- Tests/Source/UserSession/ZMUserSessionTestsBase+ZMUserSessionConfiguration.swift
- Tests/Source/UserSession/ZMUserSessionTestsBase.m
- Tests/Source/UserSession/ZMUserSessionTests_NetworkState.swift
- Tests/Source/Utility/ZMUserSession+DefaultConfiguration.swift
- WireSyncEngine.xcodeproj/project.pbxproj
When building this framework as a XCFramework, error occurs in the code having `ZMUserSessionConfiguration`. 
Convert these tests to Swift and remove `ZMUserSessionConfiguration` @objc signature.
> Remove ZMUserSessionConfiguration @objc signature

- Source/Data Model/Conversation+Join.swift
The crash in the UI when receiving an error message.
`completion(.failure(error))` was called from syncContext. The completion handler triggers a delegate method that displays a popup with an error message.
Perform the request from `viewContext`.
> [Fix] Perform the request from viewContext

- Source/Data Model/ZMUser+FederatedConnection.swift
- Source/Synchronization/Transcoders/ZMConversationTranscoder.m
- WireSyncEngine.xcodeproj/project.pbxproj
Support creating fake one-to-one conversation with a federated user. 
This code will be removed before this feature is shipped and is only implemented to unlock some user flows during testing.
> [Feature] Support creating fake one-to-one conversation with a federated user

- Source/Data Model/ZMUser+FederatedConnection.swift
fake one-to-one conversations with federated users had always the name of the other user which doesn't make sense for the receiving end. 
Set both names as the conversation name.
> [Fix]  Name for for fake one-to-one conversations with federated users

- Tests/Source/Integration/IntegrationTest.h
- Tests/Source/Integration/IntegrationTest.m
- Tests/Source/Integration/IntegrationTest.swift
Prevent using `SessionManagerConfiguration` in objc code to prevent linker error
> Fix: integration test linker error

- Tests/Source/Integration/UserProfileTests.m
- Tests/Source/Synchronization/Transcoders/UserProfileUpdateRequestStrategyTests.swift
- TestsPlans/AllTests.xctestplan
This PR disables failing tests:
- 4 Integration tests on `UserProfileTests.m` 
- `UserProfileUpdateRequestStrategyTests.swift` - failing due to a leaked `NSManagedObjectContext` object
It also fixes a test in `UserProfileUpdateRequestStrategyTests.swift`
> [Chore] fix/disable failing tests

- WireSyncEngine.xcodeproj/project.pbxproj
Don't embed the Starscream framework since it will be embedded at the top level.
> [Chore] Don't embed the Starscream framework

- Source/Calling/WireCallCenterV3.swift
- Tests/Source/Calling/WireCallCenterV3Tests.swift
This PR updates the behaviour when answering a call & when handling an incoming call.
- Remove setting video state when answering a call
- Mute microphone for group calls when handling an incoming call instead of when answering
> [Feature] Pre-call actions

- Tests/Source/Integration/PushChannelTests.swift
Failed `testThatItFetchesLastNotificationsFromBackendIgnoringTransientNotificationsID` test. 
Requests to fetch feature configs have been added to QuickSync.
Exclude the fetch feature config requests from the expected result, as the test checks if there are transient notification in the given result.
> [Fix] Failed tests that were affected by adding new requests to QuickSync

- Source/Calling/CallCenterSupport.swift
- Source/Calling/CallKitManager.swift
- Source/Calling/MediaManager.swift
- Source/Calling/VoiceChannel.swift
- Source/Calling/WireCallCenterV3+Notifications.swift
- Source/Notifications/Push notifications/Helpers/UserNotificationCenter.swift
- Source/Registration/Company/CompanyLoginRequester.swift
- Source/Registration/RegistrationStatus.swift
- Source/SessionManager/PresentationDelegate.swift
- Source/SessionManager/SessionManager+AVS.swift
- Source/SessionManager/SessionManager.swift
- Source/Synchronization/EventProcessingTracker.swift
- Source/Synchronization/EventProcessor.swift
- Source/Synchronization/Strategies/Asset Deletion/AssetDeletionStatus.swift
- Source/Synchronization/Strategies/Asset Deletion/DeletableAssetIdentifierProvider.swift
- Source/UnauthenticatedSession/URLActionProcessors/CompanyLoginURLActionProcessor.swift
- Source/UnauthenticatedSession/UnauthenticatedSession.swift
- Source/UserSession/OperationStatus.swift
- Source/UserSession/UserProfileImageUpdateStatus.swift
- Source/UserSession/ZMUserSession+AppLock.swift
- Source/UserSession/ZMUserSession+Calling.swift
- Source/UserSession/ZMUserSession+EncryptionAtRest.swift
- Source/Utility/Pasteboard.swift
Replace all protocol extends class with AnyObject
> Fix: xcode13 warning - Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead

- .swiftlint.yml
- Source/Calling/CallKitManager.swift
- Source/Calling/SystemMessageCallObserver.swift
- Source/Calling/WireCallCenterV3+Events.swift
- Source/Data Model/Conversation+AccessMode.swift
- Source/Data Model/Conversation+MessageDestructionTimeout.swift
- Source/E2EE/APSSignalingKeysStore.swift
- Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
- Source/SessionManager/SessionManager.swift
- Source/Synchronization/Strategies/RegistationCredentialVerificationStrategy.swift
- Source/Synchronization/Strategies/UserClientRequestFactory.swift
- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
- Source/UserSession/ClientUpdateStatus.swift
- Source/UserSession/FileRelocator.swift
- Source/UserSession/ZMUserSession+Push.swift
- Tests/Source/Calling/CallKitManagerTests.swift
- Tests/Source/E2EE/UserClientRequestFactoryTests.swift
- Tests/Source/Integration/ConversationTests+Ephemeral.swift
- Tests/Source/Synchronization/EventDecoderTests.swift
- Tests/Source/Synchronization/SynchronizationMocks.swift
- Tests/Source/Synchronization/ZMConversationAccessModeTests.swift
- Tests/Source/UserSession/ZMUserSessionTests+EncryptionAtRest.swift
----
----
1. With this PR I started to remove rules from the disabled rules list and fixed the errors and warnings that popped up. More specifically I fixed warnings and errors for the rules below:
- **Statement Position Violation**: Else and catch should be on the same line, one space after the previous declaration. `(statement_position)`
- **Shorthand Operator Violation**: Prefer shorthand operators (+=, -=, *=, /=) over doing the operation and assigning. `(shorthand_operator)`
2. In addition to that I removed a bunch of rules from the list since they didn't trigger any warnings and errors by being enabled. These rules are:
- **Reduce Boolean**: Prefer using .allSatisfy() or .contains() over reduce(true) or reduce(false) `(reduce_boolean)`
- …
> fix: Fix warnings and errors for multiple SwiftLint rules by removing them from the disabled list

- Tests/Source/UnauthenticatedSession/URLActionProcessors/StartLoginURLActionProcessorTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
----
----
There are failed tests related to `StartLoginURLActionProcessor` :
- testThatAuthenticationStatusChanges_OnStartLoginAction
- testThatStartLoginActionFails_WhenAccountLimitIsReached
The tests were created in the wrong file.
These tests were created for `StartLoginURLActionProcessor` and should be moved to the corresponding test case (`StartLoginURLActionProcessorTests`).
----
----
----
> fix: Fix tests related to StartLoginURLActionProcessor

- Source/UserSession/Search/SearchRequest.swift
- Tests/Source/UserSession/SearchRequestTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-454" title="FS-454" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-454</a>  [iOS] The app crashes on searching muhammadanta1@anta.wire.link abc in search UI field 
</td></table>
<br />
----
----
Remove whitespace in federated handle search
> fix: remove space in federated handle search query FS-454

- Source/Calling/CallCenterSupport.swift
- Source/Calling/CallEventContent.swift
- Source/Synchronization/Strategies/CallingRequestStrategy.swift
- Tests/Source/Calling/CallEventContentTests.swift
- Tests/Source/Synchronization/StoreUpdateEventTests.swift
- Tests/Source/Synchronization/Strategies/CallingRequestStrategyTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQCALL-336" title="SQCALL-336" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />SQCALL-336</a>  [iOS] PARTICIPANT - Remote mute support for participant
</td></table>
<br />
----
----
We need to implement support for remote mute
Before processing call events and forwarding them to AVS, we decode the event data and check if the type of the event is a remote mute event. If it is, we mute the user instead of sending the call event to AVS.
----
----
----
1. E.g. `feat(conversation-list): Sort …
> feat: remote mute support - SQCALL-336

- Source/Synchronization/Strategies/UserClientRequestFactory.swift
- Source/Synchronization/Strategies/UserClientRequestStrategy.swift
- Tests/Source/E2EE/UserClientRequestFactoryTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1177" title="SQSERVICES-1177" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQSERVICES-1177</a>  [iOS] 2nd auth factor for "add client"
</td></table>
<br />
----
----
If 2nd auth factor is enabled, we should send an additional optional field verification-code to the POST /clients endpoint.
----
----
----
> feat: Add verification_code parameter to the register client request SQSERVICES-1177

- Source/Synchronization/Transcoders/ZMLoginCodeRequestTranscoder.m
- Source/Synchronization/Transcoders/ZMLoginTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMLoginCodeRequestTranscoderTests.m
- Tests/Source/Synchronization/Transcoders/ZMLoginTranscoderTests.m
- Tests/Source/UserSession/ZMAuthenticationStatusTests.m
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1341" title="SQSERVICES-1341" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />SQSERVICES-1341</a>  [iOS] SE: modify ZMLoginCodeRequestTranscoder
</td></table>
<br />
----
----
With this PR we modify the `ZMLoginCodeRequestTranscoder` to support Two Factor Authentication for Login. More specifically:
- Renamed `codeRequestSync` to `phoneVerificationCodeRequestSync`
- Added a new property `emailVerificationCodeRequestSync`
- in nextRequest we add an if check for the `current phase`
- In `requestForSingleRequestSync` method we do a check for which sync we do have and based on …
> feat: Modify `ZMLoginCodeRequestTranscoder` to support 2FA for login SQSERVICES-1341

- Source/Synchronization/Transcoders/ZMLoginCodeRequestTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMLoginCodeRequestTranscoderTests.m
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1416" title="SQSERVICES-1416" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />SQSERVICES-1416</a>  SE: Add "action" as part of the payload
</td></table>
<br />
----
----
With this PR we add action as part of the payload regarding 2FA for login. This is needed so the request can work as expected. If it's missing we're getting an error back.
----
> fix: Add "action" as part of the payload regarding 2FA for login SQSERVICES-1416

- Source/Synchronization/Transcoders/ZMLoginTranscoder.m
- Tests/Source/Synchronization/Transcoders/ZMLoginTranscoderTests.m
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1417" title="SQSERVICES-1417" target="_blank"><img alt="Subtask" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />SQSERVICES-1417</a>  SE: Fix typo in the payload for the verification code (2FA)
</td></table>
<br />
----
----
Fix a typo related to the payload for the 2FA for login. 
----
> fix: Payload typo for 2FA for Login SQSERVICES-1417

- Source/Synchronization/Strategies/LegalHoldRequestStrategy.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-535" title="FS-535" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-535</a>  [iOS] Legal hold regressions
</td></table>
<br />
----
----
When a user logs into the app after having been requested to enable legal hold, the legal hold alert isn't shown.
The legal hold sync request path misses a `/` at the beginning. Resulting in something like `v1teams/.../legalhold/...` instead of `v1/teams/.../legalhold/...`
Add missing `/`
- **TODO:** Add tests for the request path
----
----
----
1. …
> fix: missing alert when legal hold is requested FS-535

- Source/SessionManager/SessionManager+APIVersionResolver.swift
- Source/SessionManager/SessionManager.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-422" title="FS-422" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-422</a>  [iOS] Clients need to know if the backend support federated endpoints or not
</td></table>
<br />
----
----
The app wasn't functioning correctly when switching backends. For example, when switching to a federated backend, the app was acting as if it couldn't federate.
We only resolved the api version when the app first loads or comes to the foreground. When switching the backend via a deep link, we were not resolving the api version directly afterward.
Resolve the api version also after switching backends. …
> fix: resolve api version when switching backend FS-422

- Source/SessionManager/BackendEnvironmentProvider+Reachability.swift
- Source/SessionManager/SessionFactories.swift
- Source/SessionManager/SessionManager+ServerConnection.swift
- Source/SessionManager/SessionManager.swift
- Tests/Source/Integration/IntegrationTest.swift
- WireSyncEngine.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-799" title="FS-799" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-799</a>  Cannot login with deeplinked backend
</td></table>
<br />
----
----
When switching a backend via deep link, then logging in with valid credentials an alert is shown stating that is issues with the network.
When logging in, there is a reachability check to see if the server is reachable. This was failing because the reachability object was still configured to the previous backend environment, which in this case was unreachable.
When the backend environment changes, then the reachability helper must be recreated …
> fix: can't login to deep-linked backend FS-799

- Source/Data Model/Conversation+MessageDestructionTimeout.swift
- Source/Registration/RandomHandleGenerator.swift
- Source/UserSession/ZMUserSession.swift
----
----
Fix SwiftLint warnings related to legacy random
- Legacy Random Violation: Prefer using type.random(in:) over legacy functions. (legacy_random)
----
> fix: SwiftLint legacy_random warnings

- Source/Calling/CallKitManager.swift
- Tests/Source/Calling/CallKitManagerTests.swift
----
----
With this PR we drop INStartAudioCallIntent and INStartVideoCalIntent and replace it with INStartCalIntent.
----
> chore: Remove deprecated INStartAudioCallIntent and INStartVideoCalIntent

- Source/UserSession/ZMUserSession.swift
----
----
Sometimes the client is unable to fetch the backend mls keys.
Fetching the keys happens in the initializer of the `MLSController`. It uses an action to make the network request. Typically an action handler picks up the action and schedules the request to the backend, but this isn't always happening because the action handler may not exist yet. This is because the request strategies are set up after setting up the MLS controller.
Set up the mls controller after the request strategies.
- tested manually
----
----
----
> fix(mls): not able to fetch backend keys

- Source/SessionManager/JailbreakDetector.swift
- Source/Synchronization/Strategies/UserProfileUpdateRequestStrategy.swift
- Tests/Source/MockAddressBook.swift
For Where Violation: `where` clauses are preferred over a single `if` inside a `for`. (for_where)
----
----
With this PR we fix SwiftLint warnings related to `(for_where)`
- For Where Violation: `where` clauses are preferred over a single `if` inside a `for`. (for_where)
----
> fix: SwiftLint warnings related to `(for_where)`

- Source/Calling/CallKitCall.swift
- Source/Calling/CallKitCallRegister.swift
- Source/Calling/CallKitManager.swift
- Source/Calling/CallObserver.swift
- Source/Notifications/VoIPPushManager.swift
- Source/SessionManager/SessionManager+CallKitManagerDelegate.swift
- Source/SessionManager/SessionManager.swift
- Source/Synchronization/ApplicationStatusDirectory.swift
- Source/Synchronization/EventProcessor.swift
- Source/UserSession/SyncStatus.swift
- Source/UserSession/ZMUserSession.swift
----
----
If you accumulate unprocessed call events (e.g call start, call end, call start...), then attempt to answer an incoming call, the calls will be terminated.
All unprocessed call events need to be processed before you can join a current call. Processing old events would trigger call state changes that would then terminated the current CallKit call.
- Disable call state observation when processing CallKit calls.
- Perform a quick sync before registering observation for the current call.
- There are some other little fixes included in this PR too.
Manually tested.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most …
> refactor: separate call observation

- Source/SessionManager/APIMigration/APIMigrationManager.swift
- Source/SessionManager/APIMigration/AccessTokenMigration.swift
- Source/SessionManager/APIVersionResolver.swift
- Source/SessionManager/SessionManager+APIVersionResolver.swift
- Source/SessionManager/SessionManager.swift
- Source/UserSession/ZMUserSession+AccessToken.swift
- Source/UserSession/ZMUserSession.swift
- Source/Utility/Logging.swift
- Tests/Source/Integration/IntegrationTest.swift
- Tests/Source/RecordingMockTransportSession.swift
- Tests/Source/SessionManager/APIMigrationManagerTests.swift
- Tests/Source/SessionManager/APIVersionResolverTests.swift
- Tests/Source/SessionManager/AccessTokenMigrationTests.swift
- Tests/Source/SessionManager/SessionManagerTests+APIVersionResolver.swift
- Tests/Source/SessionManager/SessionManagerTests.swift
- WireSyncEngine.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-1237" title="FS-1237" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-1237</a>  [iOS] Implement API version migrations
</td></table>
<br />
----
----
This PR introduces the `APIMigrationManager` that enables us to run migrations when we detect that the api version has changed. 
It also adds a migration for v3, `AccessTokenMigration`, which associates the session's client id to the access token.
https://github.com/wireapp/wire-ios-transport/pull/261
I've added 3 TODOs in the code. I plan on removing them before merging and I'll either implement changes in this PR or create tickets …
> feat(api-v3): add api migration mechanism + migrate access token FS-1237
